import type { DayPlan } from "../types";

const CORE = ["#DeepLearning", "#PyTorch", "#NeuralNetworks", "#AI", "#100DaysOfCode"];

export const week07: DayPlan[] = [
  /* DAY 43 */
  {
    day: 43, theme: "Neurons & perceptrons — DL from first principles", pillar: "ai-ml",
    posts: [
      { id: "d43-p1", day: 43, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "A neuron is a weighted sum + activation",
        copy: "📅 Day 43. Week seven begins. Welcome to deep learning.\n\n🧠 Strip away every textbook diagram you've ever seen of neural networks. The atomic unit is shockingly small.\n\nA neuron is — output = f(W·x + b)\n\nThat's it.\n→ x is the input vector.\n→ W is a weight vector (one weight per input feature).\n→ W·x is a dot product (linear combination).\n→ b is a bias (a single scalar shift).\n→ f is a non-linear activation function (ReLU, sigmoid, tanh, GELU).\n\nA single neuron computes a weighted sum of its inputs, adds a bias, and passes the result through a non-linearity. That's the whole story.\n\n🎯 A single neuron with sigmoid activation IS logistic regression from yesterday. Same math. Same loss function. Same training procedure. The neuron is just the building block.\n\n🏗 Stack neurons in a layer (n neurons, each producing one output from the same input). Stack layers (the output of layer 1 is the input to layer 2). Add a final output layer with the right activation for your task (sigmoid for binary, softmax for multi-class, none for regression).\n\nYou now have a multi-layer neural network. Universal approximator — given enough neurons and the right training, it can fit any function.\n\n🌐 That's the entire blueprint behind modern AI. GPT-4 has a few hundred billion of these neurons stacked across many layers. The architecture details (transformers, attention) are about HOW to stack and connect them efficiently. The atomic unit is still f(W·x + b).\n\n💡 Internalise the equation. The rest is plumbing.",
        hashtags: [...CORE, "#NeuralNetworks"],
        image: { template: "stat", headline: "f(Wx + b)", subhead: "The atomic unit of every neural net.", stat: { number: "1", label: "neuron = logistic regression" }, accent: "violet", aiPrompt: "Stat poster with single-neuron diagram, 1:1", canvaBrief: "Violet gradient. Big f(Wx+b)." }
      },
      { id: "d43-p2", day: 43, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Activation functions — the quick guide",
        copy: "🧠 Activation functions are the non-linear functions f() in our neuron equation. Without them, stacked neurons would collapse into a single linear function (linear composed with linear is linear). The non-linearity is what gives neural networks their power.\n\n📊 The six activations you'll meet:\n\n⚡ ReLU. max(0, x). The default for hidden layers since around 2012. Fast (no exp), sparse (negative values become 0), simple gradient. Sometimes 'dies' — neurons whose output is always 0 stop training. Leaky ReLU fixes this by allowing a small negative slope.\n\n🌊 GELU. A smoother variant of ReLU. The default in transformers and most modern architectures. Slightly more compute, slightly better behaviour. If in doubt, GELU.\n\n🎯 Sigmoid. σ(x) = 1 / (1 + e^-x). Output bounded to (0, 1). Used in the OUTPUT layer for binary classification (gives a probability). Almost never used in hidden layers anymore (suffers from vanishing gradients on deep networks).\n\n🎯 Softmax. Generalisation of sigmoid to multiple classes. Output is a probability distribution over k classes (sums to 1). Used in the OUTPUT layer for multi-class classification.\n\n📐 Tanh. (e^x - e^-x) / (e^x + e^-x). Output bounded to (-1, 1). Used in RNNs and a few other places where you want zero-centered output.\n\n🩹 Leaky ReLU. max(0.01*x, x). Same as ReLU but with a small slope for negative inputs. Use when you suspect 'dying ReLU' is happening.\n\n📋 The rule:\n→ Hidden layers — ReLU or GELU.\n→ Binary output — sigmoid.\n→ Multi-class output — softmax.\n→ RNN hidden state — tanh.\n→ ReLU dies — leaky ReLU.\n\n💡 90% of layers are ReLU or GELU. Don't overthink the activation choice.",
        hashtags: [...CORE, "#ActivationFunctions"],
        image: { template: "list", headline: "Activations — pick by layer",
          bullets: ["Hidden — ReLU / GELU", "Binary out — sigmoid", "Multi-class out — softmax", "RNN — tanh", "Dying ReLU? — leaky"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 5 rows."
        }
      },
      { id: "d43-p3", day: 43, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "A 2-layer network in 12 lines (PyTorch)",
        copy: "💻 The simplest non-trivial neural network — a 2-layer multilayer perceptron (MLP). Linear → ReLU → Linear. Trains MNIST in under a minute. Read this code; you've read 80% of every PyTorch model.\n\nLook at the snippet.\n\n🏗 Class MLP inherits from nn.Module. Every PyTorch model does this. nn.Module gives you parameter tracking, GPU movement, and serialisation for free.\n\n📦 In __init__, we define the layers as instance attributes. nn.Sequential stacks layers in order. nn.Linear(in, out) is a linear transformation (the 'Wx + b' from the morning post). nn.ReLU() is the activation function as a layer (callable).\n\n🔄 forward(x) defines the forward pass. PyTorch calls this when you do model(x). The Sequential takes care of running each layer in order.\n\n📊 Test — model = MLP(784, 256, 10). 784 inputs (flattened 28x28 MNIST image). 256 hidden units. 10 outputs (one per digit class). Then model(torch.randn(8, 784)) runs a batch of 8 random inputs through the model. Output shape is (8, 10) — one row of 10 logits per input.\n\n🎯 What's missing for actual classification — softmax (often baked into the loss function, like CrossEntropyLoss). Loss function. Optimiser. Training loop. We cover those tomorrow.\n\n💡 The pattern — define layers in __init__, run them in forward. The model is a compositional structure. To add a layer, add a line. To make it a CNN, swap nn.Linear for nn.Conv2d.\n\n🚀 12 lines. Real neural network. PyTorch's API is small enough to fit in your head; powerful enough to build any architecture you've heard of.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "MLP in 12 lines",
          code: { language: "python", snippet: "import torch\nimport torch.nn as nn\n\nclass MLP(nn.Module):\n    def __init__(self, d_in, d_hidden, d_out):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Linear(d_in, d_hidden),\n            nn.ReLU(),\n            nn.Linear(d_hidden, d_out),\n        )\n    def forward(self, x):\n        return self.net(x)\n\nmodel = MLP(784, 256, 10)\nprint(model(torch.randn(8, 784)).shape)   # torch.Size([8, 10])" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d43-p4", day: 43, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Initialise weights well, or training stalls",
        copy: "💡 Pro tip — bad weight initialisation can prevent training from making progress at all. The symptom — your loss flatlines from epoch 1, no matter how long you train.\n\n🚨 The classic failure — initialise all weights to zero. Now every neuron in a layer computes the same output, gets the same gradient during backprop, updates the same way. They never differentiate. The network has the capacity of a single neuron.\n\n✅ The fix — initialise from a small random distribution. The exact distribution depends on the activation function.\n\n🎯 Kaiming initialisation (He init). For ReLU and its variants. Variance scaled by 2 / fan_in (number of input units). Designed to keep activation magnitudes stable across layers in deep networks.\n\nnn.init.kaiming_normal_(layer.weight, nonlinearity='relu')\nnn.init.zeros_(layer.bias)\n\n🌊 Xavier initialisation (Glorot init). For sigmoid and tanh. Variance scaled by 2 / (fan_in + fan_out). Better for activations that have a different variance profile.\n\nnn.init.xavier_normal_(layer.weight)\n\n📦 Good news — PyTorch's defaults are usually fine. nn.Linear initialises with Kaiming uniform by default. nn.Conv2d does too. You only need to override for unusual architectures or when you're debugging weight scale issues.\n\n🔍 Diagnosis — if loss flatlines:\n\n1️⃣ Check if outputs are saturated (all close to 0 or 1 for sigmoid). Bad init or bad scaling.\n\n2️⃣ Check gradient norms. If they're zero or NaN, the gradients aren't flowing. Init or normalisation issue.\n\n3️⃣ Try a smaller learning rate. Sometimes init is fine but lr is too high and weights diverge in step 1.\n\n4️⃣ Check for dying ReLU. Many neurons stuck at zero output → switch to leaky ReLU.\n\n💡 Most of the time, defaults work. When they don't, the diagnostics above narrow it down fast.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "tip", headline: "Initialise weights, not zeros",
          bullets: ["Zero init = symmetry stuck", "Kaiming for ReLU", "Xavier for sigmoid/tanh", "PyTorch defaults usually fine"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d43-p5", day: 43, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 43 — neurons, framed",
        copy: "📅 End of Day 43. Welcome to deep learning week.\n\n✅ Recap:\n\n🧠 Neuron = f(Wx + b). The atomic unit. Single neuron with sigmoid is logistic regression. Stack neurons; stack layers; you have a neural network.\n\n📊 Activations — ReLU/GELU for hidden, sigmoid/softmax for output, tanh for RNNs. Don't overthink.\n\n💻 12-line MLP in PyTorch. nn.Module class, nn.Sequential composition, forward method. The pattern repeats for every model.\n\n🎯 Initialisation matters. Zero init kills training (symmetry trap). Kaiming for ReLU, Xavier for sigmoid/tanh. PyTorch defaults usually fine.\n\n🧠 The bigger picture — modern AI is built from this single equation, repeated billions of times in stacked layers. Transformers add attention; CNNs add convolutions; the underlying neuron is the same. Once you grok the unit, the architectures are just different ways of connecting them.\n\n🚀 Tomorrow, Day 44 — backpropagation. The chain rule that makes deep networks trainable. The optimiser families (Adam, AdamW, SGD). The training loop you'll write 100 times. The 'NaN loss? Lower lr first' rule.\n\n💼 We're 48% through. Foundations + Python + DSA + data + classical ML + (now) DL fundamentals. Three more weeks of ML/DL/NLP. Then RAG, agents, automation, career.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#NeuralNetworks"],
        image: { template: "quote", headline: "Stack neurons. Train. Repeat.", subhead: "Modern AI in 4 words.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 44 */
  {
    day: 44, theme: "Backpropagation — the chain rule, applied", pillar: "ai-ml",
    posts: [
      { id: "d44-p1", day: 44, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Backprop = chain rule + smart caching",
        copy: "📅 Day 44. Backpropagation is how neural networks learn. It scares beginners. It shouldn't — the idea is small once you've seen it.\n\n🔄 The training step has three phases:\n\n1️⃣ Forward pass. Run input through the network. Compute the output. Compute the loss (how wrong the output is vs the true label).\n\n2️⃣ Backward pass. Compute the gradient of loss with respect to every parameter. This is what tells the optimiser how to adjust each weight to reduce loss.\n\n3️⃣ Optimiser step. For each parameter, update it using the gradient. Typically — new_weight = old_weight - lr * gradient.\n\n🎓 The 'backward pass' is backpropagation. It's just the chain rule of calculus, applied repeatedly through the network's layers. The smart bit is reusing intermediate values from the forward pass — without that reuse, computing all gradients would be O(n²) in the number of parameters.\n\nWith reuse, it's O(n). Same complexity as the forward pass.\n\n🤖 PyTorch's autograd does all this automatically. You define the forward pass; you call .backward() on the loss; PyTorch computes every gradient and stores them. Then optimiser.step() applies them.\n\nYou never write the gradients by hand. Even for complex networks with custom layers, autograd handles the math. You just need to make sure your forward pass uses PyTorch operations (which know their gradients), not raw NumPy (which doesn't).\n\n💡 The mystique around backprop is undeserved. The mechanics are clean. The math (chain rule) is from first-year calculus. The implementation (autograd) is hidden from you. Your job is to define the model and the loss; the framework handles everything else.\n\n🚀 Forward, backward, step. Three phases. Repeat until loss is small.",
        hashtags: [...CORE, "#Backpropagation"],
        image: { template: "stat", headline: "forward → backward → step", subhead: "The training loop, in 3 words.", stat: { number: "3", label: "phases of every training step" }, accent: "violet", aiPrompt: "Stat poster, 1:1", canvaBrief: "Violet gradient. Big 3."
        }
      },
      { id: "d44-p2", day: 44, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Optimisers — Adam, SGD, AdamW",
        copy: "⚙️ Optimisers turn gradients into weight updates. There are dozens. Three cover 95% of cases.\n\n🐎 SGD with momentum. The classical optimiser. Plain stochastic gradient descent (subtract lr * gradient) plus momentum (a moving average of past gradients to accelerate in consistent directions). Used in many computer vision papers because it generalises slightly better than Adam at the end of long training runs.\n\nDownsides — needs careful learning rate tuning. Slow to converge in the early epochs.\n\nWhen to use — image models with cosine LR schedule. Final fine-tuning of large models when you've got the time.\n\n🎯 Adam. Adaptive Moment Estimation. Maintains per-parameter learning rates based on running estimates of gradient mean and variance. Converges fast in the early epochs without much LR tuning. The default for most NLP and many other tasks.\n\nDownsides — sometimes generalises slightly worse than SGD. Has a subtle bug with weight decay (next).\n\nWhen to use — almost any new training run. Default LR is 3e-4 for Adam.\n\n🔧 AdamW. Adam with proper weight decay decoupling. Original Adam had a subtle interaction between weight decay and the adaptive LR — basically, weight decay scaled by the gradient size, which isn't what you want. AdamW separates them. The original 'fixed Adam'.\n\nWhen to use — any time you want weight decay with an adaptive optimiser. Default for transformer fine-tuning. Default LR 1e-4 to 5e-5 for transformers.\n\n📋 The rule:\n→ Starting a new project — Adam, lr=3e-4.\n→ Image model with long training — SGD + momentum, lr=0.1, cosine schedule.\n→ Transformer training or fine-tuning — AdamW, lr=1e-4 to 5e-5, linear warmup + cosine decay.\n→ Anything weird — start with Adam, see what happens, adjust.\n\n💡 Optimiser choice matters less than people think. LR schedule and batch size matter more. Pick a reasonable optimiser and tune the schedule.",
        hashtags: [...CORE, "#Optimizers"],
        image: { template: "list", headline: "3 optimisers cover most cases",
          bullets: ["SGD + momentum — vision SOTA", "Adam — NLP default", "AdamW — transformers 2026", "Start lr=3e-4"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d44-p3", day: 44, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "The PyTorch training loop you'll write 100 times",
        copy: "💻 Every PyTorch training loop has the same shape. Memorise this template; the rest is variations.\n\nLook at the snippet.\n\n🛠 Setup — create the optimiser (AdamW with lr=3e-4 here) by passing model.parameters() (so the optimiser knows which weights to update). Create the loss function (CrossEntropyLoss for multi-class classification).\n\n🔄 Outer loop over epochs. Each epoch is one full pass through the training data.\n\n🔄 Inner loop over batches. train_loader yields (X, y) pairs. Each batch goes through the same five-step ritual.\n\n📲 Step 1 — Move X and y to the device (GPU if available). PyTorch tensors must be on the same device as the model.\n\n🧹 Step 2 — optim.zero_grad(). Clear gradients from the previous step. PyTorch accumulates gradients by default; without zero_grad, you'd be adding new gradients to old ones.\n\n➡️ Step 3 — Forward pass. logits = model(X). Output of the model.\n\n📐 Step 4 — Compute loss. loss_fn(logits, y) gives a scalar measuring how wrong the predictions are.\n\n⬅️ Step 5 — loss.backward(). Backpropagation. Computes gradients of loss with respect to every parameter, stores them in .grad attributes.\n\n👟 Step 6 — optim.step(). Apply the update rule (using gradients) to each parameter. The model is now slightly better.\n\nAt the end of each epoch, print the loss for monitoring. In real code, you'd also evaluate on validation data and possibly save a checkpoint.\n\n📋 This six-step ritual is the heart of every PyTorch training loop. Once you can write it from memory, you can train any model.\n\n🚀 Memorise the shape; specialise the model and loss for your problem.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Training loop — the shape",
          code: { language: "python", snippet: "import torch\n\noptim = torch.optim.AdamW(model.parameters(), lr=3e-4)\nloss_fn = torch.nn.CrossEntropyLoss()\n\nfor epoch in range(10):\n    for X, y in train_loader:\n        X, y = X.to(device), y.to(device)\n        optim.zero_grad()\n        logits = model(X)\n        loss = loss_fn(logits, y)\n        loss.backward()\n        optim.step()\n    print(f'epoch {epoch}: train loss {loss.item():.4f}')" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d44-p4", day: 44, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "If loss is NaN, check learning rate first",
        copy: "💡 Pro tip — when your loss diverges to NaN within the first 10 training steps, the cause is almost always one specific thing. Save yourself a debugging session.\n\n🚨 The symptoms:\n\n→ Loss goes from a normal number (say 2.3) to NaN within a few steps.\n→ Or loss explodes upward (10, 100, 1000, NaN).\n→ Or all your gradients become NaN and training stops working.\n\n🔍 The likely culprits, in order of probability:\n\n1️⃣ Learning rate too high. The optimiser is taking steps so large that weights overflow. This accounts for ~70% of NaN cases I've seen. Drop lr by 10x and try again. Often fixes it.\n\n2️⃣ Bad inputs. Check your training data for inf, NaN, or extremely large values (> 1e10). A single bad row can poison the gradient. Use torch.isfinite() to detect.\n\n3️⃣ Numerical instability. Some operations (exp(), log()) blow up at extreme values. Add gradient clipping — torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0) — to bound the gradient magnitude before the optimiser step.\n\n4️⃣ Mixed precision overflow. If you're training with fp16/bf16 (automatic mixed precision), some intermediate values can overflow the smaller dtype. Try disabling AMP to see if it stabilises. If it does, use a GradScaler properly.\n\n5️⃣ Initialisation bug. Custom layers initialised wrong might produce extreme outputs immediately. Check intermediate activation magnitudes.\n\n6️⃣ Bug in custom loss function. log() of zero, division by zero, etc. Add small epsilons (log(x + 1e-8)) to prevent.\n\n📋 My debugging order: lr first, inputs second, gradient clip third, then everything else.\n\n💡 The good news — NaN losses are usually fixable by step 1 or 2. Spend 5 minutes there before going deeper.",
        hashtags: [...CORE, "#PyTorchTips"],
        image: { template: "tip", headline: "NaN loss? lr first.",
          bullets: ["lr too high — drop 10x", "Check inputs for NaN/inf", "Add grad clip 1.0", "Disable AMP to test"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d44-p5", day: 44, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 44 — backprop, demystified",
        copy: "📅 End of Day 44.\n\n✅ Recap:\n\n🧮 Backprop = chain rule + smart caching. Forward pass computes outputs and loss. Backward pass computes gradients. Optimiser step applies updates. Three phases per training step.\n\n⚙️ Three optimisers cover most cases — SGD+momentum (vision), Adam (NLP default), AdamW (transformers). Default LR 3e-4 for Adam.\n\n💻 The PyTorch training loop you'll write 100 times — zero_grad, forward, loss, backward, step. Six-step ritual; the rest is variations.\n\n🚨 NaN loss? Lower learning rate first. ~70% of NaN losses are 'lr too high'. Then check inputs, add grad clip, then dig deeper.\n\n🧠 The bigger picture — PyTorch hides the math (autograd) so you can focus on architecture and training dynamics. The framework is doing the heavy lifting; your job is to define the model and pick reasonable hyperparameters.\n\n🚀 Tomorrow, Day 45 — PyTorch deeper. DataLoader for data pipelines. GPU device handling done right. Save and load models the right way. The eval+no_grad rule for inference.\n\n💼 The PyTorch core is small — Model, Loss, Optimiser, DataLoader, plus the training loop. Master these five and you can build any neural network.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Backpropagation"],
        image: { template: "quote", headline: "Forward. Backward. Step.", subhead: "Repeat until loss is small.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 45 */
  {
    day: 45, theme: "PyTorch — DataLoader, GPU, save/load", pillar: "ai-ml",
    posts: [
      { id: "d45-p1", day: 45, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Dataset + DataLoader = the PyTorch data pipeline",
        copy: "📅 Day 45. PyTorch's data abstraction is one of its cleanest design choices. Two classes, separation of concerns.\n\n📦 Dataset. Defines 'how to get one example'. Two methods — __len__ returns the dataset size, __getitem__(i) returns the i-th example as a (X, y) tuple. That's it. Subclass torch.utils.data.Dataset, implement these two methods, you have a dataset.\n\nThe Dataset doesn't care about batching or shuffling. It just knows how to retrieve individual examples. This separation lets you focus on the data loading logic without worrying about batching plumbing.\n\n🚚 DataLoader. Wraps a Dataset to add batching, shuffling, and parallel loading. DataLoader(dataset, batch_size=32, shuffle=True, num_workers=4) gives you batches of 32 examples, randomly shuffled, loaded by 4 worker processes in the background.\n\nThe DataLoader is what you iterate in your training loop — for X, y in train_loader: gives you batches.\n\n🔌 Why this design wins:\n\n→ Drop in any data source. Files, S3, an HTTP API, a generator, a database query. Implement Dataset; DataLoader handles the rest.\n\n→ Parallel loading. num_workers > 0 spawns worker processes that pre-fetch batches while your model is training. Removes data loading from the critical path.\n\n→ Memory efficiency. The DataLoader pulls one batch at a time. The dataset can be too big for memory; only the active batches need to fit.\n\n→ Reusability. Same DataLoader code works for image, text, audio, tabular. The Dataset is the swappable part.\n\n💡 For quick experiments, torch.utils.data.TensorDataset wraps existing tensors directly. tensor_dataset = TensorDataset(X, y) gives you a Dataset without writing a class. Pair with DataLoader and you're training in 5 lines.\n\n🚀 Master the pattern once; reuse it forever.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "list", headline: "Dataset + DataLoader",
          bullets: ["Dataset — single-example access", "DataLoader — batch + shuffle", "num_workers > 0 — parallel", "TensorDataset for quick wraps"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d45-p2", day: 45, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Move model and data to GPU correctly",
        copy: "🖥 GPU usage in PyTorch is straightforward — until it isn't. The number-one bug — model on GPU, data on CPU. PyTorch raises 'Expected all tensors to be on the same device' and you wonder why.\n\n📋 Three things must live on the same device:\n\n1️⃣ The model. model = model.to(device).\n\n2️⃣ The inputs. X = X.to(device) inside your training loop.\n\n3️⃣ The targets. y = y.to(device) inside your training loop.\n\nMismatch any of them → error.\n\n🎯 My default top-of-file device detection:\n\nimport torch\n\ndevice = (\n    'cuda' if torch.cuda.is_available() else\n    'mps'  if torch.backends.mps.is_available() else\n    'cpu'\n)\n\nThis tries CUDA (NVIDIA GPUs) first, then MPS (Apple Silicon), then falls back to CPU. The same code runs on a Linux GPU server, a MacBook M-series, or a Windows laptop without changes.\n\n📦 Then in code:\n\nmodel = MLP(...).to(device)  # once at startup\n\nfor X, y in loader:\n    X, y = X.to(device), y.to(device)  # every batch\n    out = model(X)\n    ...\n\n⚡ Pro tips:\n\n→ For very large datasets, pin_memory=True in DataLoader speeds up CPU→GPU transfer (~10-30% on heavy training).\n\n→ For multiple GPUs, torch.nn.DataParallel or torch.nn.DistributedDataParallel splits the batch across GPUs. Modern projects use DDP; DataParallel is legacy.\n\n→ For Apple Silicon, MPS support has improved a lot. Most operations now work; some don't. Check error messages and fall back to CPU for unsupported ops.\n\n💡 Get device handling right once at the top of your codebase. Then forget about it. The 'same device' bug becomes invisible.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Device-aware PyTorch",
          code: { language: "python", snippet: "import torch\n\ndevice = (\n    'cuda' if torch.cuda.is_available() else\n    'mps'  if torch.backends.mps.is_available() else\n    'cpu'\n)\nmodel = MLP(784, 256, 10).to(device)\n\nfor X, y in loader:\n    X, y = X.to(device), y.to(device)\n    out = model(X)" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d45-p3", day: 45, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Save and load — the right way",
        copy: "💾 PyTorch model serialisation has one rule that beginners constantly violate — save the state_dict, NOT the model object.\n\n📦 The wrong way:\n\ntorch.save(model, 'model.pt')\nmodel = torch.load('model.pt')\n\nThis pickles the entire model object including its class definition. Two problems:\n\n→ Loading requires the SAME class definition to be importable. If you renamed a layer or refactored the file structure, loading fails with cryptic errors.\n\n→ Tightly coupled to PyTorch internals. Changes to PyTorch versions can break loading.\n\n✅ The right way — save state_dict, which is a Python dict mapping parameter names to tensors:\n\ntorch.save(model.state_dict(), 'model.pt')\n\n# Later\nmodel = MLP(in_d, hid, out_d).to(device)  # recreate the architecture\nmodel.load_state_dict(torch.load('model.pt', map_location=device))\nmodel.eval()  # set to inference mode\n\nNotice the steps:\n\n1️⃣ Recreate the model architecture (you need the class available).\n\n2️⃣ Move it to the right device.\n\n3️⃣ Load the state_dict (parameters only).\n\n4️⃣ map_location=device handles the case where the model was saved on GPU but you're loading on CPU (or vice versa). Without it, you'd get device errors.\n\n5️⃣ model.eval() switches BatchNorm and Dropout to inference mode. Critical step (covered tonight in detail).\n\n💼 What this gives you:\n\n→ Portable. Load on different machines, different PyTorch versions, different devices.\n\n→ Future-proof. Your model architecture file can change names; as long as the layer structure is the same, the state_dict loads.\n\n→ Smaller files. Just the weights, no Python pickling overhead.\n\n💡 For production with frequent retraining, also save metadata — training date, evaluation metrics, hyperparameters used. JSON file alongside the .pt. Future-you will know what version is what.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Save state_dict, never the object",
          code: { language: "python", snippet: "torch.save(model.state_dict(), 'model.pt')\n\n# later\nmodel = MLP(in_d, hid, out_d).to(device)\nmodel.load_state_dict(\n    torch.load('model.pt', map_location=device)\n)\nmodel.eval()" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d45-p4", day: 45, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Always model.eval() and torch.no_grad() at inference",
        copy: "💡 Two flips at inference time. Skip either and you have subtle bugs.\n\n🎯 Flip 1 — model.eval()\n\nThis switches certain layers (BatchNorm, Dropout) into inference mode.\n\n→ Dropout in train mode randomly zeros out a fraction of activations. In eval mode, it does nothing (passes inputs through unchanged).\n\n→ BatchNorm in train mode uses the current batch's statistics for normalisation. In eval mode, it uses the running mean/variance accumulated during training.\n\nForget to call eval() and your model produces noisy, suboptimal outputs at inference. The bug is silent — outputs look reasonable, just not as good as they should be. Easy to miss; embarrassing in production.\n\n🚫 Flip 2 — torch.no_grad()\n\nDisables PyTorch's gradient tracking. Inference doesn't need gradients (we're not training); tracking them wastes memory and CPU.\n\nwith torch.no_grad():\n    output = model(X)\n\nMemory cost drops because intermediate activations don't need to be stored for backprop. Speed improves 30-50% because the autograd machinery is bypassed.\n\n🎯 The combined inference pattern:\n\nmodel.eval()\nwith torch.no_grad():\n    for X in test_loader:\n        X = X.to(device)\n        output = model(X)\n        # process output\n\n💼 In production with PyTorch:\n\n→ At model load, call model.eval() once. It stays in eval mode until you call model.train() to switch back.\n\n→ Wrap inference code in torch.no_grad(). Or use the @torch.no_grad() decorator on inference functions for cleaner syntax.\n\n→ For inference-only deployments (no training), consider torch.jit.trace or torch.compile for further speedups. We won't cover them in this sprint.\n\n💡 Two lines. Skipping either is a top-5 PyTorch bug. Do them both, every time.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "tip", headline: ".eval() + no_grad() at inference",
          bullets: ["model.eval() — flip dropout/BN", "torch.no_grad() — kill gradients", "Faster, lower memory", "Skipping = wrong outputs"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d45-p5", day: 45, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 45 — PyTorch hygiene",
        copy: "📅 End of Day 45.\n\n✅ Recap:\n\n📦 Dataset + DataLoader pattern. Dataset = single-example access. DataLoader = batching, shuffling, parallel loading. Reusable across data types.\n\n🖥 Device handling. Detect at startup; .to(device) for model and every batch. Same device for everything or PyTorch yells.\n\n💾 Save state_dict, not the model object. Recreate architecture at load time. map_location for cross-device loading. model.eval() after loading.\n\n🎯 Inference always has model.eval() + torch.no_grad(). Otherwise dropout adds noise and gradient tracking wastes resources.\n\n🧠 Reflection — PyTorch's API is small enough to fit in your head. Five concepts (Module, DataLoader, Loss, Optimiser, Device) plus the training loop covers 95% of what you'll write. Once you've internalised these, building any neural network architecture is composition.\n\n🚀 Tomorrow, Day 46 — CNNs. Convolutions, pooling, why they still matter for vision. Tiny CNN for MNIST in 14 lines. ResNet's skip connections that unlocked deep networks. The 'always start from a pretrained model' rule.\n\n💼 PyTorch fundamentals are done. Tomorrow we apply them to specific architectures.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "quote", headline: ".eval() + no_grad().", subhead: "Two lines that fix more bugs than any debugger.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 46 */
  {
    day: 46, theme: "CNNs — convolutions for vision", pillar: "ai-ml",
    posts: [
      { id: "d46-p1", day: 46, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "A convolution is a sliding dot product",
        copy: "📅 Day 46. CNNs (Convolutional Neural Networks) revolutionised computer vision in 2012 and still dominate small-to-medium image tasks today.\n\n🖼 The core operation — convolution.\n\nA 2D convolution slides a small kernel (typically 3x3 or 5x5) across an image. At each position, it computes a dot product between the kernel's weights and the corresponding image patch. The output is a new 2D map of activations.\n\nThe kernel learns features — edges, corners, textures, then more abstract patterns in deeper layers (eyes, wheels, faces). Same kernel, applied everywhere — translation invariance built in.\n\n🎯 Why CNNs beat MLPs on images:\n\n→ Locality. Pixels near each other are related; the convolution exploits that. An MLP has to relearn this from scratch.\n\n→ Translation invariance. A cat at the top-left of an image is still a cat at the bottom-right. Same kernel applied at every position handles it naturally. An MLP would need separate parameters for each position.\n\n→ Parameter sharing. The same kernel weights are used across the entire image. A 3x3 kernel has 9 parameters (plus a bias). An MLP doing equivalent work would have millions.\n\n→ Hierarchical features. Stack convolution layers; later layers see combinations of earlier features. Layer 1 learns edges; layer 2 learns corners and textures; layer 5 learns object parts; layer 10 learns objects.\n\n🏗 The standard CNN architecture — alternating convolution + pooling layers, ending with one or two fully-connected layers for classification. Pooling (max or average) downsamples the feature maps, reducing computation and adding some translation invariance.\n\n💡 Modern CNNs (ResNet, EfficientNet, ConvNeXt) refine this — skip connections, depthwise separable convolutions, channel attention. The core convolution operation is unchanged.\n\n🚀 Convolutions for vision is still the right tool. Even in 2026 when Vision Transformers exist, ResNet wins on small datasets and inference cost.",
        hashtags: [...CORE, "#CNN"],
        image: { template: "stat", headline: "kernel slides", subhead: "Same weights everywhere = parameter sharing", stat: { number: "3x3", label: "the kernel that started a revolution" }, accent: "violet", aiPrompt: "Stat poster with kernel-sliding glyph, 1:1", canvaBrief: "Violet gradient. Big 3x3."
        }
      },
      { id: "d46-p2", day: 46, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "ResNet — the architecture that survived",
        copy: "🏗 ResNet (2015) is one of the most influential papers in deep learning. The reason it survived a decade — it solved a fundamental problem nothing else had.\n\n🚨 The pre-ResNet problem. Adding more layers to a CNN made things WORSE, not better, past about 20 layers. Even with proper initialisation and ReLU activations, deep networks failed to train. Gradients vanished or exploded; layers stopped learning meaningfully.\n\nThis was counterintuitive — more parameters should mean more capacity. But empirically, deep networks underperformed shallow ones.\n\n🎯 ResNet's insight — skip connections. Add the input back to the output of every block.\n\noutput = block(input) + input\n\nInstead of computing block(input), compute block(input) + input. The block now learns the RESIDUAL (the difference between input and desired output) rather than the full transformation.\n\n🌊 Why this works:\n\n→ Gradient flow. The gradient flows directly through the skip connection during backprop. Even if block(input) has near-zero gradient, the +input term keeps things flowing. Networks 100+ layers deep become trainable.\n\n→ Identity is easy. If a layer has nothing useful to add, it can output approximately zero (the residual is zero), and the input passes through unchanged. The network learns when to use a layer.\n\n→ Implicit ensemble. With many skip connections, the network has many parallel paths. It behaves like an ensemble of shallower networks.\n\n🏆 In 2026, ResNet-50 (50 layers) is still the default backbone for many vision tasks. Vision Transformers (ViT) match or beat it on big data; ResNet wins on small datasets and at inference cost (smaller, faster).\n\n💡 The skip-connection idea spread far beyond ResNet. Transformers use it. Modern LLMs use it. U-Net for segmentation uses it. The +input pattern is one of deep learning's most reused ideas.\n\n🚀 Two characters. Massive impact.",
        hashtags: [...CORE, "#ResNet"],
        image: { template: "stat", headline: "x + f(x)", subhead: "The skip connection that unlocked deep CNNs.", stat: { number: "x + f(x)", label: "ResNet's two-character revolution" }, accent: "violet", aiPrompt: "Stat poster with skip-connection diagram, 1:1", canvaBrief: "Violet gradient. Big x + f(x)."
        }
      },
      { id: "d46-p3", day: 46, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Tiny CNN for MNIST in 14 lines",
        copy: "💻 The minimum viable CNN. 14 lines. Hits 99% accuracy on MNIST after 5 epochs. The skeleton of every computer-vision model you'll ever write.\n\nLook at the snippet.\n\n🏗 Class TinyCNN inherits from nn.Module. Layers defined in __init__ as nn.Sequential.\n\n📦 First convolution block:\n→ nn.Conv2d(1, 16, 3, padding=1) — 1 input channel (grayscale), 16 output channels (16 different kernels), 3x3 kernel size, padding=1 (keeps spatial size unchanged).\n→ nn.ReLU() — activation.\n→ nn.MaxPool2d(2) — downsample by 2x in each spatial dim. 28x28 image becomes 14x14.\n\n📦 Second convolution block:\n→ nn.Conv2d(16, 32, 3, padding=1) — 16 input channels, 32 output channels.\n→ nn.ReLU().\n→ nn.MaxPool2d(2) — 14x14 becomes 7x7.\n\n🔄 Classifier:\n→ nn.Flatten() — turn (32, 7, 7) tensor into (32 * 7 * 7,) vector. 1568 features.\n→ nn.Linear(1568, 128) — fully connected layer to 128 hidden units.\n→ nn.ReLU().\n→ nn.Linear(128, n_classes) — output layer to 10 logits (one per digit).\n\nNo softmax — CrossEntropyLoss applies it internally for numerical stability.\n\n📊 The shape progression — (B, 1, 28, 28) → (B, 16, 14, 14) → (B, 32, 7, 7) → (B, 1568) → (B, 128) → (B, 10).\n\nB is batch size. Channels grow (1 → 16 → 32) as spatial size shrinks (28 → 14 → 7). The flatten + dense layers do the final classification.\n\n🚀 This shape — alternating conv+pool, flatten, dense — is the basic CNN template. Larger models add more conv blocks, batch normalisation, dropout, residual connections. The skeleton is the same.\n\n💡 14 lines. Real working CV model.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Tiny CNN — MNIST 99%",
          code: { language: "python", snippet: "import torch.nn as nn\n\nclass TinyCNN(nn.Module):\n    def __init__(self, n_classes=10):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Conv2d(1, 16, 3, padding=1),  nn.ReLU(),\n            nn.MaxPool2d(2),\n            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(),\n            nn.MaxPool2d(2),\n            nn.Flatten(),\n            nn.Linear(32 * 7 * 7, 128), nn.ReLU(),\n            nn.Linear(128, n_classes),\n        )\n    def forward(self, x):\n        return self.net(x)" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d46-p4", day: 46, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Always start from a pretrained model",
        copy: "💡 Pro tip — for any computer vision task in 2026, start from a pretrained model. Training from scratch is almost always wrong.\n\n🤔 Why? Two reasons.\n\n📊 Pretrained models on ImageNet (or larger datasets) have learned useful features — edges, textures, shapes, common objects. These features TRANSFER to your task. Even if you're classifying medical images or industrial defects, the low-level features are similar.\n\n⏱ Training from scratch on small datasets (under 100k images) usually leads to overfitting. The model has too many parameters relative to your training data; it memorises rather than learns.\n\nFine-tuning a pretrained model on your data — typically 10x faster training, 10-30% better accuracy on small datasets. Free lunch.\n\n📦 The torchvision.models module has many pretrained options:\n\n→ ResNet (resnet18, resnet50) — the workhorse. Pretrained on ImageNet (1.2M images, 1000 classes).\n\n→ EfficientNet (efficientnet_b0 through b7) — better accuracy/cost tradeoff than ResNet. Use for production where inference cost matters.\n\n→ ViT (vit_b_16) — Vision Transformers. Best accuracy on big data; slower inference. Use when you have lots of training data.\n\n→ ConvNeXt — modern CNN with ViT-inspired changes. Strong all-around.\n\n🎯 The fine-tuning recipe:\n\n1️⃣ Load pretrained model. model = resnet50(weights='IMAGENET1K_V2').\n\n2️⃣ Replace the final layer. Originally 1000 classes; you have N. model.fc = nn.Linear(model.fc.in_features, N).\n\n3️⃣ Fine-tune. Train all layers with a small learning rate (1e-4 or smaller).\n\n4️⃣ Optionally — freeze early layers, train only the last few. Faster, less risk of overfitting on tiny datasets.\n\n💡 The transfer-learning lunch is free. Eat it.\n\n🚀 Use Hugging Face's image models for even more options — DINOv2 for self-supervised features, CLIP for image-text alignment, SAM for segmentation. The library is large; the API is clean.",
        hashtags: [...CORE, "#TransferLearning"],
        image: { template: "tip", headline: "Pretrained > scratch (almost always)",
          bullets: ["torchvision.models — pretrained ImageNet", "Swap final layer to your classes", "Fine-tune", "10-30% accuracy lift on small data"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d46-p5", day: 46, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 46 — CNNs in one breath",
        copy: "📅 End of Day 46.\n\n✅ Recap:\n\n🖼 Convolution = sliding dot product + parameter sharing. Locality, translation invariance, hierarchical features. The right tool for vision.\n\n🌊 ResNet's skip connections (x + f(x)) unlocked deep CNNs. Networks 100+ layers deep became trainable. Pattern reused everywhere — transformers, U-Nets, modern LLMs.\n\n💻 Tiny CNN for MNIST in 14 lines. Conv → ReLU → MaxPool → repeat → Flatten → Dense. The skeleton of every CV model.\n\n📦 Always start from a pretrained model. Training from scratch on small data overfits. ResNet, EfficientNet, ViT — all pretrained on ImageNet, fine-tune for your task. 10-30% accuracy lift for free.\n\n🧠 Reflection — vision is one of the most successful applications of deep learning. From AlexNet (2012) to today, the architecture has refined but the convolution operation is unchanged. The lesson — build on what works; don't rewrite the foundation when refinements suffice.\n\n🚀 Tomorrow, Day 47 — RNNs and LSTMs. Mostly historical now (transformers won), but the foundation that made transformers necessary. The 'pack variable-length sequences' tip for production.\n\n💼 We've covered the two main neural-network families — feedforward (MLPs, CNNs) and recurrent (tomorrow). Both are stepping stones to transformers (Day 53) which dominate modern AI.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#CNN"],
        image: { template: "quote", headline: "Pretrained beats from-scratch.", subhead: "Almost always.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 47 */
  {
    day: 47, theme: "RNNs & LSTMs — the predecessor to transformers", pillar: "ai-ml",
    posts: [
      { id: "d47-p1", day: 47, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "An RNN keeps a hidden state",
        copy: "📅 Day 47. Recurrent Neural Networks (RNNs) ruled sequential data from 2010 to 2018, then transformers replaced them. They're worth understanding for context.\n\n🔄 The core idea — process a sequence one element at a time, maintaining a hidden state that 'remembers' what's been seen so far.\n\nAt each step t:\nh_t = f(W_xh · x_t + W_hh · h_{t-1} + b)\n\nWhere:\n→ x_t is the input at this step.\n→ h_{t-1} is the hidden state from the previous step.\n→ h_t is the new hidden state.\n→ f is a non-linearity (typically tanh).\n→ W_xh and W_hh are weight matrices (shared across all time steps).\n\nThe hidden state acts as the model's memory. As you process the sequence, h_t accumulates information about everything seen so far.\n\n🎯 Useful for sequential data — text, audio, time-series, DNA sequences.\n\n⚠️ Big problem — vanishing/exploding gradients. When you backprop through many time steps, the gradient is multiplied by W_hh each step. If |W_hh| < 1, the gradient vanishes (model can't learn long-term dependencies). If |W_hh| > 1, it explodes (training diverges).\n\nIn practice, vanilla RNNs struggle to learn dependencies more than ~10 steps apart.\n\n🛠 The fix — LSTM (Long Short-Term Memory) and GRU (Gated Recurrent Unit). Both add explicit 'gates' that decide what to remember, forget, and write to the hidden state. The gating mechanism enables long-range learning that vanilla RNNs can't do.\n\nLSTMs ruled NLP from 2014 to 2018. Then attention/transformers came.\n\n💡 In 2026, you'll write RNNs rarely. They survive in resource-constrained settings (mobile speech recognition, embedded systems) and as a teaching example. For everything else — transformers.",
        hashtags: [...CORE, "#RNN"],
        image: { template: "stat", headline: "h_t = f(Wx + Wh + b)", subhead: "Sequential memory, one step at a time.", stat: { number: "h_t", label: "the hidden state every RNN carries" }, accent: "violet", aiPrompt: "Stat poster with sequence-arrow glyph, 1:1", canvaBrief: "Violet gradient. Big h_t."
        }
      },
      { id: "d47-p2", day: 47, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Why transformers replaced RNNs",
        copy: "🔄 The RNN's biggest limitation isn't the math — it's the architecture. RNNs are inherently sequential.\n\n🐌 At step t, you can't compute h_t until you've computed h_{t-1}. There's no way to parallelise across the sequence. On a GPU with thousands of cores, an RNN uses one core for each sequence position; the others sit idle.\n\nFor a sequence of length 1000, an RNN takes 1000 sequential operations. On a transformer (next week's deep dive), the same sequence can be processed in ONE parallel operation.\n\n📈 Concrete numbers. Same hardware, same model size:\n\n→ RNN training on 1000-token sequences: limited by single-core speed. ~100 sequences/sec.\n\n→ Transformer training on 1000-token sequences: limited by GPU parallelism. ~1000 sequences/sec (10x faster).\n\nMultiply across millions of sequences for a full training run. Days vs weeks.\n\n🎯 Beyond speed, transformers also win on quality:\n\n→ Long-range dependencies. Attention can directly link any two positions in the sequence (O(1) path length). RNNs need to propagate information through many steps (O(n) path length), which decays.\n\n→ Better gradient flow. Attention has direct paths; RNNs have sequential paths that compound vanishing/exploding.\n\n→ More parameters per FLOP. Transformer compute scales with attention + feed-forward, both highly parallel. RNNs scale with sequence length.\n\n🏆 Result — transformers replaced RNNs across the board. GPT, BERT, Claude, Llama, Gemini — all transformers. Speech-to-text models — transformers (Whisper). Image transformers (ViT) compete with CNNs.\n\n📋 Where RNNs still survive in 2026:\n\n→ Mobile/edge devices where transformer compute is too expensive.\n→ Streaming/online tasks where you need to process input as it arrives (some real-time speech).\n→ Specific niche tasks where the sequential bias is helpful.\n→ Teaching, because they're conceptually simpler.\n\n💡 Know the history. Use transformers.",
        hashtags: [...CORE, "#Transformers"],
        image: { template: "compare", headline: "RNN vs Transformer",
          compare: { leftLabel: "RNN", leftItems: ["Sequential per step", "Limited context", "Small / on-device", "Hard to scale"], rightLabel: "Transformer", rightItems: ["Parallel attention", "Long context", "Cloud / GPU", "SOTA everywhere"] },
          accent: "violet", aiPrompt: "Compare poster, 1:1", canvaBrief: "Split. Grey vs violet. VS badge."
        }
      },
      { id: "d47-p3", day: 47, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Tiny LSTM in PyTorch",
        copy: "💻 PyTorch's nn.LSTM does the gating internally. You don't implement gates by hand; you just declare input size, hidden size, number of layers.\n\nLook at the snippet.\n\n🏗 LSTMClassifier:\n→ self.emb = nn.Embedding(vocab, d_emb) — turns integer token IDs into dense vectors.\n→ self.lstm = nn.LSTM(d_emb, d_hid, batch_first=True) — processes the embedded sequence.\n→ self.head = nn.Linear(d_hid, n_classes) — maps the final hidden state to class logits.\n\n📊 batch_first=True changes input shape from (seq, batch, features) to (batch, seq, features), which matches every other layer in PyTorch. Always pass batch_first=True.\n\n🔄 forward(x):\n→ e = self.emb(x) — embed the input. Shape (batch, seq, d_emb).\n→ out, (h, c) = self.lstm(e) — run through LSTM.\n  → out is the per-step output (batch, seq, d_hid). Useful for tasks where you predict at each step (sequence labeling).\n  → h is the final hidden state (1, batch, d_hid). Useful for sequence classification.\n  → c is the final cell state (1, batch, d_hid). LSTMs have both.\n→ self.head(h.squeeze(0)) — project the final hidden state to logits. Squeeze removes the leading dim of 1.\n\n🎯 The output — (batch, n_classes) of logits. Pair with CrossEntropyLoss for training.\n\n📋 Variants:\n→ Stacked LSTM — pass num_layers=2 or more. Multiple LSTM layers on top of each other. More capacity, more compute.\n→ Bidirectional LSTM — pass bidirectional=True. Processes the sequence both forward and backward; the output is the concatenation. Useful for tasks where future context matters (NER, POS tagging).\n→ GRU — nn.GRU instead of nn.LSTM. Same API, slightly less compute, often equivalent quality. Use when LSTM is overkill.\n\n💡 LSTMs are simple in PyTorch. The complexity is in WHEN to use them (rare in 2026) and HOW to handle variable-length sequences (next post).",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "nn.LSTM — sequence to logits",
          code: { language: "python", snippet: "import torch.nn as nn\n\nclass LSTMClassifier(nn.Module):\n    def __init__(self, vocab, d_emb, d_hid, n_classes):\n        super().__init__()\n        self.emb = nn.Embedding(vocab, d_emb)\n        self.lstm = nn.LSTM(d_emb, d_hid, batch_first=True)\n        self.head = nn.Linear(d_hid, n_classes)\n    def forward(self, x):\n        e = self.emb(x)\n        out, (h, c) = self.lstm(e)\n        return self.head(h.squeeze(0))" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d47-p4", day: 47, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Use packed sequences for variable-length",
        copy: "💡 Pro tip for RNN code (rare in 2026, but useful when needed) — handle variable-length sequences with packed sequences.\n\n🚨 The problem. Different sequences in a batch have different lengths. To batch them, you pad shorter ones to match the longest. The LSTM still iterates through all the padding, wasting compute.\n\n📊 For a batch of [length=10, length=50, length=200] sequences, naive padding pads everything to 200. The LSTM iterates 200 times for the length=10 sequence, 190 of which are useless padding processing.\n\n✅ The fix — torch.nn.utils.rnn.pack_padded_sequence + pad_packed_sequence.\n\nfrom torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence\n\npacked = pack_padded_sequence(input, lengths, batch_first=True, enforce_sorted=False)\nout, (h, c) = lstm(packed)\nout, lengths = pad_packed_sequence(out, batch_first=True)\n\nPack the input with the original lengths. The LSTM processes only the actual tokens, skipping the padding. Then unpack to get back to padded form.\n\n📈 Speedup — proportional to the variation in lengths. If sequences vary 10x in length (10-200), you can save up to 10x compute. If they're roughly uniform, gain is smaller.\n\n🎯 Other RNN tips for production:\n\n→ Sort sequences by length before batching. Reduces wasted padding within batches.\n\n→ Use bucketing — group sequences of similar length into the same batch. More uniform length per batch, less padding waste.\n\n→ For Transformers, use attention masks instead. Same problem (padding), different solution. Attention masks tell the model to ignore padded positions.\n\n💡 In 2026, you'll mostly write transformers, not RNNs. But if you maintain RNN code, packed sequences are the pro move. The training-loop boilerplate is small; the speedup is real on length-varying datasets.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "tip", headline: "Pack variable-length sequences",
          bullets: ["pack_padded_sequence(...)", "Skips padding compute", "pad_packed_sequence to invert", "Or use transformers + masks"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d47-p5", day: 47, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 47 — sequential models, framed",
        copy: "📅 End of Day 47.\n\n✅ Recap:\n\n🔄 RNN = hidden state across time. h_t = f(Wx + Wh + b). Sequential by design.\n\n🚧 Vanishing/exploding gradients limited vanilla RNNs to ~10 steps of memory. LSTMs and GRUs solved this with explicit gates.\n\n🏆 Transformers won. Parallel attention, longer context, better gradient flow. RNNs survive on the edge and in niche cases.\n\n💻 Tiny LSTM in PyTorch — 8 lines. nn.LSTM handles gates internally; you just declare sizes.\n\n📦 Pack variable-length sequences for RNN production work. Or use transformers with attention masks.\n\n🧠 Reflection — RNNs were the cutting edge in 2016. By 2018, transformers had displaced them. The history matters because the SAME architectural shifts continue to happen — Vision Transformers are displacing CNNs in some domains; Mamba and state-space models are challenging transformers in others. Stay flexible; the dominant architecture changes every 5-10 years.\n\n🚀 Tomorrow, Day 48 — regularisation. Dropout, weight decay, early stopping. Stop your model from memorising. Then training tricks Day 49 wraps the week.\n\n💼 Three days left in week 7. We're 53% through the sprint. Next week is NLP and transformers — the dominant architecture of the 2020s.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#RNN"],
        image: { template: "quote", headline: "Transformers won.", subhead: "RNNs survive on the edge.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 48 */
  {
    day: 48, theme: "Regularisation — stop memorising, start generalising", pillar: "ai-ml",
    posts: [
      { id: "d48-p1", day: 48, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Overfitting in one chart",
        copy: "📅 Day 48. Overfitting is the central failure mode in deep learning. Spotting it is the first skill; preventing it is the second.\n\n📊 The diagnostic chart. Train your model. Plot training loss and validation loss vs epoch.\n\nThree possible patterns:\n\n📉 Both losses drop together → underfitting. The model needs more capacity, more training, or both. Low priority concern.\n\n📈 Train drops, validation drops less but follows → working well. The gap between train and val tells you how much overfitting is happening, but it's manageable.\n\n📉📈 Train keeps dropping, validation drops then RISES → overfitting. The model is memorising training data instead of learning patterns. The divergence point is when you should have stopped.\n\nThis is the chart you check after every training run. Save it. Look at it.\n\n🛠 Six tools to combat overfitting, in order of effectiveness:\n\n1️⃣ More data. Always the best fix. Often impossible.\n\n2️⃣ Smaller model. Reduce parameters until train and val track each other.\n\n3️⃣ Dropout. Randomly zero out neurons during training. Forces the model not to depend on any single neuron.\n\n4️⃣ Weight decay. L2 penalty on weights. Keeps weights from growing too large.\n\n5️⃣ Data augmentation. Generate more training examples by transforming existing ones (image flips, text perturbations).\n\n6️⃣ Early stopping. Stop training when validation loss stops improving. Use the model from the best epoch, not the last one.\n\n💡 Almost every model needs at least one of these. Most need two or three. The exact combination depends on the model size, dataset size, and task.\n\n🎯 Tomorrow's training-tricks post wraps these into a production training loop. Today we cover them individually.",
        hashtags: [...CORE, "#Regularization"],
        image: { template: "list", headline: "6 regularisers in your toolkit",
          bullets: ["More data", "Simpler model", "Dropout", "Weight decay", "Data augmentation", "Early stopping"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 6 rows."
        }
      },
      { id: "d48-p2", day: 48, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Dropout — the trick that almost magically works",
        copy: "🎲 Dropout is one of those rare deep-learning tricks that almost always helps and is dirt cheap to add. Born from a 2014 paper; ubiquitous since.\n\n🔧 The mechanism. During training, randomly set a fraction p of activations to zero. Different random subset every forward pass. Effectively trains many subnets simultaneously.\n\nAt inference, no dropout. All neurons participate. Outputs scaled by (1-p) to compensate for the magnitude difference.\n\nPyTorch handles the inference scaling automatically when you set model.eval(). Don't manually scale.\n\n🧠 Why it works:\n\n→ Forces redundancy. Since any neuron might be dropped, the model can't depend on any single neuron. It learns robust, distributed representations.\n\n→ Implicit ensembling. Each forward pass uses a different subnet. The trained model behaves like an ensemble of many partial models. Ensembles generalise better than individual models.\n\n→ Reduces co-adaptation. Without dropout, neurons can co-evolve to compensate for each other's quirks (you scratch my back). Dropout breaks this dependency.\n\n📊 Typical p values:\n\n→ 0.1-0.2 in CNNs (after activation in conv blocks).\n\n→ 0.1-0.3 in transformers (attention dropout + residual dropout, both small).\n\n→ 0.5 in older MLPs and pre-2015 architectures (less common now).\n\n⚠️ Where to NOT use dropout:\n\n→ Output layer. Adds noise where you want a clean prediction.\n\n→ The very last hidden layer before output. Same reason.\n\n→ Batch normalisation does some of dropout's job; combining can be over-regularising.\n\n→ Very small models (<100k params) — they need all the capacity they have.\n\n🎯 In PyTorch — nn.Dropout(p=0.2) added between layers. Activates only during model.train(); silent during model.eval(). The framework handles the mode-switch.\n\n💡 Add dropout. Tune p between 0.1 and 0.3. Move on.",
        hashtags: [...CORE, "#Dropout"],
        image: { template: "stat", headline: "p = 0.1 to 0.3", subhead: "Modern dropout rates", stat: { number: "10-30%", label: "neurons dropped during training" }, accent: "violet", aiPrompt: "Stat poster with neuron-grid glyph, 1:1", canvaBrief: "Violet gradient. Big 10-30%."
        }
      },
      { id: "d48-p3", day: 48, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Early stopping in 8 lines",
        copy: "⏱ Early stopping is the cheapest, most-effective regularisation technique. Save compute AND prevent overfitting.\n\n🎯 The idea — track validation loss every epoch. If it doesn't improve for N epochs in a row, stop training. Reload the model from the best epoch.\n\nMost training frameworks (HuggingFace Trainer, PyTorch Lightning, fastai) have this built in as a callback. For plain PyTorch, here's the 8-line version.\n\nLook at the snippet.\n\n📊 Variables:\n→ best_val = float('inf'). Best validation loss seen so far. Lower is better.\n→ patience = 5. How many epochs to wait without improvement before stopping.\n→ bad = 0. Counter for consecutive non-improving epochs.\n\n🔄 Each epoch:\n→ Train one epoch.\n→ Evaluate on validation set.\n→ If val improved (val < best_val) — update best_val, save the model checkpoint, reset bad to 0.\n→ Otherwise — increment bad. If bad >= patience, stop training.\n\nAfter training stops, load the best.pt checkpoint. That's your trained model.\n\n📋 Why this works so well:\n\n→ Prevents overfitting. The model from the best epoch is the one that generalises best, even if you trained for many more epochs.\n\n→ Saves compute. No point continuing to train if validation is degrading. Stop early; iterate faster.\n\n→ Eliminates the 'how many epochs' hyperparameter. Just set max_epochs to a generous number; let early stopping figure out the right point.\n\n🎯 Tuning patience:\n\n→ Small patience (3-5) — stops training quickly. Use when training is fast and you want quick iteration.\n\n→ Large patience (10-20) — gives the model more chances to recover. Use when validation loss is noisy or you have time for long runs.\n\n💡 Add early stopping to every training script. The 8 lines pay back enormously.\n\n🎁 Bonus — also save model EMA (exponential moving average of weights). Often performs better than the snapshot at peak validation. Modern training tricks.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Early stopping — minimal",
          code: { language: "python", snippet: "best_val = float('inf')\npatience, bad = 5, 0\n\nfor epoch in range(100):\n    train_one_epoch()\n    val = evaluate()\n    if val < best_val:\n        best_val = val\n        torch.save(model.state_dict(), 'best.pt')\n        bad = 0\n    else:\n        bad += 1\n        if bad >= patience:\n            print(f'stop at epoch {epoch}'); break" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d48-p4", day: 48, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Weight decay ≠ L2 reg in Adam",
        copy: "💡 Pro tip with subtle math — Adam + weight_decay= isn't actually L2 regularisation, despite looking like it. Use AdamW instead.\n\n🤔 The history. Adam was published in 2014 with a weight_decay parameter. It worked... mostly. Researchers noticed that Adam-with-weight-decay didn't generalise as well as SGD-with-weight-decay. The community shrugged and said 'Adam is just like that'.\n\nIn 2017, a paper called 'Decoupled Weight Decay Regularization' (Loshchilov & Hutter) figured out why.\n\n🧮 The math. L2 regularisation adds (lambda * w^2) to the loss. The gradient of this is (2 * lambda * w). So in plain SGD, weight decay subtracts (lr * 2 * lambda * w) from each weight per step. The decay scales with lr.\n\nAdam, however, scales gradients by an adaptive learning rate (depending on past gradient magnitudes). When you add the L2 gradient term, IT ALSO gets scaled by the adaptive rate. The net effect — weight decay strength varies per parameter, depending on each parameter's gradient history. Often inconsistent and worse.\n\n✅ The fix — AdamW. Decouples weight decay from the gradient. Subtracts (lr * lambda * w) from each weight directly, BEFORE the adaptive scaling. Net effect — weight decay is consistent and applies as you'd expect.\n\nAdamW was retrofitted into PyTorch as torch.optim.AdamW. Drop-in replacement. Same hyperparameters; subtly better behaviour.\n\n📊 Default weight decay values:\n→ Transformers — 0.01 (this is the value used in BERT, GPT, etc).\n→ CNNs — 5e-4 (smaller because CNNs have fewer parameters and less risk of weight explosion).\n→ MLPs — typically 1e-4 to 1e-3.\n\n🎯 The takeaway:\n\n→ If you're using Adam with weight decay, switch to AdamW. Free upgrade.\n→ If you're using SGD, weight_decay= works correctly. No change needed.\n\n💡 The bug was real but small. The fix is one character — Adam → AdamW. Use it.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "tip", headline: "Use AdamW for weight decay",
          bullets: ["Adam + decay = subtle bug", "AdamW = correct decoupling", "WD = 0.01 (transformers)", "WD = 5e-4 (CNNs)"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d48-p5", day: 48, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 48 — generalise, don't memorise",
        copy: "📅 End of Day 48.\n\n✅ Recap:\n\n📊 Overfitting in one chart. Train loss drops; val loss starts rising. The divergence point is where you should stop.\n\n🎲 Dropout. Random zeroing during training. Forces redundancy and acts as implicit ensemble. p = 0.1-0.3 in modern architectures.\n\n⏱ Early stopping in 8 lines. Track validation loss; stop after N epochs without improvement; reload best checkpoint. Saves compute and prevents overfitting.\n\n🔧 AdamW for weight decay. Adam + weight_decay= is subtly buggy due to adaptive LR interaction. AdamW fixes it. Drop-in replacement.\n\n🧠 Reflection — generalisation is the central problem of deep learning. Models with millions of parameters can memorise their training data perfectly; the goal is to constrain them so they learn patterns instead. Dropout, weight decay, augmentation, early stopping — each one a soft constraint that says 'don't memorise'.\n\n🚀 Tomorrow, Day 49 — production training tricks that put it all together. LR schedules (warmup + cosine). Mixed precision (free 2x speedup). Gradient clipping. The 'use Lightning or HF Trainer instead of writing your own' wisdom. Then we wrap week 7.\n\n💼 Two days to the end of week 7. Then NLP and transformers (week 8), the architecture under every modern AI system you've used.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Regularization"],
        image: { template: "quote", headline: "If train loss < val loss, regularise.", subhead: "Or get more data. Or both.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 49 */
  {
    day: 49, theme: "Production training tricks + week 7 wrap", pillar: "ai-ml",
    posts: [
      { id: "d49-p1", day: 49, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Learning-rate schedule beats fixed lr",
        copy: "📅 Day 49. Last day of week seven.\n\n📈 Constant learning rate is fine for tutorials. For real training, learning rate schedules give you better final loss and faster convergence.\n\n🎯 The two-phase modern recipe — linear warmup followed by cosine decay.\n\n🔥 Phase 1 — linear warmup. First 5-10% of training steps. Start lr near zero; ramp linearly up to your target lr. Why — Adam's adaptive learning rates are unreliable in the first few steps (variance estimates haven't stabilised). Starting with a tiny lr prevents the optimiser from blowing up immediately.\n\n🌊 Phase 2 — cosine decay. Rest of training. Gradually drop lr from target down to near zero following a cosine curve. Why — the optimiser benefits from large steps early (find the rough region of optimum) and small steps late (refine the optimum). Cosine gives a smooth transition.\n\nMath — lr(t) = lr_max * 0.5 * (1 + cos(pi * t / T)) where t is current step, T is total steps. Simple to implement; effective in practice.\n\n📊 Alternative — ReduceLROnPlateau. When validation loss stops improving, drop lr by a factor (typically 0.5 or 0.1). Simpler than cosine; works when you don't know total steps in advance.\n\nUsed when — you're not sure how long training will take, you want robust 'just works' behaviour without scheduler tuning.\n\n🎯 The choice in 2026:\n\n→ Transformer training/fine-tuning — warmup + cosine. The de facto standard.\n→ CNN training — warmup + cosine, OR step decay (drop lr at fixed milestones).\n→ Quick experimentation — constant lr is fine. Schedules matter for final-quality runs.\n\n💡 The single biggest improvement most teams don't make — adopt warmup + cosine. Often beats months of architecture tuning. PyTorch has CosineAnnealingLR + LinearLR built in; combine with SequentialLR.\n\n🚀 LR schedule is a free upgrade. Use it.",
        hashtags: [...CORE, "#LearningRate"],
        image: { template: "list", headline: "LR schedule — modern default",
          bullets: ["Linear warmup — first 5-10%", "Cosine decay — rest", "Plateau drop as fallback", "Constant LR is rarely best"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d49-p2", day: 49, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Mixed precision (AMP) — free 2x speedup",
        copy: "⚡ Free 2x speedup on modern GPUs (NVIDIA Volta, Ampere, Hopper) — train in fp16 or bfloat16 instead of fp32.\n\n🧮 The math. fp32 (32-bit floats) is the default. fp16 / bfloat16 are 16-bit alternatives. Smaller representation, faster operations.\n\nWhy it speeds things up:\n\n→ Tensor cores on modern GPUs do mixed-precision matrix multiplication 8-16x faster than full fp32. Same hardware; way more throughput.\n\n→ Memory bandwidth is half. Loading half the bytes per parameter; faster everywhere.\n\n→ Memory footprint drops 50%. You can train larger batches or larger models on the same GPU.\n\n🛡 Numerical stability is preserved by keeping a master copy of weights in fp32. Forward and backward passes happen in fp16; the gradient updates are applied to the fp32 master copy. The fp32 master is then copied to fp16 for the next forward pass.\n\nGradient scaling — fp16 has limited range. Small gradients (common late in training) can underflow to zero. The trick — multiply the loss by a scale factor before backprop; gradients are scaled up; divide back before optimiser step. PyTorch's GradScaler handles this automatically.\n\n📦 Code:\n\nfrom torch.amp import autocast, GradScaler\nscaler = GradScaler()\n\nwith autocast(device_type='cuda'):\n    out = model(x)\n    loss = loss_fn(out, y)\n\nscaler.scale(loss).backward()\nscaler.step(optim)\nscaler.update()\n\nThree extra lines. 2x speedup. Half the memory. Same final accuracy on most tasks.\n\n🚨 When NOT to use AMP:\n\n→ Tasks with extreme dynamic range (some scientific computing). Test first.\n\n→ Custom layers that don't have fp16 implementations. Modern PyTorch is fine for almost everything.\n\n→ Old hardware (pre-Volta). The speedup comes from tensor cores; without them, no benefit.\n\n💡 If you're not using mixed precision in 2026, you're leaving 2x on the table. Try it.",
        hashtags: [...CORE, "#MixedPrecision"],
        image: { template: "stat", headline: "2x", subhead: "Mixed-precision speedup vs fp32", stat: { number: "2x", label: "training speedup with AMP — same accuracy" }, accent: "violet", aiPrompt: "Stat poster, 1:1", canvaBrief: "Violet gradient. Big 2x."
        }
      },
      { id: "d49-p3", day: 49, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Production training loop — every trick",
        copy: "💻 Putting it all together — the production training loop with every trick from this week.\n\nLook at the snippet.\n\n🛠 Setup:\n→ AdamW optimiser (proper weight decay).\n→ CosineAnnealingLR scheduler (lr decays cosinely over epochs).\n→ GradScaler for mixed precision.\n\n🔄 Per epoch, per batch:\n→ Move X, y to device.\n→ Zero gradients.\n→ With autocast — forward pass and loss in fp16/bf16.\n→ scaler.scale(loss).backward() — gradients computed in scaled fp16, then reverse-scaled.\n→ scaler.unscale_(opt) — undo the scale before clipping.\n→ Gradient clipping — clip total gradient norm to 1.0. Prevents catastrophic updates from outlier gradients.\n→ scaler.step(opt) — optimiser step (skipped if gradients are NaN).\n→ scaler.update() — update the scale factor for next iteration.\n\n📊 At end of each epoch — sched.step() updates the learning rate.\n\nThis is the modern training loop. AMP (2x speedup), AdamW (correct weight decay), cosine decay (better convergence), gradient clipping (stability), early stopping (would be added on top).\n\n🚀 Real numbers — same model, same data, same final accuracy:\n→ Naive PyTorch loop — 60 minutes per epoch.\n→ With this production loop — ~25 minutes per epoch.\n→ Plus less hyperparameter sensitivity (LR scheduler reduces dependence on initial lr).\n\n📋 Things this loop is missing for completeness:\n→ Validation evaluation per epoch.\n→ Logging to TensorBoard / Weights & Biases.\n→ Model checkpointing.\n→ Multi-GPU support (DDP).\n→ Early stopping callback.\n\nRather than add them by hand, use a framework. That's tonight's tip.\n\n💡 Memorise this loop shape. It's the foundation of every serious training run you'll write.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Production training loop",
          code: { language: "python", snippet: "from torch.amp import autocast, GradScaler\nfrom torch.optim.lr_scheduler import CosineAnnealingLR\n\nopt = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=0.01)\nsched = CosineAnnealingLR(opt, T_max=epochs)\nscaler = GradScaler()\n\nfor epoch in range(epochs):\n    for X, y in loader:\n        X, y = X.to(device), y.to(device)\n        opt.zero_grad()\n        with autocast(device_type='cuda'):\n            loss = loss_fn(model(X), y)\n        scaler.scale(loss).backward()\n        scaler.unscale_(opt)\n        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n        scaler.step(opt); scaler.update()\n    sched.step()" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d49-p4", day: 49, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Use Lightning or HF Trainer instead of writing your own",
        copy: "💡 Pro tip — past your first 10 training loops, stop writing them by hand. Use a framework.\n\n📦 Three frameworks worth knowing:\n\n🤗 HuggingFace Trainer. Best for transformer fine-tuning. Handles AMP, gradient accumulation, distributed training, checkpointing, evaluation, logging — all with sensible defaults. Most NLP work in 2026 uses Trainer or its extensions (TRL, PEFT).\n\n⚡ PyTorch Lightning. Clean abstraction over plain PyTorch. You define a LightningModule (model + train/val/test steps); Lightning handles the loop, callbacks, checkpointing, multi-GPU, mixed precision. Used by many vision and audio teams.\n\n🚀 HuggingFace Accelerate. Lower-level than Trainer. Lets you keep your training loop's structure while abstracting the device/distributed-training plumbing. Used when you need custom training logic but want easy multi-GPU.\n\n🎯 Why use a framework:\n\n→ Battle-tested. Edge cases (mixed precision overflow, gradient sync across GPUs, checkpoint resume) are handled correctly. Your hand-rolled version probably has bugs you haven't found.\n\n→ Multi-GPU for free. PyTorch Lightning's 'accelerator' or HF Trainer's 'fsdp' enables multi-GPU with one config flag. Implementing DDP correctly by hand is non-trivial.\n\n→ Logging baked in. TensorBoard, Weights & Biases, MLflow — all integrated. One log call sends to all configured backends.\n\n→ Saves time. The boilerplate (loop, checkpointing, early stopping, eval) is hundreds of lines. Frameworks reduce it to a couple dozen.\n\n🛠 When to write your own loop:\n\n→ First few times you train, to understand the mechanics.\n\n→ Highly custom training (RL, GANs, complex multi-task setups).\n\n→ Embedded/edge deployments where framework overhead matters.\n\n💡 For 95% of production training, frameworks win. Don't reinvent the loop.\n\n🚀 The energy you save goes to data, architecture, and evaluation — the parts that actually matter.",
        hashtags: [...CORE, "#MLEngineering"],
        image: { template: "tip", headline: "Use a training framework",
          bullets: ["HF Trainer — transformers", "Lightning — clean abstraction", "Accelerate — multi-GPU", "Stop reinventing the loop"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d49-p5", day: 49, postNumber: 5, slot: "night", type: "recap", pillar: "career",
        title: "Week 7 done — deep learning fundamentals",
        copy: "📅 End of week 7. 49 days. 245 posts. We're 54% through the sprint.\n\n✅ Week 7 in seven topics:\n\n🧠 Neurons + activations. f(Wx + b). ReLU/GELU for hidden, sigmoid/softmax for output, tanh for RNNs. PyTorch's defaults are good.\n\n🔄 Backprop + optimisers. Forward, backward, step. Three optimisers (SGD+momentum, Adam, AdamW) cover most cases. NaN loss = lower lr first.\n\n📦 PyTorch hygiene. Dataset + DataLoader. Device handling. Save state_dict. eval + no_grad at inference.\n\n🖼 CNNs. Convolutions = sliding dot product + parameter sharing. ResNet's skip connections (x + f(x)) unlocked deep networks. Always start from a pretrained model.\n\n🔄 RNNs. Hidden state across time. Gradient issues solved by LSTMs/GRUs. Transformers won; RNNs survive on the edge.\n\n🛡 Regularisation. Dropout, weight decay, early stopping, AdamW. Each one a soft constraint that prevents memorisation.\n\n⚡ Production training tricks. LR warmup + cosine decay. Mixed precision (AMP) for 2x speedup. Gradient clipping for stability. Use a framework (HF Trainer, Lightning) for non-toy training.\n\n🧠 The big takeaway from week 7 — deep learning is mostly engineering, not math. The math behind backprop is calculus from the 1960s. The hard parts are the engineering — efficient training, reproducibility, scaling, regularisation. The frameworks abstract most of this; your job is to use them well.\n\n🚀 Next week — NLP and transformers. The architecture under every LLM you've used. From tokenisation to attention to the transformer block to BERT vs GPT. Then RAG (week 9-10) builds on top.\n\n💼 We're past halfway. The remaining six weeks are the AI-modern stack — NLP, RAG, agents, automation, career. Strap in.\n\n👋 See you in week 8.",
        hashtags: [...CORE, "#90DaysOfAI"],
        image: { template: "quote", headline: "7 weeks down. 6 to go.", subhead: "Next: tokenizers, embeddings, attention, transformers.", accent: "violet", aiPrompt: "Pastel violet quote with 49/90 progress, 1:1", canvaBrief: "Pastel violet quote with 49/90 violet bar." }
      },
    ]
  },
];
