import type { DayPlan } from "../types";

const CORE = ["#MachineLearning", "#scikitlearn", "#Python", "#AI", "#100DaysOfCode"];

export const week06: DayPlan[] = [
  /* DAY 36 */
  {
    day: 36, theme: "ML problem framing — supervised, unsupervised, RL", pillar: "ai-ml",
    posts: [
      { id: "d36-p1", day: 36, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "ML, framed in 3 boxes",
        copy: "📅 Day 36. Week six begins. We've built the foundation; now we go into actual machine learning.\n\n🧠 Before any code, frame the problem. Every ML problem fits into one of three boxes — and naming the box determines what algorithms apply, what data you need, and what 'success' even means.\n\n📦 Box 1 — Supervised learning. You have inputs AND labels. Predict the label for new inputs. Two flavours — classification (label is a category, like 'spam' or 'not spam') and regression (label is a number, like 'house price'). 95% of real ML jobs are supervised. Most ML APIs you'll ship live here.\n\n📦 Box 2 — Unsupervised learning. You have inputs but NO labels. Find hidden structure. Clustering (group similar items), dimensionality reduction (compress to fewer features while keeping structure), anomaly detection (flag the weird ones). Useful for exploratory analysis and as preprocessing.\n\n📦 Box 3 — Reinforcement learning. An agent acts in an environment, gets rewards, learns a policy that maximises long-term reward. Game playing, robotics, recommendation systems with feedback loops. Most exciting; least common in practical jobs.\n\n💡 Most ML jobs are supervised. Most real impact comes from getting the labels right — clean labels, sufficient labels, labels that actually represent what you want to predict. Don't underestimate the labelling step. I've seen models fail because the 'positive' label was applied inconsistently across training data, and the model dutifully learned the inconsistency.\n\n🎯 Frame first. Pick the box. Then pick the algorithm. The other order leads to forced fits and wasted effort.",
        hashtags: [...CORE, "#MLConcepts"],
        image: { template: "list", headline: "ML in 3 boxes",
          bullets: ["Supervised — labels", "Unsupervised — structure", "Reinforcement — rewards", "Most jobs are supervised"],
          accent: "violet", aiPrompt: "Three-box ML diagram, violet, 1:1", canvaBrief: "White grid. 3 large boxes. Labels in violet."
        }
      },
      { id: "d36-p2", day: 36, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "The ML loop in 6 steps",
        copy: "🔄 Every supervised ML project follows the same six-step loop. Knowing the loop is half the discipline of shipping ML that actually works.\n\n1️⃣ Frame the problem. What's the input? What's the output? What metric makes a good model? If you can't answer these three questions in one sentence each, you're not ready to start. I've seen multi-quarter projects fail because step 1 was rushed.\n\n2️⃣ Get and clean data. The 60% from week 5. Real data is messy — handle that before modelling. The cleaner your data, the easier everything downstream.\n\n3️⃣ Split. Train / validation / test. Train on train. Tune on validation. Final score on test (touched ONCE at the end, never to tune). If you tune on test, you've leaked — your reported number is optimistic by 2-5%, sometimes more.\n\n4️⃣ Train a baseline. Linear regression for regression, logistic regression for classification. ALWAYS start with a baseline. The baseline tells you what 'better than nothing' looks like and gives you a number to beat.\n\n5️⃣ Iterate. Better features, different model classes, hyperparameter tuning. The art is here — informed by EDA, guided by validation metric, bounded by time.\n\n6️⃣ Evaluate on test. Once. Deploy. Monitor. The test number is your honest estimate of production performance. The monitoring catches drift.\n\n⚠️ Most teams skip steps 1 and 6. They frame loosely (the project drifts) and deploy without monitoring (the model degrades silently). The good news — if you do all six, you're already top quartile by execution.\n\n🚀 Discipline beats cleverness in ML. Most of the time.",
        hashtags: [...CORE, "#MLPipeline"],
        image: { template: "list", headline: "ML loop — 6 steps",
          bullets: ["1. Frame problem", "2. Data + clean", "3. Split", "4. Baseline", "5. Iterate", "6. Eval + deploy"],
          accent: "violet", aiPrompt: "6-step pipeline poster, violet, 1:1", canvaBrief: "White grid. 6 numbered rows."
        }
      },
      { id: "d36-p3", day: 36, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Train/validation/test split — never skip val",
        copy: "💻 Three-way split. Train ~64%, validation ~16%, test 20%. The most-skipped step in ML, and the most-expensive one to skip.\n\n🎯 Why three sets, not two? Because the validation set is your hyperparameter-tuning sandbox. You train on train, evaluate on val, adjust hyperparameters (learning rate, regularisation, model architecture), repeat. The validation set sees your tuning decisions; it's no longer an unbiased estimate of generalisation.\n\n🔒 Test is sacred. Touched exactly once, at the end, after you've committed to a final model. The test score is your honest estimate of production performance.\n\n⚠️ If you tune hyperparameters on the test set, you've leaked. The model is optimised against the test data; reported test score is optimistic by 2-5% (sometimes more for small datasets). Looks great in your report; disappoints in production.\n\n📊 For small datasets, use cross-validation on the train+val portion. K-fold (typically k=5 or k=10) gives you K different train/val splits; train K models, average their validation scores. More robust estimate than a single split. Keep test held out separately.\n\nLook at the snippet. We use stratify=y to preserve class proportions in each split. Critical for imbalanced classification — without stratify, you might end up with all positive cases in test by accident, and your training set won't have any to learn from.\n\n🔢 random_state=42 makes the split reproducible. Pin it. Different splits give different scores; without a fixed seed, you can't compare experiments.\n\n💡 Three-way split takes 30 seconds to write. Saves entire categories of bug. Always.",
        hashtags: [...CORE, "#scikitlearn"],
        image: { template: "code", headline: "Three-way split — the right way",
          code: { language: "python", snippet: "from sklearn.model_selection import train_test_split\n\nX_trainval, X_test, y_trainval, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y\n)\nX_train, X_val, y_train, y_val = train_test_split(\n    X_trainval, y_trainval, test_size=0.2, random_state=42, stratify=y_trainval\n)\n# X_train ~64% | X_val ~16% | X_test 20%" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d36-p4", day: 36, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Pick the metric BEFORE training",
        copy: "💡 Pro tip that I learned the hard way — pick your evaluation metric BEFORE you start training. If you decide it after results come in, you'll cherry-pick.\n\n🎯 Why this matters. After training, you'll see a bunch of numbers — accuracy, F1, precision, recall, AUC, log-loss. They tell different stories. The temptation is to report whichever number looks best. That's confirmation bias dressed as analysis.\n\n📊 For binary classification:\n\n→ Class-balanced + cost-symmetric (false-positive and false-negative cost about the same) → accuracy is fine.\n\n→ Imbalanced + want to minimise false negatives (medical diagnosis, fraud detection) → recall first, then precision.\n\n→ Imbalanced + want a single number → F1 (harmonic mean of precision and recall) or PR-AUC.\n\n→ Probability calibration matters → Brier score or log-loss.\n\n📈 For regression:\n\n→ Symmetric error matters → RMSE.\n\n→ Robust to outliers → MAE.\n\n→ Multiplicative errors (forecast, demand) → MAPE or sMAPE.\n\n→ Hard upper bound on target → quantile loss at the relevant quantile.\n\n📋 My rule — write the metric in the README before you start training. State it explicitly. 'We're optimising for F1 on the positive class because false negatives are 3x worse than false positives.' Now everyone knows the goal.\n\n⚠️ The trap to avoid — silently changing metric mid-project because the original one isn't going well. If you change it, document why, and reset the baseline against the new metric. Otherwise you're just moving the goalpost.\n\n🔒 Pick once. Stick. Report honestly.",
        hashtags: [...CORE, "#MLBestPractices"],
        image: { template: "tip", headline: "Pick the metric first",
          bullets: ["Balanced binary → accuracy", "Imbalanced → F1 / PR-AUC", "Regression → RMSE / MAE", "Document before training"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d36-p5", day: 36, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 36 — frame before you fit",
        copy: "📅 End of Day 36. Week six begins. We're now in actual machine learning territory.\n\n✅ What we covered today:\n\n📦 Three boxes — supervised, unsupervised, reinforcement. Most jobs are supervised; most impact comes from clean labels.\n\n🔄 The 6-step ML loop — frame, data+clean, split, baseline, iterate, evaluate+deploy. Most teams skip steps 1 and 6; doing both puts you in the top quartile.\n\n💻 Three-way train/val/test split with stratify=y for classification. The validation set is your hyperparameter sandbox; test is touched once.\n\n🎯 Pick the metric BEFORE training. Document it. Don't cherry-pick after results.\n\n🧠 Reflection — ML is more discipline than cleverness. The teams that ship great ML aren't the ones with the smartest tricks; they're the ones that frame the problem precisely, clean the data ruthlessly, and pick metrics that match their business goal. Cleverness within that frame is great. Cleverness outside the frame is wasted.\n\n🚀 Tomorrow, Day 37 — linear regression. The workhorse you must understand before any neural net makes sense. The closed-form solution. The MSE/RMSE/MAE choice. The 'always compare against a dumb baseline' rule.\n\n💼 We're 40% through the sprint. Five weeks of foundation behind us; we now spend three weeks (6, 7, 8) on the core ML/DL stack, then four weeks on RAG and agents and automation, and one week on career.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#MachineLearning"],
        image: { template: "quote", headline: "Frame the problem.", subhead: "Then fit.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 37 */
  {
    day: 37, theme: "Linear regression — the model you must understand", pillar: "ai-ml",
    posts: [
      { id: "d37-p1", day: 37, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Linear regression in one sentence",
        copy: "📅 Day 37. Linear regression is the most underestimated model in machine learning. It's also the one you must understand before any neural net makes sense.\n\n🧮 The whole model in one equation — y = X·w + b. Output is a linear combination of features (X·w) plus a bias (b). Learn the weights w and bias b such that the predicted y is close to the actual y on training data.\n\n📊 'Close' usually means minimum squared error. Sum of (predicted - actual)^2 across all training examples. Take derivative; set to zero; solve. The result has a closed-form solution — the normal equations. No gradient descent needed for small problems.\n\n🎯 Why it's foundational:\n\n1️⃣ It's the baseline you compare every fancy model against. A model that doesn't beat linear regression on tabular data is usually not worth deploying.\n\n2️⃣ Its assumptions — linearity, independence of errors, normal residuals — are the assumptions that deep learning violates and gets away with. Understanding what assumption is being violated tells you what model to reach for next.\n\n3️⃣ The math (least squares, maximum likelihood under Gaussian errors) underlies almost every ML loss function you'll ever see. MSE in neural networks is least squares. Cross-entropy in classification is maximum likelihood under a different distribution. The structure repeats.\n\n💡 If linear regression solves your problem, ship it. Less code, easier to debug, faster to retrain, more interpretable. The bias toward complex models is a self-imposed cost.\n\n🚀 Master this before transformers. The transformer's final layer is, mathematically, a linear regression on top of learned features.",
        hashtags: [...CORE, "#LinearRegression"],
        image: { template: "stat", headline: "y = Xw + b", subhead: "The simplest model. The most underrated.", stat: { number: "y=Xw+b", label: "the equation under most ML you'll touch" }, accent: "violet", aiPrompt: "Stat poster with line-of-best-fit glyph, 1:1", canvaBrief: "Violet gradient. Big y=Xw+b."
        }
      },
      { id: "d37-p2", day: 37, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "MSE, RMSE, MAE — pick by error shape",
        copy: "📊 Three regression metrics, three different stories about your errors. Pick by what kind of error matters most for your problem.\n\n📐 MSE — Mean Squared Error. Sum of (y_true - y_pred)^2 divided by N. Penalises large errors quadratically. A prediction that's 10 off contributes 100 times more to the loss than one that's 1 off. Smooth gradient (good for training neural nets). Sensitive to outliers (a few bad predictions dominate the average).\n\n📏 RMSE — Root Mean Squared Error. Square root of MSE. Same units as your target (helpful for interpretation). 'My RMSE is $1200' means the model is typically off by about $1200 on house price predictions. Inherits MSE's outlier sensitivity.\n\n📐 MAE — Mean Absolute Error. Average of |y_true - y_pred|. Linear in error. A prediction off by 10 contributes 10x more than one off by 1, not 100x. Robust to outliers. Less smooth gradient (some optimisers prefer MSE).\n\n🎯 The choice depends on what you're optimising for:\n\n→ Errors should hurt proportionally → MAE.\n\n→ Big errors are catastrophically worse than small ones (forecasting demand, where being short by 100 units costs more than being short by 10) → MSE/RMSE.\n\n→ Median outcome matters more than mean → MAE.\n\n💡 My rule of thumb — report BOTH RMSE and MAE in evaluation. The gap between them tells you about outlier influence. If RMSE is much larger than MAE (like 3x), outliers are dominating; investigate before trusting the model.\n\n📋 For papers and reports — pick one as the primary metric, mention the other for context. Don't bury the inconvenient one.",
        hashtags: [...CORE, "#Metrics"],
        image: { template: "list", headline: "MSE / RMSE / MAE",
          bullets: ["MSE — squared, smooth", "RMSE — same units as y", "MAE — robust to outliers", "Report RMSE + MAE both"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid. 4 rows."
        }
      },
      { id: "d37-p3", day: 37, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Linear regression — sklearn vs from scratch",
        copy: "💻 Two implementations of linear regression. Three lines with sklearn. Two lines with NumPy. Worth seeing both — you understand what sklearn is doing under the hood.\n\n📦 Sklearn version. Three lines. LinearRegression() creates the model. .fit(X, y) computes the weights and bias from training data. .predict(X_new) generates predictions. Done.\n\n🧮 Closed-form NumPy version. Two lines after the augmentation. We add a column of ones to X (so the bias gets absorbed into the weight vector). Then the formula w = (X^T X)^-1 X^T y gives us the weights directly. This is the closed-form solution to the least-squares problem.\n\nThe pseudo-inverse (np.linalg.pinv) handles the case where X^T X is singular — happens when features are perfectly collinear or when you have more features than samples. Numerically stable; standard practice.\n\n⚖️ Why both versions exist. Sklearn's LinearRegression internally does almost exactly this — solves the normal equations with a numerically stable method (LAPACK's gelss or gelsd, depending). Wrapping it gives you scoring methods, parameter persistence, sklearn pipeline integration. The two-liner skips all that.\n\n🚀 For small problems — closed-form is exact and fast. O(d^3) for inversion, where d is feature count. Fine for d up to a few thousand.\n\n📈 For large problems (millions of features, millions of samples) — gradient descent is faster. SGD updates weights one batch at a time without ever materialising X^T X.\n\n💡 Knowing both gives you the connection from classical ML to deep learning. Same loss function. Different optimisation. Same idea.",
        hashtags: [...CORE, "#scikitlearn"],
        image: { template: "code", headline: "Linear regression — two ways",
          code: { language: "python", snippet: "from sklearn.linear_model import LinearRegression\nimport numpy as np\n\n# sklearn — 3 lines\nm = LinearRegression().fit(X, y)\npred = m.predict(X_new)\n\n# closed-form numpy — 2 lines\nXb = np.c_[np.ones(len(X)), X]\nw = np.linalg.pinv(Xb.T @ Xb) @ Xb.T @ y" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d37-p4", day: 37, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Always compare against a dumb baseline",
        copy: "💡 Tonight's pro tip — before you report any model's performance, beat the dumb baseline. By 'dumb baseline' I mean the simplest possible thing that predicts.\n\n🤔 What's the dumb baseline?\n\n📊 For regression — predict the mean of the training target. Always. For every test input. Compute RMSE.\n\n🎯 For classification — predict the majority class. For every test input. Compute accuracy / F1.\n\n💼 The dumb baseline gives you a floor. Your model has to beat it to be worth the compute, the deployment effort, and the maintenance burden.\n\n📈 Sklearn has DummyRegressor and DummyClassifier built in for exactly this. Three lines to set up, instant baseline.\n\n⚠️ I've seen plenty of 'great models' that beat the dumb baseline by 0.5%. Most aren't worth deploying. The cost of running an ML model in production — inference latency, monitoring, retraining, on-call rotations for when it breaks — needs to be earned by meaningfully better predictions.\n\n💵 Quantify the win. If the dumb baseline has 78% accuracy and your model has 79%, the marginal value of one percentage point depends on the use case. For high-stakes problems (medical diagnosis), 1% is huge. For ad clickthrough prediction at scale, 1% might be huge or might be invisible noise.\n\n🎯 The discipline — always report the gap, not just the score. 'Our model achieves 84% accuracy, vs 76% for the majority-class baseline (+8 points).' Now the reader knows what the model actually contributes.\n\n💡 Beating yourself isn't the goal. Beating the dumb baseline by a meaningful margin is.",
        hashtags: [...CORE, "#MLBestPractices"],
        image: { template: "tip", headline: "Always beat the dumb baseline",
          bullets: ["DummyRegressor — predict mean", "DummyClassifier — majority", "Report gap", "0.5% gain ≠ great model"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d37-p5", day: 37, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 37 — the baseline that doesn't lie",
        copy: "📅 End of Day 37. Linear regression done.\n\n✅ Recap:\n\n🧮 Linear regression in one equation — y = Xw + b. The simplest model and the most underrated. Foundation under every loss function you'll see.\n\n📊 MSE, RMSE, MAE — pick by error shape. MSE/RMSE punish large errors quadratically. MAE is robust to outliers. Report both.\n\n💻 Sklearn (3 lines) vs closed-form NumPy (2 lines). Same answer; sklearn wraps the same math with conveniences.\n\n🎯 Always beat the dumb baseline. DummyRegressor / DummyClassifier give you a floor. 0.5% gain over baseline rarely justifies the production cost.\n\n🧠 A broader thought — linear regression is what you compare to when you want to know if your fancy model is worth the complexity. If LightGBM beats linear regression by 8 points, ship LightGBM. If by 0.5 points, ship linear regression — same accuracy, fraction of the maintenance.\n\n🚀 Tomorrow, Day 38 — logistic regression. Same math; different output. The bridge to neural networks. Sigmoid squashes the linear output to a probability; cross-entropy loss replaces MSE; the model becomes a single neuron.\n\n💼 Once you understand linear and logistic regression, you've understood 80% of the math behind every ML model — including modern deep learning. The rest is bigger and stacked.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#LinearRegression"],
        image: { template: "quote", headline: "Linear first. Always.", subhead: "If a linear model wins, you're done.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 38 */
  {
    day: 38, theme: "Logistic regression — classification, framed simply", pillar: "ai-ml",
    posts: [
      { id: "d38-p1", day: 38, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Logistic regression is linear regression in disguise",
        copy: "📅 Day 38. Logistic regression is one of the most important models in ML — and it's literally linear regression with one extra step.\n\n🧮 Linear regression — y = Xw + b. Output is unbounded; could be any real number.\n\n🎯 Logistic regression — σ(Xw + b). Same Xw + b, then squashed through the sigmoid function σ(z) = 1 / (1 + e^-z). Output is now bounded between 0 and 1, interpretable as a probability.\n\n📊 The sigmoid maps:\n→ -∞ → 0\n→ 0 → 0.5\n→ +∞ → 1\n\n🎯 Decision rule — if σ(Xw + b) > 0.5, predict class 1; otherwise class 0. Threshold tunable based on the cost of false positives vs false negatives.\n\n📐 Loss function — cross-entropy (log-loss). Mathematically derived from maximum likelihood under a Bernoulli (yes/no) distribution. Computationally similar to MSE but designed for probabilities.\n\n🧠 The bigger insight — logistic regression is a single-neuron neural network. Literally. One linear layer + sigmoid activation. Modern neural networks just stack many of these (with non-linearities between).\n\n🚀 Why this matters for understanding deep learning. The classification head of every neural network is essentially logistic regression on top of learned features. The transformer's final layer that predicts the next token? Logistic regression on the embedding. The image classifier's final layer? Logistic regression on the convolution output. Same math; different feature pipeline.\n\n💡 Master logistic regression and you've understood the output layer of every classifier ever built. The rest is feature engineering and stacked layers.",
        hashtags: [...CORE, "#LogisticRegression"],
        image: { template: "stat", headline: "σ(Xw + b)", subhead: "Linear regression squashed to (0, 1)", stat: { number: "σ", label: "the sigmoid that turns regression into classification" }, accent: "violet", aiPrompt: "Stat poster with sigmoid curve, 1:1", canvaBrief: "Violet gradient. Big σ symbol."
        }
      },
      { id: "d38-p2", day: 38, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Class imbalance — the silent metric killer",
        copy: "⚠️ Class imbalance is one of the top reasons ML models silently underperform in production.\n\n🤔 The setup — 95% of your training rows are class 0, 5% are class 1. You train a logistic regression. Accuracy on validation is 95.2%. Looks great. Ship it.\n\n🚨 Reality — your model probably predicts class 0 for almost everything. Accuracy is 95% because the prior alone gives you 95%. The model adds essentially zero signal on the minority class. Useless for what you actually wanted.\n\n🎯 Four fixes for class imbalance:\n\n1️⃣ Use a different metric. Accuracy is misleading on imbalanced data. Use F1 (harmonic mean of precision and recall on the positive class), PR-AUC (area under the precision-recall curve), balanced accuracy (mean of recall on each class). All three reward catching the minority class properly.\n\n2️⃣ Stratify your splits. stratify=y in train_test_split. Preserves class proportions in each split. Without stratify, you might end up with 0% of the minority class in the test set on small datasets.\n\n3️⃣ Class weights. class_weight='balanced' in sklearn auto-weights inversely by class frequency. The model now pays more attention to minority-class errors. Same data, different loss weights.\n\n4️⃣ Resample. SMOTE creates synthetic minority examples by interpolating between real ones. Use carefully — SMOTE can create unrealistic synthetic examples in high-dim feature space. Apply BEFORE the train/test split is fine; AFTER is leakage.\n\n📊 The first thing I do on any classification task — print value_counts() of y. If imbalanced (say >70/30), change strategy before training. Otherwise you're optimising for the wrong thing.",
        hashtags: [...CORE, "#ClassImbalance"],
        image: { template: "list", headline: "4 fixes for imbalanced classes",
          bullets: ["Better metric (F1, PR-AUC)", "stratify=y in splits", "class_weight='balanced'", "SMOTE — careful"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid. 4 rows."
        }
      },
      { id: "d38-p3", day: 38, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Logistic regression with proper diagnostics",
        copy: "💻 Beyond accuracy — three diagnostics that tell the actual story of a classifier. classification_report, confusion_matrix, roc_auc_score.\n\n📊 classification_report shows precision, recall, F1 per class — plus the overall accuracy and macro/weighted averages. One function call. Reveals whether your model is good at one class but weak at another.\n\n📊 confusion_matrix is the 2x2 (or NxN) matrix of true vs predicted. The diagonal is correct predictions; off-diagonal is errors. Look at off-diagonal cells to see WHICH class your model confuses with WHICH other class. For a fraud model, you might see 'we miss most fraud cases' (low recall) or 'we flag too many legit transactions' (low precision). The matrix shows you exactly where.\n\n📈 roc_auc_score — area under the ROC curve. Threshold-independent measure of how well the model separates classes. AUC of 0.5 is random; 1.0 is perfect. Useful when you want to evaluate the model's ranking ability without committing to a specific threshold.\n\nLook at the snippet. We use class_weight='balanced' to handle imbalance, train, predict probabilities (predict_proba returns the full P(y=1|X), not just the binary class). Then we report all three diagnostics.\n\n💡 max_iter=2000. The default in some sklearn versions is 100, which can fail to converge on harder problems. Bumping to 2000 gives the optimiser room. If it still doesn't converge, your features probably need scaling (StandardScaler) before fitting.\n\n🎯 The lesson — accuracy alone is misleading. Always look at the full picture. precision, recall, F1, confusion matrix, AUC. Five numbers tell more than one.",
        hashtags: [...CORE, "#scikitlearn"],
        image: { template: "code", headline: "Logistic regression — full eval",
          code: { language: "python", snippet: "from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import (\n    classification_report, confusion_matrix, roc_auc_score\n)\n\nm = LogisticRegression(class_weight='balanced', max_iter=2000)\nm.fit(X_train, y_train)\np = m.predict(X_val)\nproba = m.predict_proba(X_val)[:, 1]\n\nprint(classification_report(y_val, p))\nprint(confusion_matrix(y_val, p))\nprint('AUC:', roc_auc_score(y_val, proba))" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d38-p4", day: 38, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Threshold ≠ 0.5",
        copy: "💡 Pro tip that escapes most beginners — the default classification threshold is 0.5, and it's almost never optimal for your problem.\n\n🤔 Recap — logistic regression outputs a probability. To turn it into a class prediction, you compare the probability to a threshold. By default, > 0.5 means class 1. But why 0.5?\n\n💵 The 'right' threshold depends on the cost asymmetry of false positives vs false negatives.\n\n🚨 Fraud detection. Missing fraud (false negative) costs the company $X per case. Flagging a legit transaction as fraud (false positive) costs Y per case in customer experience. If X > 10*Y, you should lower the threshold — call more things fraud, even if more of those are wrong, because catching the real cases matters more.\n\n🏥 Medical screening. Missing a disease (false negative) is much worse than a false positive that leads to a follow-up test. Lower threshold; higher recall.\n\n🛒 Spam detection. Marking real email as spam (false positive) might be much worse than letting some spam through (false negative). Higher threshold.\n\n📈 The technique — use precision_recall_curve from sklearn. Computes precision and recall at every possible threshold. Plot them. Pick the threshold that maximises the metric you actually care about (F1, F2, F0.5 — F-beta scores weight recall more or less than precision).\n\n🎯 In production, threshold and model are separate concerns. Train the model. Then sweep threshold against held-out data and your business metric. Deploy both together.\n\n💡 The model gives you a probability. The threshold is your business decision. Don't conflate them.",
        hashtags: [...CORE, "#MLEngineering"],
        image: { template: "tip", headline: "Tune the threshold, not just the model",
          bullets: ["Default 0.5 is rarely best", "Optimise on PR curve", "Pick by business cost", "Probability != decision"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d38-p5", day: 38, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 38 — classification, framed cleanly",
        copy: "📅 End of Day 38.\n\n✅ Recap:\n\n🎯 Logistic regression = linear regression + sigmoid. Output bounded to (0,1) — a probability. Single-neuron neural network in disguise.\n\n⚠️ Class imbalance silently kills metrics. Four fixes — better metric (F1, PR-AUC), stratified splits, class weights, SMOTE. Always check value_counts(y) first.\n\n📊 Diagnostics — classification_report, confusion_matrix, AUC. Five numbers tell more than one.\n\n💡 Threshold ≠ 0.5. Tune by business cost. Use precision_recall_curve to pick.\n\n🧠 The bigger picture — logistic regression is the output head of every classifier you'll ever build. Modern neural networks add layers of feature learning before this final logistic step. Understanding the math here means understanding the output of every classifier — from spam filters to image classifiers to language models predicting the next token.\n\n🚀 Tomorrow, Day 39 — decision trees. The most interpretable model in ML and the building block of random forests + gradient boosting. The Gini-vs-entropy debate (spoiler: it doesn't matter much). The two hyperparameters that prevent overfitting.\n\n💼 We're ramping up. Linear, logistic, trees, ensembles, k-means, SVM. By Friday we'll have covered 90% of the classical ML toolkit.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#LogisticRegression"],
        image: { template: "quote", headline: "Probability is the model. Threshold is the choice.", subhead: "Don't ship 0.5 by default.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 39 */
  {
    day: 39, theme: "Decision trees — the interpretable workhorse", pillar: "ai-ml",
    posts: [
      { id: "d39-p1", day: 39, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "A decision tree is a flowchart you trained",
        copy: "📅 Day 39. Decision trees are the most interpretable model in ML — and they're also the building blocks of random forests and gradient boosting, which dominate tabular data.\n\n🌳 The model — a flowchart. Each internal node tests one feature against a threshold ('age > 35?'). Branches lead to subtrees based on the answer. Each leaf has a prediction (a class for classification; a number for regression).\n\n🎯 Training — pick the split (feature + threshold) that reduces 'impurity' the most. Recurse on each child. Stop when the tree is deep enough or splits don't help. Greedy, top-down. O(n × d × log n) or so.\n\n📐 Impurity for classification — Gini or entropy. Both measure how mixed the classes are at a node. Pure node (all one class) → impurity 0. Mixed node (50/50) → impurity max. The split that maximises 'parent impurity minus weighted child impurities' is chosen.\n\n📐 Impurity for regression — mean squared error. The split that minimises sum-of-squared-residuals across the children.\n\n🎯 Inference — start at the root, follow branches based on the input's features, return the leaf's prediction. O(depth) time. For balanced trees, that's O(log n).\n\n💎 Why people love decision trees:\n\n→ Interpretable. You can literally print the tree and read it. Every prediction has a traceable path.\n\n→ No scaling needed. Trees handle raw features fine. No StandardScaler. Categorical features (after encoding) work natively.\n\n→ Capture non-linear interactions for free. The tree splits on whichever feature reduces impurity most; if interactions matter, splits naturally exploit them.\n\n⚠️ Why alone they overfit — a deep tree memorises training data. That's why we ensemble them (tomorrow).\n\n💡 Master the building block. Then we stack.",
        hashtags: [...CORE, "#DecisionTree"],
        image: { template: "stat", headline: "Tree → flowchart", subhead: "Trained on splits that reduce impurity.", stat: { number: "log n", label: "inference cost on a balanced tree" }, accent: "violet", aiPrompt: "Stat poster with binary-tree glyph, 1:1", canvaBrief: "Violet gradient. Big log n."
        }
      },
      { id: "d39-p2", day: 39, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Gini, entropy, info gain — same idea, different formulas",
        copy: "🧮 If you've read about decision trees, you've seen the Gini-vs-entropy debate. Here's the honest take — they're nearly equivalent and the debate is mostly aesthetic.\n\n📊 Gini impurity. 1 - sum(p_i^2) where p_i is the proportion of class i at the node. Pure node → 0. Maximum mixed → 0.5 for binary. Faster to compute (no log). Sklearn's default for classification trees.\n\n📊 Entropy. -sum(p_i * log(p_i)). From information theory. Pure node → 0. Maximum mixed → 1 for binary (when using log base 2). Slightly slower (logs are expensive). Used in some classical ML literature.\n\n📈 Information gain — the entropy reduction after a split. parent_entropy - sum(weight_i * child_entropy_i). The split with highest info gain is chosen.\n\n🎯 Both Gini and entropy:\n\n→ Are zero when a node is pure.\n→ Maximise when classes are perfectly mixed.\n→ Decrease monotonically as the node becomes purer.\n→ Produce nearly identical trees in practice. Studies show <2% accuracy difference on standard benchmarks.\n\n💡 What MATTERS far more than Gini-vs-entropy:\n\n1️⃣ max_depth. Caps tree depth. The single biggest hyperparameter. Default is None (grow until pure), which overfits.\n\n2️⃣ min_samples_leaf. Minimum rows per leaf. Prevents tiny leaves that memorise training noise.\n\n3️⃣ max_features. How many features to consider per split. Used in random forests for variance reduction.\n\n📋 The reality — pick Gini (sklearn default), tune max_depth and min_samples_leaf, move on. Stop arguing about impurity criteria; you're not going to find the breakthrough there.\n\n🚀 The breakthroughs come from ensembling (tomorrow), not from impurity tweaks.",
        hashtags: [...CORE, "#DecisionTree"],
        image: { template: "list", headline: "Tree splits — measures of 'mixed-ness'",
          bullets: ["Gini — fast, default", "Entropy — info-theoretic", "Info gain = entropy reduction", "Tuning max_depth matters more"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d39-p3", day: 39, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Visualise a decision tree in 4 lines",
        copy: "💻 Sklearn's plot_tree gives you a printable tree diagram. For decision trees up to depth 5 or so, this is incredibly useful — you can literally see the splits.\n\nLook at the snippet. We train a DecisionTreeClassifier with max_depth=4 (so the visualisation isn't too big). Then plot_tree renders the full tree with feature names, class names, and color-filled nodes (color intensity reflects class purity).\n\n🎨 The output shows, for each node:\n\n→ The split — feature and threshold.\n→ Gini (or entropy) value.\n→ Number of samples reaching this node.\n→ Class distribution.\n→ Predicted class.\n\n🔍 You can trace the model's logic for any specific input by walking the tree by hand. 'Age <= 30 → goes left → Income > 50K → goes right → predicts class 1'. That's interpretation in the most concrete sense.\n\n🚀 Use cases for tree visualisation:\n\n→ Explaining the model to non-technical stakeholders. 'Here's exactly what it checks.'\n→ Debugging suspected bugs. If the tree splits on a feature that shouldn't matter, you might have leakage.\n→ Sanity-checking feature engineering. The features at the top of the tree are the most informative.\n\n⚠️ Caveats:\n\n→ Beyond depth 5-6, the visualisation becomes unreadable. Too many nodes.\n→ For very wide datasets, individual splits might use one column out of thousands. Hard to see big picture from one tree.\n→ Random forests and gradient boosting make many trees. You'd visualise one or two for intuition; the ensemble's behaviour isn't from any single tree.\n\n💡 For deeper trees or ensembles, switch to feature_importances_ (a bar chart of feature relevance) or SHAP for per-prediction attribution.",
        hashtags: [...CORE, "#scikitlearn"],
        image: { template: "code", headline: "Train + visualise a tree",
          code: { language: "python", snippet: "from sklearn.tree import DecisionTreeClassifier, plot_tree\nimport matplotlib.pyplot as plt\n\nm = DecisionTreeClassifier(max_depth=4, random_state=42)\nm.fit(X_train, y_train)\n\nplt.figure(figsize=(14, 6))\nplot_tree(m, feature_names=feat_names, class_names=class_names,\n          filled=True, rounded=True, fontsize=10)\nplt.show()" },
          accent: "violet", aiPrompt: "Dark code card with tree diagram glyph, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d39-p4", day: 39, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "max_depth and min_samples_leaf — your overfit defenders",
        copy: "💡 Two hyperparameters tame decision trees. Get them right and you have a useful interpretable model. Get them wrong and you have a wildly overfit tree that memorises training data.\n\n🌳 max_depth. The deepest a tree can grow. Default is None (grow until pure or hits min_samples_leaf). Default = overfit. Always set this explicitly.\n\n📊 Sensible ranges by dataset size:\n→ Small (n < 1k): max_depth 3-5. Larger trees memorise.\n→ Medium (n = 1k-100k): max_depth 5-10.\n→ Large (n > 100k): max_depth 6-12. Past 12, you're usually overfitting unless features are very rich.\n\nFor random forest, deeper trees are fine because the ensemble averages out the overfit. Single trees should stay shallow.\n\n🍃 min_samples_leaf. Minimum number of training samples in any leaf node. The tree won't split a node further if doing so would create a child with fewer than this number of samples.\n\n📊 Sensible ranges:\n→ Default 1 — overfits. Each leaf can be one row.\n→ 5-50 for medium data. Forces the tree to find splits that affect meaningfully-sized groups.\n→ 100+ for very large datasets where you want robust splits.\n\n🎯 The grid search ritual:\n\nfor max_depth in [3, 5, 7, 10, 15]:\n    for min_samples_leaf in [1, 5, 10, 50]:\n        # train + cross-validate\n        ...\n\nTwenty model fits, validation score for each, pick the best.\n\n📈 In sklearn, GridSearchCV does this automatically. Pass the parameter grid; it returns the best combination based on cross-validation score.\n\n💡 The cheapest win in tree-based ML — tuning these two hyperparameters. Don't accept defaults.",
        hashtags: [...CORE, "#Hyperparameters"],
        image: { template: "tip", headline: "Two hyperparams that matter most",
          bullets: ["max_depth — 4 to 10", "min_samples_leaf — 5 to 50", "Default = overfit", "Grid search both"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d39-p5", day: 39, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 39 — trees, framed",
        copy: "📅 End of Day 39.\n\n✅ Recap:\n\n🌳 Tree = flowchart trained on impurity reduction. Inference is O(log n). Interpretable. Handles non-linear interactions for free.\n\n🧮 Gini vs entropy — nearly equivalent. Pick Gini (sklearn default). Move on. Don't get stuck on the choice.\n\n💻 plot_tree visualises trees up to depth 5-6. Useful for explaining models, debugging suspected bugs, sanity-checking features.\n\n🎯 max_depth + min_samples_leaf are the two hyperparameters that matter most. Defaults overfit. Grid search both with cross-validation.\n\n🧠 Reflection — single decision trees are interpretable but not super accurate. They overfit easily and have high variance (small data changes lead to very different trees). Tomorrow we ensemble them, and they become the strongest tabular ML technique most production systems use.\n\n🚀 Tomorrow, Day 40 — random forests + gradient boosting. Bagging vs boosting. LightGBM as the modern default. The 'feature_importances_' diagnostic that catches leakage. Why these models still beat deep learning on tabular data.\n\n💼 Tabular data is most of business ML. Knowing decision trees → ensemble → boosting is the spine of what production ML looks like in fintech, retail, ad tech, healthcare.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#DecisionTree"],
        image: { template: "quote", headline: "A tree is a flowchart you trained.", subhead: "Interpretable. Until you ensemble.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 40 */
  {
    day: 40, theme: "Random forests + gradient boosting — tabular kings", pillar: "ai-ml",
    posts: [
      { id: "d40-p1", day: 40, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Bagging vs boosting in one slide",
        copy: "📅 Day 40. Tree ensembles dominate tabular ML. Two strategies for combining trees, two different ways of thinking about model errors.\n\n🌲 Random Forest (bagging). Train many trees in parallel. Each tree sees a different bootstrap sample of the training data (sampled WITH replacement). Each tree is independently 'wrong' in different ways. Average the predictions. The variance averages out; the bias stays roughly the same.\n\nKey hyperparameters — n_estimators (number of trees, usually 100-500), max_features (features to consider per split, typically sqrt of total). Trees can be deep; the ensemble averaging prevents overfitting.\n\n🚀 Gradient Boosting (XGBoost, LightGBM, CatBoost). Train trees sequentially. Each new tree is trained to correct the residual errors of the ensemble so far. The model 'boosts' itself by progressively fixing what it gets wrong.\n\nKey hyperparameters — n_estimators (usually 100-1000), learning_rate (how much to shrink each tree's contribution, usually 0.01-0.1), max_depth (typically shallower than RF, like 3-8). Trees stay small; the boosting handles complexity.\n\n📊 Bias vs variance:\n\n→ Random Forest reduces variance (high-variance trees averaged → stable ensemble).\n→ Gradient Boosting reduces bias (each tree corrects the previous, fitting more closely to the truth).\n\n🏆 In 2026, gradient boosting (LightGBM or XGBoost) is the strongest baseline for tabular data. It beats deep learning on most structured datasets. Kaggle competitions are won by gradient boosting more than any other technique.\n\n💡 Random forest is more robust out of the box (less hyperparameter tuning needed). Gradient boosting needs more care but ceiling is higher. For production tabular ML — start with LightGBM defaults, tune learning_rate and n_estimators with early stopping.",
        hashtags: [...CORE, "#XGBoost"],
        image: { template: "compare", headline: "Random forest vs gradient boosting",
          compare: { leftLabel: "Random forest", leftItems: ["Trees in parallel", "Bootstrap samples", "Average → reduce variance", "Robust default"], rightLabel: "Gradient boosting", rightItems: ["Trees sequential", "Each fixes prior errors", "Reduce bias", "Strongest tabular baseline"] },
          accent: "violet", aiPrompt: "Compare poster, 1:1", canvaBrief: "Split. Grey vs violet. VS badge."
        }
      },
      { id: "d40-p2", day: 40, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "LightGBM > XGBoost for most things",
        copy: "🌲 In the gradient boosting world, three libraries dominate — LightGBM, XGBoost, CatBoost. All are excellent. In practice, I reach for LightGBM first.\n\n⚡ Why LightGBM:\n\n→ Faster training. Especially on large datasets. Histogram-based splits are 5-20x faster than the exact-split methods.\n\n→ Native categorical feature support. Pass categorical_features=[...] and LightGBM handles them without one-hot encoding. Faster, less memory, often better accuracy.\n\n→ Lower memory footprint. Important when you're working with millions of rows.\n\n→ Cleaner Python API. lgb.LGBMClassifier follows sklearn conventions tightly.\n\n→ Excellent default values. The out-of-box performance is usually within 1-2% of well-tuned XGBoost.\n\n🦾 Where XGBoost still wins:\n\n→ Stability. Older, more battle-tested. Bug rate has been near zero for years.\n\n→ Sklearn-style API consistency. Some teams use it everywhere for uniformity with scikit-learn pipelines.\n\n→ Some specific algorithms it has that LightGBM doesn't (DART, custom objective functions in slightly different shapes).\n\n🐱 Where CatBoost wins:\n\n→ Strongest categorical handling out of the box. Uses target statistics with regularisation.\n\n→ Best defaults of the three for most problems. Slightly slower to train.\n\n→ Built-in handling of overfitting via 'ordered boosting'.\n\n📋 My decision tree:\n\n→ Mostly numerical features → LightGBM.\n→ Lots of categorical features → CatBoost or LightGBM with categorical_features=[].\n→ Already have an XGBoost-based codebase → stick with XGBoost.\n→ Maximum performance ceiling, willing to tune extensively → all three with grid search; pick winner.\n\n💡 Try LightGBM first. Switch only if you hit a specific issue.",
        hashtags: [...CORE, "#LightGBM"],
        image: { template: "list", headline: "Pick a boosting library",
          bullets: ["LightGBM — fast default", "XGBoost — battle-tested", "CatBoost — clean cats", "Try LightGBM first"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d40-p3", day: 40, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "LightGBM with sane defaults",
        copy: "💻 Most LightGBM examples online have 30 hyperparameters set explicitly. You don't need them. Start with this 10-line setup and a single early-stopping callback.\n\nLook at the snippet. We create LGBMClassifier with four parameters:\n\n→ n_estimators=500. The maximum number of trees. With early stopping, the actual number is whatever stops improving.\n\n→ learning_rate=0.05. The shrinkage factor for each tree. Lower = more trees needed but smoother fit. 0.05 is a good middle ground.\n\n→ num_leaves=63. Maximum leaves per tree. LightGBM uses leaf-wise (best-first) growth, so this controls tree complexity. 63 is the default and works well.\n\n→ random_state=42. Reproducibility.\n\n🎯 The fit call passes:\n\n→ Training data.\n\n→ eval_set with validation data. LightGBM scores on this set during training.\n\n→ callbacks=[lgb.early_stopping(20)]. Stop training if validation score doesn't improve for 20 rounds. Picks the best iteration automatically.\n\n📈 Why early stopping is non-negotiable. Without it, you'd train for the full n_estimators (500) and likely overfit. With it, training stops as soon as validation accuracy peaks. Often the actual best iteration is around 100-300, not 500.\n\n🏆 The output AUC tells you how well the model separates classes. Above 0.85 is decent for many real-world problems. Above 0.95 is suspicious — check for leakage.\n\n💡 The 30-line LightGBM examples online often tune subsample, colsample_bytree, lambda_l1, lambda_l2, min_child_samples, etc. Start without these. After you have a baseline working, do hyperparameter tuning (Optuna is great for this). The marginal improvement from extensive tuning is usually 1-3%; the time cost is huge.",
        hashtags: [...CORE, "#LightGBM"],
        image: { template: "code", headline: "LightGBM — minimum viable",
          code: { language: "python", snippet: "import lightgbm as lgb\nfrom sklearn.metrics import roc_auc_score\n\nmodel = lgb.LGBMClassifier(\n    n_estimators=500,\n    learning_rate=0.05,\n    num_leaves=63,\n    random_state=42,\n)\nmodel.fit(\n    X_train, y_train,\n    eval_set=[(X_val, y_val)],\n    callbacks=[lgb.early_stopping(20)],\n)\nprint('AUC:', roc_auc_score(y_val, model.predict_proba(X_val)[:, 1]))" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d40-p4", day: 40, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "feature_importances_ — the cheapest insight",
        copy: "💡 Tonight's pro tip — every tree-based model gives you feature_importances_ for free. Always look at them. They reveal more about your data than the model's accuracy.\n\n📊 What it shows. A score per feature reflecting how much each contributed to reducing impurity across all trees. Higher = more important. Sort and plot the top 20 as a bar chart.\n\n🔍 What you'll learn:\n\n→ Which features actually drive the model. Often surprising. The feature you thought was critical might be ranked 12th; the one you almost dropped might be #1.\n\n→ Suspected leakage. If 'created_at' or 'customer_id' or some derived field is at the top, investigate. Is this feature genuinely predictive or is it secretly the answer?\n\n→ Feature engineering opportunities. If a date field is high but you're using it as a string, parse it into year/month/dayofweek/quarter and likely improve the model.\n\n→ What to drop. Features at the bottom (importance near zero) can be removed for simplicity without much accuracy loss.\n\n⚠️ Caveat — built-in importance can be biased toward high-cardinality features. A categorical with 1000 levels might rank high simply because there are many split opportunities, not because it's truly informative.\n\n📈 The honest version — use SHAP values (shap library). SHAP gives:\n\n→ Per-prediction attribution. 'For this customer, age contributed +0.3 to the prediction.'\n\n→ Global importance that's bias-corrected.\n\n→ Direction of effect (does high feature value increase or decrease the prediction?).\n\nSHAP runs slower than feature_importances_ but the insights are sharper.\n\n💡 The best ML interview answer is — 'I plotted feature importance and noticed that timestamp_created was at the top, which turned out to be a leaky timestamp from the future.' That kind of observation is what separates ML engineers who ship from those who don't.",
        hashtags: [...CORE, "#FeatureImportance"],
        image: { template: "tip", headline: "Plot feature importance every time",
          bullets: ["Sklearn .feature_importances_", "Top 20 bar chart", "SHAP for honest values", "Catches leakage and bugs"],
          accent: "violet", aiPrompt: "Pro tip card with bar chart glyph, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d40-p5", day: 40, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 40 — boosting wins on tabular",
        copy: "📅 End of Day 40. Five-eighths through week six.\n\n✅ Recap:\n\n🌲 Bagging vs boosting in two paragraphs. RF averages parallel trees (variance reduction). GBM trains sequential trees that fix errors (bias reduction).\n\n⚡ LightGBM > XGBoost in most cases. Faster, native categoricals, lower memory, cleaner API. Try LightGBM first.\n\n💻 10-line LightGBM with early stopping. Forget the 30-parameter tutorial. Start simple, tune later.\n\n📊 feature_importances_ — the cheapest insight in tree-based ML. Catches leakage, reveals what matters, suggests feature engineering.\n\n🧠 The honest reality of tabular ML in 2026 — gradient boosting wins. Most production systems handling structured data (fraud, churn, ranking, demand forecasting) use LightGBM or XGBoost. Deep learning (TabNet, FT-Transformer) is catching up but hasn't decisively won. For most tabular problems, GBM is the right default.\n\n🚀 Tomorrow, Day 41 — clustering. K-means, when there are no labels. The elbow method and silhouette score for picking k. Why you ALWAYS scale before clustering. The cases where K-means fails (and what to use instead).\n\n💼 We've covered linear regression, logistic regression, decision trees, ensembles. Tomorrow's clustering is a shift to unsupervised. Day 42 wraps with SVMs and the classical-vs-DL pick-by-data decision tree.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#XGBoost"],
        image: { template: "quote", headline: "On tabular data, boost first.", subhead: "Save deep learning for unstructured.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 41 */
  {
    day: 41, theme: "K-means + clustering — finding structure", pillar: "ai-ml",
    posts: [
      { id: "d41-p1", day: 41, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "K-means in 4 steps",
        copy: "📅 Day 41. K-means is the most-taught clustering algorithm — and rightly so. It's simple, fast, and works well when the data has spherical clusters of similar size.\n\n🎯 The algorithm — four steps that repeat until convergence:\n\n1️⃣ Pick k initial centroids. Random selection of k data points works, but k-means++ (sklearn default) is smarter — it picks initial centroids that are spread out, leading to faster convergence and better results.\n\n2️⃣ Assignment. Each data point is assigned to the nearest centroid (using Euclidean distance). Now you have k clusters, each containing the points closest to its centroid.\n\n3️⃣ Update. Each centroid moves to the mean (centroid) of its assigned points. New centroid position; clusters might shift on the next iteration.\n\n4️⃣ Repeat. Steps 2 and 3 until centroids stop moving (or move very little). Usually 10-50 iterations on real data.\n\n📊 The result — k clusters of points around k centroids. Each point belongs to one cluster.\n\n💡 Where k-means works:\n\n→ Customer segmentation by behaviour metrics.\n→ Image quantisation (compressing image colors to k representative ones).\n→ Document topic clustering (after embedding).\n→ Anomaly detection (points far from any centroid are anomalies).\n\n⚠️ Where k-means fails:\n\n→ Non-spherical clusters. K-means assumes round blobs. For long curved clusters, use DBSCAN.\n→ Very different cluster sizes. K-means tends to make clusters of similar size. For varied sizes, use Gaussian Mixture Models.\n→ Choosing k. The algorithm requires you to specify k upfront. We address this in the midday post.\n→ Outliers. They drag centroids toward them. Pre-clean or use a robust variant.\n\n🚀 K-means is the right default for many clustering tasks. When it doesn't fit, you have alternatives.",
        hashtags: [...CORE, "#KMeans"],
        image: { template: "list", headline: "K-means — 4 steps",
          bullets: ["1. Init centroids", "2. Assign points", "3. Move centroids", "4. Repeat to convergence"],
          accent: "violet", aiPrompt: "Cluster glyph poster, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d41-p2", day: 41, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Choosing k — elbow vs silhouette",
        copy: "🤔 K-means' biggest weakness — you have to pick k upfront. Pick wrong and the clusters are meaningless. Two methods help.\n\n📈 Method 1 — Elbow. Plot inertia (within-cluster sum of squared distances) for k = 2, 3, ..., 15. Inertia decreases as k grows (more clusters → tighter fits). Look for the 'elbow' — the point where adding more k stops giving meaningful improvement.\n\nVisually, the curve drops steeply, then flattens. The elbow is where the steep-to-flat transition happens. That k is the answer.\n\n⚠️ Caveats with elbow:\n→ The 'elbow' is sometimes ambiguous. Curves don't always have a clean bend.\n→ Subjective. Different people pick different elbows from the same plot.\n→ Best for showing 'k=10 is overkill, k=4 is enough'. Less good for distinguishing k=4 from k=5.\n\n📊 Method 2 — Silhouette score. For each point, measure (b - a) / max(a, b) where a is mean distance to its own cluster and b is mean distance to the nearest OTHER cluster. Range: -1 to 1.\n\n→ +1 means the point fits its cluster well and is far from other clusters.\n→ 0 means the point is on the boundary between clusters.\n→ Negative means the point might be in the wrong cluster.\n\nFor each k, compute the mean silhouette across all points. Pick the k that maximises mean silhouette.\n\n🏆 Silhouette is more principled than elbow. The output is a single number, comparable across k values, with a clear interpretation.\n\n📋 In practice — run both. If they agree, you have your k. If they disagree, your data probably doesn't have clean clusters, and the 'best' k is somewhat arbitrary. Use domain knowledge as the tiebreaker.\n\n💡 Don't trust k blindly. Visualise the clusters (PCA or t-SNE for 2D projection). If they look meaningful, ship. If they look random, the data may not cluster at all — k-means will give you SOMETHING regardless.",
        hashtags: [...CORE, "#Clustering"],
        image: { template: "compare", headline: "Picking k — elbow vs silhouette",
          compare: { leftLabel: "Elbow", leftItems: ["Plot inertia", "Look for bend", "Subjective", "Quick visual"], rightLabel: "Silhouette", rightItems: ["Measure similarity ratio", "Range -1 to 1", "Pick max", "More principled"] },
          accent: "violet", aiPrompt: "Compare poster, 1:1", canvaBrief: "Split. Grey vs violet. VS badge."
        }
      },
      { id: "d41-p3", day: 41, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "K-means + silhouette in 12 lines",
        copy: "💻 Twelve lines to find the best k for your dataset. Loop k from 2 to 10, fit k-means, compute silhouette, track the best.\n\nLook at the snippet. We initialise best_k = 2 and best_s = -1 (silhouette can be negative; -1 is the lower bound).\n\nFor each k from 2 to 10, we create a KMeans model with n_init=10 (run k-means 10 times with different initial centroids and pick the best result; protects against bad random initialisations). Fit and predict labels. Compute silhouette_score on (X, labels).\n\nIf silhouette beats current best, update.\n\nPrint the silhouette per k as you go. Useful for seeing the curve, not just the winner.\n\n📊 Interpreting the output:\n\n→ Silhouette > 0.5 — strong, well-separated clusters.\n→ Silhouette 0.25-0.5 — reasonable structure but some overlap.\n→ Silhouette < 0.25 — weak structure, clusters are murky.\n→ Silhouette near zero or negative — the data probably doesn't cluster at all. Don't fool yourself.\n\n🎯 What to do with the best k:\n\n→ Refit KMeans with that k on the full dataset.\n→ Inspect the clusters — what makes each one distinct? Look at centroid coordinates, examine sample points.\n→ Use cluster labels as features for downstream models, or as segments for analysis.\n\n⚠️ The most common mistake — running this without scaling first. If features are on different scales (income in dollars, age in years), the clustering becomes dominated by the larger-scale feature. Always StandardScaler.fit_transform(X) before k-means. We cover this in tonight's tip.\n\n🚀 12 lines. Real cluster discovery. Add scaling for production-grade results.",
        hashtags: [...CORE, "#scikitlearn"],
        image: { template: "code", headline: "K-means + silhouette",
          code: { language: "python", snippet: "from sklearn.cluster import KMeans\nfrom sklearn.metrics import silhouette_score\n\nbest_k, best_s = 2, -1\nfor k in range(2, 11):\n    km = KMeans(n_clusters=k, random_state=42, n_init=10)\n    labels = km.fit_predict(X)\n    s = silhouette_score(X, labels)\n    if s > best_s:\n        best_k, best_s = k, s\n    print(f'k={k}: silhouette={s:.3f}')\n\nprint(f'best k = {best_k}')" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d41-p4", day: 41, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Always StandardScaler before clustering",
        copy: "💡 The most common cluster bug — features on different scales.\n\n🚨 The setup. You have a dataset with two features:\n\n→ income — values in [10000, 200000]\n→ age — values in [18, 80]\n\nYou run k-means. The clusters look weird. They're stratified entirely by income, ignoring age.\n\n🤔 Why? Euclidean distance. The distance between two points is sqrt(sum of squared feature differences). When income's scale is ~1000x larger than age's scale, income's squared differences dominate. Age contributes essentially nothing to distance. The clusters form along income, period.\n\n✅ The fix — StandardScaler. Scales each feature to mean=0, std=1. Now both features contribute equally to distance.\n\nfrom sklearn.preprocessing import StandardScaler\n\nX_scaled = StandardScaler().fit_transform(X)\nkmeans = KMeans(n_clusters=k).fit(X_scaled)\n\n📊 What changes — every feature lives in roughly the same range. Distances respect all features equally. Clusters reflect actual structure.\n\n🎯 When to scale (the same rule applies):\n\n→ KMeans, hierarchical clustering, DBSCAN — yes, all distance-based.\n→ PCA, t-SNE, UMAP — yes, distance-based.\n→ k-Nearest Neighbours — yes, classic example.\n→ Linear/logistic regression with regularisation (Ridge, Lasso) — yes, regularisation is sensitive to scale.\n→ Neural networks — yes (or at least normalize within the network).\n\n📋 When NOT to scale:\n\n→ Tree-based models (decision trees, random forests, gradient boosting) — no. They split on threshold values, which are scale-invariant.\n\n💡 Default — when in doubt, scale. The cost is one line; the savings are 'why are my clusters terrible' debugging sessions.\n\n⚠️ The variant — for clusters with outliers, RobustScaler is better than StandardScaler. Uses median and IQR instead of mean and std.",
        hashtags: [...CORE, "#FeatureScaling"],
        image: { template: "tip", headline: "Standardise before any distance algo",
          bullets: ["StandardScaler.fit_transform", "Apply before KMeans, PCA, kNN", "Or MinMaxScaler", "Different scales = wrong clusters"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d41-p5", day: 41, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 41 — clustering, framed",
        copy: "📅 End of Day 41.\n\n✅ Recap:\n\n🎯 K-means in 4 steps — init, assign, update, repeat. Spherical clusters of similar size. Fails on non-spherical, varied-size, or no-structure data.\n\n📊 Picking k — elbow (visual) or silhouette (principled). Run both; if they disagree, your data may not cluster cleanly.\n\n💻 12-line silhouette loop to find the best k. n_init=10 for robust initialisation.\n\n📐 StandardScaler before any distance algorithm. Mandatory for k-means, PCA, k-NN. Saves you the 'why are clusters dominated by one feature' bug.\n\n🧠 Reflection — clustering is harder than supervised learning because there's no ground truth. You can always cluster; the question is whether the clusters mean anything. Visualise (PCA + scatter), inspect cluster centroids, check business interpretability.\n\n🚀 Tomorrow, Day 42 — SVMs and the wrap of week 6. Why classical ML still wins on tabular data even in the age of LLMs. The classical-vs-DL decision tree by data type.\n\n💼 Six weeks done after tomorrow. Foundations + Python + DSA + data + classical ML covered. Then we go into deep learning, transformers, RAG, agents, automation, career. The remaining seven weeks are the AI-modern stack.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Clustering"],
        image: { template: "quote", headline: "K-means finds spheres.", subhead: "If your data isn't spherical, switch.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 42 */
  {
    day: 42, theme: "SVMs + week 6 wrap", pillar: "ai-ml",
    posts: [
      { id: "d42-p1", day: 42, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "SVMs — find the widest margin",
        copy: "📅 Day 42. Last day of week six.\n\n📐 Support Vector Machines were the dominant ML algorithm of the 2000s. They've lost ground to gradient boosting on tabular and to deep learning on unstructured data. Still worth understanding — the margin idea shows up in modern contrastive learning.\n\n🎯 The core idea — find the hyperplane that separates two classes with the largest possible 'margin' (gap between classes). The points closest to this hyperplane are 'support vectors' (hence the name). The hyperplane is positioned to maximise its distance from these support vectors.\n\n📊 Why max-margin matters. A separating hyperplane that's right at the boundary of one class has zero margin — small perturbations in test data cross it, leading to wrong predictions. A hyperplane that's centered between classes has high margin — robust to perturbations, generalises better.\n\n🧮 Mathematical guarantee. Statistical learning theory provides bounds on test error based on margin. Larger margin → tighter bound → better generalisation. This was a big deal in the 2000s before neural networks empirically beat the bounds.\n\n🌀 Kernels. SVMs can implicitly map features into much higher-dimensional space without computing the mapping explicitly. RBF (Gaussian) kernel handles non-linear boundaries. Polynomial kernel captures polynomial relationships. The 'kernel trick' was groundbreaking — non-linearity at modest computational cost.\n\n⚠️ Why SVMs lost ground:\n\n→ Doesn't scale to huge datasets. Training is O(n²) or worse.\n→ Tabular data is owned by gradient boosting (smaller, faster, often more accurate).\n→ Unstructured data is owned by deep learning.\n→ Hyperparameter tuning is harder than for tree models.\n\n💡 Where SVMs still shine — small datasets (a few hundred samples) where you need a strong baseline. Text classification with TF-IDF features used to be SVM territory before transformers. Some niche cases in finance and biology.\n\n🚀 Worth knowing for the principles. Margin, kernels, support vectors — all concepts you'll see in modern self-supervised learning.",
        hashtags: [...CORE, "#SVM"],
        image: { template: "stat", headline: "max margin", subhead: "The original 'find the widest gap'", stat: { number: "max", label: "margin — the SVM goal" }, accent: "violet", aiPrompt: "Stat poster with hyperplane glyph, 1:1", canvaBrief: "Violet gradient. Big max."
        }
      },
      { id: "d42-p2", day: 42, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Classical ML vs deep learning — when to pick what",
        copy: "🤔 The eternal question — should I use classical ML or deep learning? My decision tree based on data type and size.\n\n📊 Tabular data, small (<10M rows):\n\n→ LightGBM / XGBoost. Often beats neural networks. Fewer hyperparameters to tune. Faster to train. More interpretable. Production-friendly.\n\n📈 Tabular data, large (>100M rows):\n\n→ Still gradient boosting in most cases. Modern variants handle large data well.\n→ Consider TabNet, FT-Transformer, SAINT for very large tabular. They sometimes win when you have the compute and data.\n\n🖼️ Images, audio, video:\n\n→ Deep learning, no contest. CNNs (ResNet, EfficientNet) for images. Vision Transformers (ViT) for the highest accuracy on big data. Wav2Vec for audio.\n\n📝 Text:\n\n→ Small data (< 10k labeled): TF-IDF + classical model often wins. Less overfitting risk.\n→ Medium data: BERT-style encoders or sentence-transformers for embedding + classical model.\n→ Large data: Fine-tune a transformer or use a pretrained one with a small classification head.\n\n📅 Time series:\n\n→ Start with classical. ARIMA, Prophet (Facebook's), exponential smoothing. Strong baselines.\n→ Upgrade to neural (LSTM, Transformer-based) only if classical doesn't meet requirements and you have lots of training data.\n\n🌐 Graph data:\n\n→ Neural (Graph Neural Networks) for prediction tasks on graphs.\n→ Classical algorithms (PageRank, community detection) for non-prediction tasks.\n\n💡 The meta-rule — don't reach for deep learning by reflex. Many problems don't have enough data for neural networks to outperform simpler models. Many production teams underestimate the maintenance cost of DL pipelines.\n\n🎯 Default decision tree:\n\n1️⃣ Try a baseline (linear, logistic).\n2️⃣ Try gradient boosting.\n3️⃣ If you need more, then deep learning.\n\nMost projects stop at step 2 and ship. That's fine.",
        hashtags: [...CORE, "#MLEngineering"],
        image: { template: "list", headline: "Classical ML vs DL — pick by data",
          bullets: ["Tabular small → LightGBM", "Tabular huge → still LightGBM", "Images / audio → DL", "Text → mix, depends on size", "Time series → classical first"],
          accent: "violet", aiPrompt: "Decision-flow infographic, 1:1", canvaBrief: "White grid. 5 rows."
        }
      },
      { id: "d42-p3", day: 42, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Pipeline — wrap everything in one object",
        copy: "💻 Sklearn Pipelines wrap preprocessing + model into a single fit/predict object. Train it; ship it; never worry about preprocessing drift between training and production.\n\nLook at the snippet. Three steps:\n\n1️⃣ SimpleImputer(strategy='median') — fills missing values with the median of each column. The fitted imputer remembers which median to use for each column.\n\n2️⃣ StandardScaler() — scales features to mean=0, std=1. The fitted scaler remembers each column's mean and std.\n\n3️⃣ LogisticRegression(max_iter=2000) — the actual model.\n\nWrap all three in a Pipeline. Now pipe.fit(X_train, y_train) trains the imputer, then the scaler, then the model — in order, automatically. pipe.predict(X_new) does the same chain at inference: impute, scale, predict.\n\n🎯 Why this matters in production:\n\n→ Single object to serialise. joblib.dump(pipe, 'model.pkl') saves the entire chain. No 'where's my scaler' debugging.\n\n→ No preprocessing drift. Training and inference use the SAME scaler with the SAME mean/std. Common bug — train with one scaler, infer with a different one (or none) — eliminated.\n\n→ Cross-validation done right. Without a pipeline, you might fit the scaler on the full training data, then split for CV — leaking data from validation into training. With a pipeline, the scaler is refit on each fold, no leakage.\n\n→ Easier to swap models. Replace LogisticRegression with RandomForestClassifier; same pipeline contract.\n\n📋 ColumnTransformer extends this for heterogeneous data — different preprocessing for different columns. One-hot encode categoricals, scale numerics, all in one Pipeline. Clean and reproducible.\n\n💡 If your sklearn code DOESN'T use Pipeline, refactor. The 5-minute investment prevents a class of production bugs.",
        hashtags: [...CORE, "#scikitlearn"],
        image: { template: "code", headline: "Pipeline = preprocessing + model",
          code: { language: "python", snippet: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.impute import SimpleImputer\nfrom sklearn.linear_model import LogisticRegression\n\npipe = Pipeline([\n    ('impute', SimpleImputer(strategy='median')),\n    ('scale',  StandardScaler()),\n    ('clf',    LogisticRegression(max_iter=2000)),\n])\npipe.fit(X_train, y_train)\nprint(pipe.score(X_val, y_val))" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d42-p4", day: 42, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Save the pipeline with joblib, not pickle",
        copy: "💡 Tonight's pro tip — when persisting sklearn pipelines, use joblib instead of pickle.\n\n📦 Both work for sklearn objects. Both serialise the entire pipeline including fitted estimators. The difference is in efficiency and edge cases.\n\n⚡ joblib is faster for objects with large NumPy arrays (which most ML pipelines have — fitted weights, transformer parameters, etc). It uses memory-mapped storage for arrays. The size of the saved file is similar; the load time is dramatically better for big models.\n\n🛠 Recommended:\n\nimport joblib\n\njoblib.dump(pipeline, 'model.pkl')\npipe = joblib.load('model.pkl')\n\n⚠️ Important caveats for production:\n\n1️⃣ Pin sklearn version. A pipeline trained on sklearn 1.4 may not load on sklearn 1.6. Some transformers change internal structure between versions. Pin sklearn version in requirements.txt and document it alongside the saved model.\n\n2️⃣ Pin Python version. Pickle/joblib are sensitive to Python version differences. Train on Python 3.11, deploy on Python 3.11.\n\n3️⃣ Pin numpy and other dependencies. Same logic.\n\n4️⃣ Save metadata next to the model. A small JSON with the version info, training date, evaluation metrics, training data hash. Future-you will thank present-you.\n\n5️⃣ Test the load before shipping. Save the model. Then load it from a fresh process and run inference on a known input. Verify the output matches what training produced. Catches any subtle serialisation issue immediately.\n\n📋 For long-term storage (>1 year), consider exporting to a portable format like ONNX. Pickled models are fragile across major version jumps; ONNX is portable across runtimes.\n\n💡 The pickle-vs-joblib choice is small. The version-pinning discipline is huge. Don't skip step 5 (test load).",
        hashtags: [...CORE, "#MLOps"],
        image: { template: "tip", headline: "Persist with joblib + pinned versions",
          bullets: ["joblib.dump > pickle", "Pin sklearn / Python", "Save metadata too", "Re-test load before shipping"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d42-p5", day: 42, postNumber: 5, slot: "night", type: "recap", pillar: "career",
        title: "Week 6 done — classical ML mastered",
        copy: "📅 End of Day 42. End of week 6. We're 47% through the sprint.\n\n✅ Week 6 in seven topics:\n\n🎯 ML problem framing — three boxes (supervised, unsupervised, RL), the 6-step ML loop, three-way splits, picking the metric BEFORE training.\n\n📈 Linear regression — y = Xw + b, MSE/RMSE/MAE choice, sklearn vs closed-form NumPy, always beat the dumb baseline.\n\n🎯 Logistic regression — linear regression + sigmoid, class imbalance fixes, full diagnostics (classification_report, confusion_matrix, AUC), threshold ≠ 0.5.\n\n🌳 Decision trees — flowchart trained on impurity, Gini = entropy, plot_tree for visualisation, max_depth + min_samples_leaf as the key hyperparameters.\n\n🚀 Ensembles — bagging vs boosting, LightGBM > XGBoost in most cases, 10-line LightGBM with early stopping, feature_importances_ as the cheapest insight.\n\n🎯 K-means clustering — 4-step algorithm, elbow + silhouette for picking k, StandardScaler before any distance-based algo.\n\n📐 SVMs + classical-vs-DL decision — margin idea still relevant, gradient boosting wins on tabular, deep learning wins on unstructured. Pipeline + joblib for production.\n\n🧠 The big takeaway from week 6 — don't reach for deep learning by reflex. Classical ML solves most production problems faster, cheaper, and with less maintenance. Save deep learning for when you genuinely need it (images, text, audio at scale).\n\n🚀 Next week — deep learning fundamentals. Neurons, backprop, PyTorch basics, CNNs, RNNs, regularisation, training tricks. The bridge from classical ML to modern AI.\n\n💼 47% done. The ML/AI core stack starts tomorrow.\n\n👋 See you in week 7.",
        hashtags: [...CORE, "#90DaysOfAI"],
        image: { template: "quote", headline: "6 weeks down. 7 to go.", subhead: "Next: deep learning, from a single neuron to backprop.", accent: "violet", aiPrompt: "Pastel violet quote with 42/90 progress, 1:1", canvaBrief: "Pastel violet quote with 42/90 violet bar." }
      },
    ]
  },
];
