import type { DayPlan } from "../types";

const CORE = ["#AI", "#MachineLearning", "#Python", "#100DaysOfCode", "#BuildInPublic"];

export const week01: DayPlan[] = [
  /* DAY 1 */
  {
    day: 1,
    theme: "Why I'm starting 90 days of AI/ML in public",
    pillar: "career",
    posts: [
      {
        id: "d1-p1", day: 1, postNumber: 1, slot: "morning", type: "concept", pillar: "career",
        title: "Day 1 of 90 — building AI/ML in public",
        copy: "Day 1.\n\nFor the next 90 days, I'm doing something I've put off for years — a fully public AI/ML learning sprint. Five posts every single day. By the time this ends, there will be 450 posts on this page, and a public GitHub repo with the code behind every one of them.\n\nWhy now? Because I've watched too many private learning attempts (mine included) burn out around week three. The pattern is always the same — notebook open, brain half-engaged, no skin in the game. Nothing on the line, nothing actually learned.\n\nThis time I'm putting it on the line. Every concept gets a post within twenty-four hours. Every mistake stays on the timeline. Every snippet ships to GitHub the same day.\n\nThe plan covers seven pillars — AI/ML, Python, RAG, DSA, Automation, Agents, and the honest career stuff (portfolios, interviews, open source) that nobody talks about until it's too late.\n\nFive posts a day sounds like a lot. The structure makes it work — concept in the morning, deep-dive at midday, code in the afternoon, a practical tip in the evening, a recap at night. By bedtime, the day's topic is muscle memory.\n\nIf you've been meaning to start your own sprint, follow along. We do this together.\n\n90 days. 450 posts. Let's go.\n\n— Saurav\nGitHub: github.com/SauravDnj\nLinkedIn: linkedin.com/in/sauravdnj",
        hashtags: [...CORE, "#AICareer", "#LearnInPublic"],
        image: {
          template: "stat",
          headline: "Day 1 / 90",
          subhead: "AI/ML · Python · RAG · DSA · Automation · Agents",
          stat: { number: "90", label: "days of building in public" },
          accent: "violet",
          aiPrompt: "Editorial poster, deep purple-to-cyan gradient, large neon numeral 90 centered, subtitle 'days of building in public', futuristic minimal, subtle circuit-board lines, tiny Saurav Danej wordmark top-left, square 1:1, premium tech aesthetic, suitable for LinkedIn",
          canvaBrief: "1080x1080. Background: #150538 to #5a23ee diagonal gradient with thin cyan circuit-line overlay at 18% opacity. Center large 90 in Plus Jakarta ExtraBold 320pt, white-to-cyan gradient text. Below in Inter Medium 36pt: 'days of building in public'. Top-left: small S badge + Saurav Danej. Bottom: linkedin.com/in/sauravdnj caption.",
        },
      },
      {
        id: "d1-p2", day: 1, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "What 'AI', 'ML' and 'DL' actually mean",
        copy: "Three letters everyone in tech throws around — AI, ML, DL — and almost nobody uses them correctly.\n\nLet me untangle it the way I wish someone had untangled it for me when I started.\n\nAI is the broad goal. Make a machine do something that looks intelligent. The 1997 Deep Blue chess engine is AI. So is GPT-4. So is the rule-based bot inside your favourite video game. AI is not a single technique — it's a *target*.\n\nML is one approach to AI. Instead of writing the rules by hand, you let an algorithm learn the patterns from data. A spam classifier trained on a million emails is ML. A handcrafted regex spam filter is AI but not ML.\n\nDL is a subset of ML. Deep neural networks — many layers, lots of parameters, trained on GPUs. Every modern LLM (GPT, Claude, Llama, Gemini) is deep learning of the transformer family.\n\nSo: every DL is ML, every ML is AI, but the reverse isn't true. Three nested circles.\n\nWhy this matters in conversation: when someone says 'we're using AI', they could mean a giant Llama model OR a five-line if-else. Always ask which layer they mean. The answer changes the cost, the data needs, the failure modes — everything.\n\nNext time someone tells you their startup 'uses AI', smile and ask: 'AI, ML, or DL?' You'll learn more in 30 seconds than from their entire pitch deck.",
        hashtags: [...CORE, "#DeepLearning", "#AIBasics"],
        image: {
          template: "list",
          headline: "AI vs ML vs DL — pick the right word",
          bullets: [
            "AI — make machines look intelligent",
            "ML — learn patterns from data, not rules",
            "DL — ML using deep neural networks",
            "Each is a subset of the previous",
          ],
          accent: "violet",
          aiPrompt: "Clean infographic, three concentric labelled rings (AI outer, ML middle, DL core), violet-cyan palette on white, sharp sans-serif typography, technical illustration style, 1:1 square, LinkedIn carousel, premium",
          canvaBrief: "1080x1080 white background. Centered concentric rings: outer AI #c8baff fill, middle Machine Learning #8b6bff, core Deep Learning #5a23ee. Headline top: 'AI vs ML vs DL' Plus Jakarta 56pt. Each ring labelled inside with Inter Bold 30pt white. Bottom byline.",
        },
      },
      {
        id: "d1-p3", day: 1, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "Your first ML model in 6 lines",
        copy: "If you've never trained a machine-learning model, today is the day. It's about to take you six lines of Python.\n\nThis is scikit-learn's Iris classifier. Iris is a tiny flower dataset — 150 rows, four numeric measurements, three flower species. It's the 'hello world' of ML, but don't underestimate it. The shape of these six lines is the shape of every ML pipeline you'll ever build, including the billion-parameter ones.\n\nLine 1-2: load data and split it into train and test. Never train and evaluate on the same rows. Ever.\n\nLine 3: pick a model. Random Forest is a strong, fast default for tabular data. You don't need to know how it works yet — that comes in week 6.\n\nLine 4: .fit(X_train, y_train) — the model learns patterns from the training data.\n\nLine 5: .score(X_test, y_test) — see how well it does on data it has never seen. On Iris, you'll get ~97% accuracy.\n\nThat's it. Data → split → fit → score. Every billion-dollar AI product starts as a more elaborate version of this loop. The data gets bigger. The models get fancier. The shape doesn't change.\n\nIf you can read these six lines and explain each one, you've already understood 80% of practical ML. The remaining 20% is everything we'll do for the next 89 days — but the spine is right here.\n\nCopy. Run. Watch your first model train. Then come back.",
        hashtags: [...CORE, "#scikitlearn", "#MLBeginners"],
        image: {
          template: "code",
          headline: "Your first ML model — 6 lines",
          subhead: "scikit-learn · Iris classifier",
          code: {
            language: "python",
            snippet: "from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\n\nX, y = load_iris(return_X_y=True)\nXtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2)\nprint(RandomForestClassifier().fit(Xtr, ytr).score(Xte, yte))",
          },
          accent: "violet",
          aiPrompt: "Dark IDE-style code card, deep navy background with violet glow, Python snippet with syntax highlighting, traffic-light window controls top-left, 'python' tag top-right, premium developer aesthetic, 1:1 square, LinkedIn",
          canvaBrief: "1080x1080. Dark gradient #0b0228 to #150538. Top-center title 'Your first ML model'. Below: rounded code window with mac traffic lights, JetBrains Mono 26pt, lines numbered, keywords (from/import/return) in violet. Footer with handles.",
        },
      },
      {
        id: "d1-p4", day: 1, postNumber: 4, slot: "evening", type: "tip", pillar: "career",
        title: "The single best AI/ML learning hack",
        copy: "I've watched a lot of people start learning AI/ML. The ones who stick with it all do the same weird thing — they ship tiny projects WAY before they think they're ready.\n\nThe pattern is brutal in its simplicity. Read about embeddings? That same evening, build a 50-line semantic search over your Notion notes. Read about transformers? Fine-tune a tiny one on your favourite Reddit subreddit. Read about agents? Wire up a 2-tool agent that browses the web and summarises an article.\n\nNotice what's missing — the third tutorial, the fancy GPU, the perfect dataset, the side-project framework. None of it. Just a small messy script that runs.\n\nHere's why this matters more than any course or textbook. Theory teaches you what's *possible*. Tiny projects teach you what you actually *understand*. Those are two completely different things, and the gap between them is where most learners get stuck.\n\nIf you can't ship a 100-line version of an idea, you don't understand it yet. That's not an insult — it's a diagnostic. The 100-line version forces you to confront the parts you skimmed.\n\nMy rule for myself: every concept I read about gets a tiny repo by end of day. The repo can be ugly. It just has to run, demonstrate the idea, and be pushed somewhere I can find it again.\n\nAt the end of 90 days I'll have 90+ tiny repos. Future me will use them as living reference cards — searchable, runnable, faster than any documentation.\n\nFor every hour of theory, spend an hour shipping. That's the hack.",
        hashtags: [...CORE, "#LearningInPublic", "#TinyProjects"],
        image: {
          template: "tip",
          headline: "Ship a tiny version before the next chapter",
          subhead: "100 lines beats 100 pages",
          bullets: [
            "Embeddings → semantic search on your notes",
            "Transformers → tiny fine-tune on a quirky dataset",
            "Agents → 2-tool ReAct loop",
            "RAG → chat with one PDF",
          ],
          accent: "violet",
          aiPrompt: "Modern PRO TIP poster, top half deep purple gradient with star particles, white headline 'Ship a tiny version before the next chapter', floating white card below with 4 checked items in violet, premium tech aesthetic, 1:1, LinkedIn",
          canvaBrief: "1080x1080. Top 360px: gradient #4818c4 to #5a23ee with 20 white twinkle dots. PRO TIP pill top-left. Headline white Jakarta 64pt. Bottom: white card 28px radius, 4 lines with checkmarks. Footer brand.",
        },
      },
      {
        id: "d1-p5", day: 1, postNumber: 5, slot: "night", type: "recap", pillar: "career",
        title: "Day 1 recap — and what's tomorrow",
        copy: "End of Day 1. Five posts shipped, zero shortcuts.\n\nHere's what we covered today, distilled.\n\nMorning, we set the contract — 90 days, five posts a day, all public, GitHub repo at the end. Now you know what you're following along with.\n\nMidday, we untangled AI vs ML vs DL. Three nested circles, not three names for the same thing. Use the right word; the right word changes the conversation.\n\nAfternoon, six lines of scikit-learn trained your first ML classifier. The shape of every pipeline you'll build for the rest of your career is hidden in those six lines — load, split, fit, score.\n\nEvening, the one habit that separates learners who finish from learners who don't — ship a tiny version before reading the next chapter. Theory tells you what's possible. Code tells you what you understand.\n\nA quiet number to end on: I started today with 0 posts and a vague plan. I'll end with 5 posts and a slightly clearer one. The thing about building in public is that the plan sharpens *as* you ship. You can't outline your way into clarity.\n\nTomorrow, Day 2, we set up the cleanest Python environment you'll ever own. uv, ruff, pyproject.toml — three tools, replace about ten old ones, never fight your dev environment again. Boring topic. Massive lifetime payoff.\n\nIf today's posts hit, save the day's URL. The whole 90-day index will eventually live behind a single bookmark.\n\nSee you tomorrow.",
        hashtags: [...CORE, "#90DaysOfAI", "#DailyRecap"],
        image: {
          template: "quote",
          headline: "Day 1, done.",
          subhead: "Tomorrow: a Python setup that won't fight you for 88 more days.",
          accent: "violet",
          aiPrompt: "Soft editorial quote card, pastel violet-to-white gradient, large bold headline 'Day 1, done.', italic subhead beneath, decorative quote glyph in 12% opacity, 1:1 LinkedIn quote card, premium minimal",
          canvaBrief: "1080x1080. Gradient #f3f0ff to #ffffff. Big quote glyph top-left at 12% violet. Centered Jakarta ExtraBold 76pt 'Day 1, done.'. Below: italic Inter 30pt subhead. 120x5 violet bar accent. Brand pill top-left, pillar tag top-right, footer.",
        },
      },
    ],
  },

  /* DAY 2 */
  {
    day: 2,
    theme: "Set up Python so it never fights you again",
    pillar: "python",
    posts: [
      {
        id: "d2-p1", day: 2, postNumber: 1, slot: "morning", type: "concept", pillar: "python",
        title: "Why your Python setup keeps breaking",
        copy: "Every beginner Python question I've ever answered eventually traces back to one root cause — the environment is broken.\n\nYou install one library, it complains about another. You upgrade pip, half your venv evaporates. Your laptop now has python2, python3.9, python3.11, anaconda-python, brew-python, and the system one — all fighting for PATH supremacy. You spend more time googling 'ModuleNotFoundError' than actually writing code.\n\nThe fix isn't more tutorials. It's better tools. Most Python tutorials are stuck in 2018 — pip + venv + setup.py. That stack worked. It also generated 90% of the pain.\n\nIn 2026, the cleanest stack is three tools, set up once.\n\nuv — a Rust-written installer + venv manager from Astral. Replaces pip, virtualenv, pyenv, and pip-tools in one binary. Roughly 50-100x faster, with proper lockfiles by default.\n\nruff — also from Astral. Lints AND formats your code. Replaces black, flake8, isort, and most of pylint. Same speed story — Rust under the hood, faster than anything Python-based.\n\npyproject.toml — one config file. Modern PEP-517 standard. Every modern tool reads it. Goodbye to setup.py + setup.cfg + tox.ini + .flake8 + .pre-commit-config.yaml soup.\n\nThe upfront cost of switching is one afternoon. The downstream payoff is — and I mean this literally — the rest of your Python career without environment fights.\n\nWe set this up tomorrow's section. Today, just believe me when I say the old way is what's been breaking you.",
        hashtags: [...CORE, "#PythonTips", "#uv"],
        image: {
          template: "stat",
          headline: "0 setup fights",
          subhead: "uv + ruff + pyproject.toml",
          stat: { number: "0", label: "Python environment fights, going forward" },
          accent: "violet",
          aiPrompt: "Bold stat poster, deep purple-to-cyan gradient, giant 0 numeral, subtitle 'Python environment fights, going forward', minimal, snake-coil glyph faded behind, 1:1 LinkedIn square, premium",
          canvaBrief: "1080x1080. Gradient #150538 to #5a23ee to #22d3ee. Centered 0 Jakarta 320pt white-to-cyan gradient text. Subhead 36pt brandSoft. Faded snake icon at 8% opacity behind. Brand pill, Python pillar tag.",
        },
      },
      {
        id: "d2-p2", day: 2, postNumber: 2, slot: "midday", type: "deepdive", pillar: "python",
        title: "uv — the Python installer that's actually fast",
        copy: "Let's talk about uv specifically, because it's the single biggest quality-of-life upgrade Python has had in a decade.\n\nuv is what pip should have been. Written in Rust by Astral (same team that built ruff), it's a drop-in replacement for pip + virtualenv + pyenv + pip-tools — all of them, in one self-contained binary.\n\nThe daily-life impact is hard to oversell.\n\nuv venv creates a fresh virtual environment in about 50 milliseconds. The old stack took 5+ seconds. You stop avoiding venvs because they're now free.\n\nuv pip install runs 10 to 100x faster than plain pip. Installing PyTorch + Transformers + a few utilities used to take 90 seconds; now it's under 10. On bigger projects with hundreds of dependencies, the difference is more like 5 minutes versus 30.\n\nuv python install 3.12 installs the Python interpreter itself. No more pyenv, no more 'which python on this machine'. uv manages the runtime.\n\nLockfiles by default. Reproducible installs across teammates and CI without a separate tool like pip-tools.\n\nIf you've been waiting for 'Python with cargo's UX' — that's exactly what this is. Try it for one week on one project. Just one. By day three you won't go back. I switched in March 2025, and the only times I've used pip since are when working in someone else's old repo.\n\nInstall: curl -LsSf https://astral.sh/uv/install.sh | sh (or pipx install uv on Windows). Tomorrow we use it for real.",
        hashtags: [...CORE, "#uv", "#PythonTooling"],
        image: {
          template: "list",
          headline: "uv replaces all of these",
          bullets: ["pip", "virtualenv", "pyenv", "pip-tools", "poetry (mostly)"],
          accent: "violet",
          aiPrompt: "Premium tool-replacement infographic, white background with violet grid, headline 'uv replaces all of these', 5 numbered cards with old-tool names struck through, premium tech aesthetic, 1:1, LinkedIn",
          canvaBrief: "1080x1080. White with 4% violet dot grid. Headline top in Jakarta 60pt. 5 numbered rows with old tool names — strikethrough rose color. Right edge: small uv logo in violet circle. Footer brand line.",
        },
      },
      {
        id: "d2-p3", day: 2, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "Project setup in 4 commands",
        copy: "From zero to a working AI/ML project in four commands. Run them once at the start of every new repo and never think about your environment again.\n\nFirst command, uv init creates a project skeleton — pyproject.toml, README, .python-version, src layout if you want it. It's like running 'cargo init' for Python.\n\nSecond, cd into the new directory. (Yes, this counts as a command. I'm being strict.)\n\nThird, uv add adds dependencies. uv reads pyproject.toml, resolves the dependency graph, installs everything into a hidden .venv, and writes a lockfile so your teammates get the exact same versions. Add as many libraries as you want — it batches them and runs in seconds.\n\nFourth, uv run executes a Python script (or any command) inside the project's environment. No 'source .venv/bin/activate' dance. uv handles activation transparently.\n\nThat's the whole loop — init, cd, add, run. The .venv directory and uv.lock file go into .gitignore (well, .venv does; you commit uv.lock so installs are reproducible).\n\nUpgrade dependencies later? uv lock --upgrade. Want to remove one? uv remove. Want a fresh environment from scratch? Delete .venv and rerun uv sync — it rebuilds in seconds from the lockfile.\n\nFour commands. Once. Now you can stop thinking about Python plumbing and start writing the code that actually matters. We use this exact setup in every code post for the rest of the 90 days.",
        hashtags: [...CORE, "#DevSetup", "#uv"],
        image: {
          template: "code",
          headline: "Project setup in 4 commands",
          subhead: "uv + ruff + pyproject.toml",
          code: {
            language: "bash",
            snippet: "uv init my-ai-project\ncd my-ai-project\nuv add numpy pandas scikit-learn\nuv run python -c \"import sklearn; print(sklearn.__version__)\"",
          },
          accent: "violet",
          aiPrompt: "Dark terminal card, mac traffic lights, bash prompt syntax highlighting in violet/cyan, premium developer poster, 1:1 LinkedIn",
          canvaBrief: "1080x1080. Dark gradient. Code window with bash prompt. Lines numbered. $ prompt in cyan. uv keyword in violet. Title above, footer below.",
        },
      },
      {
        id: "d2-p4", day: 2, postNumber: 4, slot: "evening", type: "tip", pillar: "python",
        title: "One pyproject.toml beats five config files",
        copy: "If you've worked on legacy Python projects, you've seen this graveyard — setup.py, setup.cfg, .flake8, .black, tox.ini, MANIFEST.in. Each one a snowflake config for some tool, each one slightly out of sync with the others, each one occasionally undone by an autoformatter that didn't read the right config.\n\nKill all of them. pyproject.toml replaces every single one.\n\nPEP-517 made pyproject.toml the canonical Python config. PEP-518, 621, and a handful of others extended it. By 2026, every modern Python tool reads it — uv, ruff, pytest, mypy, hatch, build, even some legacy holdouts via plugins.\n\nMy minimum file is twelve lines. It declares the project name, Python version, dependencies, and tool configurations under [tool.<name>] sections. That's the entire build/config story.\n\n[project] holds metadata and dependencies — name, version, python-requires, dependencies list.\n[tool.ruff] holds your lint and format rules — line length, which rules to enable, which to ignore.\n[tool.pytest.ini_options] holds your test configuration.\n[tool.mypy] holds your type-check configuration.\n\nOne file. One source of truth. When you onboard a new dev, they read pyproject.toml and they know everything. When you change a rule, you change it in one place.\n\nIf a tool you use *still* wants its own dotfile, look for a [tool.<name>] section first — there almost always is one in modern releases. If there isn't, file an issue. The migration is one-way; the world is moving.\n\nOne file beats five. Always.",
        hashtags: [...CORE, "#CleanCode", "#PythonTooling"],
        image: {
          template: "tip",
          headline: "One pyproject.toml beats five config files",
          subhead: "PEP-517. The single source of truth.",
          bullets: [
            "[project] — deps + metadata",
            "[tool.ruff] — lint + format",
            "[tool.pytest.ini_options]",
            "[tool.mypy]",
          ],
          accent: "violet",
          aiPrompt: "Pro tip poster on violet gradient with file icons radiating from a central pyproject.toml, premium tech, 1:1 LinkedIn",
          canvaBrief: "Top half violet gradient with PRO TIP pill. Headline 64pt white. Below white card with 4 [tool.*] sections monospace, each with a checkmark. Footer.",
        },
      },
      {
        id: "d2-p5", day: 2, postNumber: 5, slot: "night", type: "recap", pillar: "python",
        title: "Day 2 — your environment will never fight you again",
        copy: "End of Day 2.\n\nIf you only do one practical thing this week, do today's setup. The compounding payoff is enormous. I genuinely believe that the gap between developers who ship and developers who don't often comes down to whether they have to fight their tools every morning.\n\nWhat we set up today, in order.\n\nMorning explained why your Python keeps breaking — too many tools, none of them sharing config. The fix is fewer tools that share more.\n\nMidday introduced uv as that fewer-tools answer. One Rust-written binary that replaces pip + virtualenv + pyenv + pip-tools, runs 10-100x faster, and has proper lockfiles built in.\n\nAfternoon was the four commands — uv init, cd, uv add, uv run. That's the entire create-a-new-project workflow. We'll use it again on Day 7 when we start the GitHub repo and again on Day 78 when we begin the automation week.\n\nEvening was the case for one pyproject.toml over five legacy config files. PEP-517 won. The world is moving.\n\nIf your hands itched to migrate while reading this, that's good. Pick one project this weekend, port it to uv + ruff + pyproject.toml, time how long the install loop takes before and after. The first time you delete .venv and rebuild in 8 seconds instead of 90, you'll know.\n\nTomorrow, Day 3, we go into Python's type system. Variables, strings, numbers, and the part everyone underestimates — type hints. The reason your future self stops cursing your past self.\n\nSee you in the morning.",
        hashtags: [...CORE, "#Python3", "#DailyRecap"],
        image: {
          template: "quote",
          headline: "Tools first. Code second.",
          subhead: "An hour spent on uv saves a week of dependency drama.",
          accent: "violet",
          aiPrompt: "Editorial pastel quote card with snake icon shadow, violet-cyan accent bar, 1:1 LinkedIn",
          canvaBrief: "Soft #f3f0ff to white gradient. Big quote 'Tools first. Code second.' Italic subhead. 120x5 accent bar. Brand pill, pillar tag, footer.",
        },
      },
    ],
  },

  /* DAY 3 */
  {
    day: 3,
    theme: "Python variables & types — the parts that matter",
    pillar: "python",
    posts: [
      {
        id: "d3-p1", day: 3, postNumber: 1, slot: "morning", type: "concept", pillar: "python",
        title: "Python isn't typeless — you just can't see them",
        copy: "Tell a Python beginner that Python has types and they'll usually look at you funny. 'Python is typeless, right? You just write x = 5 and it works.'\n\nThat's the most expensive misconception in the language. Python is dynamically typed, not typeless. There is a massive difference.\n\nEvery value in Python has a type. The integer 5 has type int. The string 'hello' has type str. What's flexible is the *variable*, not the value. The variable is just a label. You can re-point the label at a different value, and the value's type is whatever the new value's type is.\n\nx = 10        # x points at an int\nx = 'ten'     # now x points at a str\nx = [1, 2]    # now x points at a list\n\nThe int 10 didn't 'change type' to a string. The variable just stopped pointing at 10 and started pointing at 'ten'. The values themselves are typed and immutable about it.\n\nWhy this matters in practice. When you see a function in someone else's code, you have no idea what type the variables are. Production bugs love this. You pass a string where the function expected a list, and the error doesn't surface for three function calls — buried under .append() failing on a string.\n\nThe fix isn't to abandon dynamic typing. It's to *annotate* what you mean — type hints (we cover them on Day 13). Hints don't change runtime behaviour. They give you, your IDE, and tools like mypy a way to catch the bugs before the code runs.\n\nDynamic typing isn't 'no types'. It's 'types you can't see unless you write them down'. Write them down.",
        hashtags: [...CORE, "#PythonTypes", "#Python3"],
        image: {
          template: "stat",
          headline: "Variables = labels.\nTypes belong to values.",
          subhead: "The single sentence that fixes most beginner confusion.",
          stat: { number: "1", label: "rule that fixes 90% of variable bugs" },
          accent: "violet",
          aiPrompt: "Concept poster, deep purple background, big 1 numeral, subtitle, abstract label-pointing-to-box illustration, 1:1 LinkedIn premium",
          canvaBrief: "Gradient #150538 to #5a23ee. Big 1 centered. Subhead. Decorative arrow from label tag to box. Brand + pillar pills, footer.",
        },
      },
      {
        id: "d3-p2", day: 3, postNumber: 2, slot: "midday", type: "deepdive", pillar: "python",
        title: "The 7 built-in types you'll touch every day",
        copy: "Python has dozens of built-in types. Most of them you'll touch once a year. Seven you'll touch every single day. Get fluent in these and you can read 90% of Python code without a reference open.\n\nint — arbitrary-precision whole numbers. Unlike C or Java, Python ints don't overflow. 2 ** 1000 is fine. Slower than fixed-width ints in C, but you almost never care.\n\nfloat — IEEE-754 double precision. Same gotchas as every other language: 0.1 + 0.2 != 0.3 (it's 0.30000000000000004). For money, use the decimal module, not float.\n\nstr — immutable Unicode strings. 'café' has length 4, not 5, because Python counts Unicode code points, not bytes. Slicing returns a new string; concatenation creates a new string. We'll use this all the way through NLP week.\n\nbool — True or False. Quirky fact: bool is a subclass of int. True == 1 and sum([True, True, False]) == 2. Use it; it's a built-in feature.\n\nlist — ordered, mutable, fast appends. Indexed by integer position. Searching by value is O(n) — if you find yourself searching a list a lot, you probably want a set or dict.\n\ndict — hash map. Indexed by hashable keys. Insert, lookup, and delete are all O(1) average. As of Python 3.7, dicts preserve insertion order — that's now part of the language spec, not just CPython behaviour.\n\nset — unordered collection of unique hashable items. Membership test is O(1). Useful for dedup, intersection, union, difference.\n\nKnow when each is the right choice and half of clean Python writes itself.",
        hashtags: [...CORE, "#DataStructures", "#PythonBasics"],
        image: {
          template: "list",
          headline: "7 Python types you'll use every day",
          bullets: ["int — unbounded", "float — careful with decimals", "str — immutable Unicode", "bool — really an int", "list — ordered, mutable", "dict — O(1) lookup", "set — O(1) membership"],
          accent: "violet",
          aiPrompt: "Premium 7-item infographic, white background, violet number badges, snake glyph corner, 1:1 LinkedIn",
          canvaBrief: "White with violet dotted grid. Title top. 7 numbered rows in alternating brandWhisper bands. Each row: gradient violet badge + bold name + lighter description. Snake icon corner at 8% opacity.",
        },
      },
      {
        id: "d3-p3", day: 3, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "Mutable vs immutable — the bug everyone meets once",
        copy: "There's a Python bug so common, so subtle, and so universally caught at 2am that it deserves its own monument. The mutable default argument trap.\n\nLook at the snippet. The author wanted a function that appends an item to a bucket, defaulting to a fresh empty list when no bucket is passed. Reasonable.\n\nBut Python evaluates default arguments *once*, at function definition time. Not once per call. So that empty list `[]` is created ONCE when the def statement runs. Every call without a bucket argument shares the same list.\n\nFirst call adds 1. Second call adds 2 — but to the same list. The function silently accumulates state across calls. Now imagine this in a web server with concurrent requests. Or in a long-running ML pipeline. The bug shows up hours into a training run, after you've already shut your laptop and gone to bed.\n\nThe fix is one line. Default to None, then create a fresh list inside the function body when needed. Now each call starts clean.\n\nWhy does Python do this? Because evaluating default args once is faster, and because it lets you do clever caching tricks if you really want to. The cost is this footgun. The footgun is well-known. Linters (ruff, pylint) catch it. mypy doesn't, because the type is technically valid.\n\nThe broader lesson: mutable types in Python (list, dict, set) are passed by reference. If you mutate them inside a function, the caller sees the mutation. Immutable types (int, float, str, tuple) can't be mutated, so this whole class of bug doesn't happen for them.\n\nEvery Python developer meets this bug exactly once. Now you've met it.",
        hashtags: [...CORE, "#PythonGotchas", "#Debugging"],
        image: {
          template: "code",
          headline: "The mutable default trap",
          subhead: "Default args are evaluated once.",
          code: {
            language: "python",
            snippet: "def add(item, bucket=[]):       # WRONG\n    bucket.append(item)\n    return bucket\n\nprint(add(1))   # [1]\nprint(add(2))   # [1, 2]  <- !\n\ndef add(item, bucket=None):     # FIX\n    bucket = bucket or []\n    bucket.append(item)\n    return bucket",
          },
          accent: "violet",
          aiPrompt: "Dark code window with WRONG/FIX comparison, violet glow, mac controls, 1:1 LinkedIn",
          canvaBrief: "Dark gradient. Code window with mac controls. WRONG block in subtle red tint, FIX block in green tint. Title above, footer below.",
        },
      },
      {
        id: "d3-p4", day: 3, postNumber: 4, slot: "evening", type: "tip", pillar: "python",
        title: "f-strings beat every other formatting in Python",
        copy: "Three ways to format a string in Python. Only one of them is correct in 2026.\n\n# old (don't)\n'Hello %s, you are %d' % (name, age)\n\n# legacy (also don't)\n'Hello {}, you are {}'.format(name, age)\n\n# correct (always this)\nf'Hello {name}, you are {age}'\n\nf-strings landed in Python 3.6 (year 2016) and have only gotten better since. They're faster than %-format and .format(). They're more readable. They support every format spec you'd want. And in 3.8 they gained a debugging trick that's worth its weight in gold:\n\nf'{x=}' — produces 'x=42'. Print the variable name AND its value in one shot. Stop typing print(f'x = {x}'). Just print(f'{x=}'). Saves keystrokes; never gets the variable name out of sync with the label.\n\nFormat specs. f'{pi:.2f}' rounds to two decimals. f'{n:,}' adds thousand separators (1000000 → 1,000,000). f'{x:>10}' right-aligns to width 10. The full format spec mini-language is in the docs and worth a 10-minute read once.\n\nMulti-line and nested f-strings work. Python 3.12 lifted the parsing limitations that used to make complex f-strings annoying. You can now nest quotes, embed expressions across lines, and use backslashes inside the braces.\n\nIf you see %-format or .format() in 2026 code, two possibilities. Either it's copied from a 2014 Stack Overflow answer the author didn't update, or it's running on Python 3.5 (please upgrade). Neither is a good reason to keep writing them today.\n\nf-strings are not a stylistic preference. They're the answer.",
        hashtags: [...CORE, "#PythonTips", "#Python3"],
        image: {
          template: "tip",
          headline: "f-strings — the only format that matters",
          subhead: "Faster · Readable · Debuggable",
          bullets: [
            "f'Hello {name}'",
            "f'{x=}' → x=42",
            "f'{pi:.2f}'",
            "f'{n:,}' → 1,000,000",
          ],
          accent: "violet",
          aiPrompt: "Pro tip poster with monospace examples in floating card, violet gradient header, 1:1",
          canvaBrief: "Top violet gradient header with PRO TIP pill. White card below with 4 monospace examples in JetBrains Mono 26pt. Footer.",
        },
      },
      {
        id: "d3-p5", day: 3, postNumber: 5, slot: "night", type: "recap", pillar: "python",
        title: "Day 3 — types are values, not labels",
        copy: "End of Day 3. Three days in, fifteen posts shipped. The pace is real and so is the ground we're covering.\n\nWhat we did today.\n\nMorning we got the foundational mental model right. Variables in Python are labels; types belong to the values they point at. This single sentence resolves probably 80% of the confusion beginners feel about why the language behaves the way it does.\n\nMidday we listed the seven built-in types you'll touch every day — int, float, str, bool, list, dict, set. There are dozens more in the standard library, and you'll learn them as you need them, but those seven are the keyboard you play.\n\nAfternoon we walked through the mutable default argument trap. It's the bug every Python developer meets exactly once, usually at 2am, usually in production. Now you've met it on Day 3 of week 1, and your future self will thank past-you for the inoculation.\n\nEvening I made the case for f-strings being the only string formatting you should use in modern Python. f'{x=}' for debugging is worth the price of admission alone.\n\nA quiet observation about pacing. Three days into a 90-day sprint, you've already touched: AI/ML framing, dev environment setup, and the type system foundations. That's three things most online courses cover in three weeks. Public learning is faster because there's nowhere to hide.\n\nTomorrow, Day 4, we go into the two collection types you'll never escape — list and dict. Slicing tricks, comprehensions, the dict-merge operator from Python 3.9. The day Python starts to feel ergonomic instead of just functional.\n\nSee you tomorrow.",
        hashtags: [...CORE, "#PythonJourney", "#DailyRecap"],
        image: {
          template: "quote",
          headline: "A label is not a type. A value is.",
          subhead: "The sentence that unlocks Python.",
          accent: "violet",
          aiPrompt: "Soft pastel violet quote card, large headline, italic subhead, 1:1 LinkedIn",
          canvaBrief: "Pastel gradient. Big quote, italic subhead, accent bar, brand + pillar pills, footer.",
        },
      },
    ],
  },

  /* DAY 4 */
  {
    day: 4,
    theme: "Lists & dicts — the workhorses of every Python program",
    pillar: "python",
    posts: [
      {
        id: "d4-p1", day: 4, postNumber: 1, slot: "morning", type: "concept", pillar: "python",
        title: "Lists are arrays. Dicts are hash maps. That's it.",
        copy: "If I had to teach a beginner exactly one thing about Python data structures, it would be this — list and dict do 95% of the work, and choosing the right one is mostly about knowing what you'll do with it.\n\nA Python list is a dynamic array. Same shape as a Java ArrayList or a C++ vector. Memory-contiguous, doubles capacity when full, indexed by integer position. Append is O(1) amortised, index is O(1), but searching for a value is O(n) because the list has no idea what it contains.\n\nA Python dict is a hash table. Same shape as a Java HashMap or a C++ unordered_map. Indexed by any hashable key. Set, get, and 'in' tests are all O(1) on average. Iteration order matches insertion order since Python 3.7 (this is now part of the language spec, not a CPython implementation detail).\n\nThose two complexities — O(1) for dict lookup, O(n) for list search — drive about 95% of structure-choice decisions in real Python code. If you're going to look things up by an identifier, dict. If you're going to iterate everything in order, list. If you only care about membership, set. If the value won't change, tuple.\n\nThe other 5% of cases reach for collections.deque, heapq, defaultdict, Counter, OrderedDict. We cover those during DSA week.\n\nA pattern I see in real-world code over and over: parse data into a list, build a dict to look things up fast, iterate to do work. If you're comfortable with these two, you can ship most of what your job throws at you. Master one, you write Python. Master both, you understand it.",
        hashtags: [...CORE, "#DataStructures", "#PythonBasics"],
        image: {
          template: "compare",
          headline: "list vs dict — pick the right one",
          compare: {
            leftLabel: "list",
            leftItems: ["index by position", "fast append", "linear search", "ordered"],
            rightLabel: "dict",
            rightItems: ["index by key", "O(1) lookup", "no order before 3.7", "ordered since 3.7"],
          },
          accent: "violet",
          aiPrompt: "Split-screen list vs dict comparison, white left and violet right halves, technical icons, 1:1",
          canvaBrief: "Split 540/540 vertical. Left grey gradient with 4 list items. Right violet gradient with 4 dict items. VS badge center. Brand + pillar pills, footer.",
        },
      },
      {
        id: "d4-p2", day: 4, postNumber: 2, slot: "midday", type: "deepdive", pillar: "python",
        title: "Slicing — the most underused superpower",
        copy: "Most Python beginners learn lst[0] and lst[-1] and stop. They never internalise the full slicing syntax — and as a result, write five-line loops where one slice would do.\n\nThe full syntax is lst[start:stop:step]. Every part is optional. Combine the optionals and you get a small DSL for sequence manipulation.\n\nReverse a list — lst[::-1]. Step is -1, so we walk backwards. Way faster than reversed() + list() and arguably more readable.\n\nEvery other element — lst[::2]. Step is 2.\n\nDrop the first element — lst[1:]. Drop the last — lst[:-1]. Drop both — lst[1:-1].\n\nDelete a slice in place — lst[a:b] = []. The list shrinks by (b-a) elements, no new list created.\n\nReplace contents without rebinding — lst[:] = other. The variable still points at the same list object, but its contents are now whatever 'other' contained. Useful when other code holds a reference to your list and you want them to see the change.\n\nString slicing works the same way. 'hello world'[6:] gives 'world'. 'racecar'[::-1] gives 'racecar'. NumPy arrays slice by the same syntax (with multi-dimensional extensions).\n\nWhy does this matter? Because every for-loop you replace with a slice is fewer lines, fewer index-off-by-one bugs, and faster code (slicing happens in C). The number of times I've seen new developers write 'for i in range(len(lst)): if i > 0: result.append(lst[i])' when 'result = lst[1:]' would do…\n\nLearn the full syntax once. It pays back forever.",
        hashtags: [...CORE, "#PythonTricks", "#Slicing"],
        image: {
          template: "list",
          headline: "6 slicing tricks every Pythonista should know",
          bullets: [
            "lst[::-1] — reverse",
            "lst[::2] — every other",
            "lst[1:] — drop first",
            "lst[:-1] — drop last",
            "lst[a:b] = [] — delete slice",
            "lst[:] = other — replace in place",
          ],
          accent: "violet",
          aiPrompt: "6-tip infographic in white-violet, monospace examples in pill cards, 1:1 LinkedIn",
          canvaBrief: "White background. Title top. 6 rows alternating violetWhisper bands. Each row: gradient number badge + monospace example.",
        },
      },
      {
        id: "d4-p3", day: 4, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "List & dict comprehensions — the loops you don't write",
        copy: "If I could pick one syntax feature to teach beginners and turn them into 'Python developers' overnight, it would be comprehensions. Every Pythonic codebase is full of them.\n\nThe basic shape — [expr for x in iterable if cond]. Read it left to right: 'a list of expr, for each x in iterable, where cond is true'. It builds a new list directly, no .append() loop.\n\nSquares of even numbers up to 20 — [x*x for x in range(20) if x % 2 == 0]. One line, intent obvious, and faster than the equivalent for-loop because CPython optimises the bytecode.\n\nDict comprehensions follow the same shape with curly braces and a key:value expression. {w: i for i, w in enumerate(words)} builds a word-to-index map from a list. Useful for tokenisers, lookup tables, anywhere you transform a sequence into a dict.\n\nSet comprehensions look like dict comprehensions but without the colon. {c.lower() for c in text if c.isalpha()} gives unique lowercase letters. The set deduplicates automatically.\n\nNested comprehensions exist but use them sparingly. Two levels deep is the limit before readability collapses. If you find yourself writing a triple-nested comprehension, that's a sign to break it up.\n\nWhen NOT to use them. Comprehensions are for transforms and filters. If your loop body has side effects — writing to a file, printing, mutating a global — write a regular for-loop. The comprehension's purpose is to produce a new collection cleanly. Mixing in side effects is what gives comprehensions a bad name.\n\nGenerator expressions, the lazy cousin of list comprehensions, get their own day on Day 11. Same syntax with parentheses instead of brackets. Same speed-up; way less memory.",
        hashtags: [...CORE, "#Comprehensions", "#PythonStyle"],
        image: {
          template: "code",
          headline: "Comprehensions — fewer loops, less bugs",
          subhead: "List · Dict · Set",
          code: {
            language: "python",
            snippet: "# list comp\nsquares = [x*x for x in range(10)]\n\n# with filter\nevens = [x for x in nums if x % 2 == 0]\n\n# dict comp\nlookup = {w: i for i, w in enumerate(words)}\n\n# set comp\nletters = {c.lower() for c in text if c.isalpha()}",
          },
          accent: "violet",
          aiPrompt: "Dark IDE code card with comprehensions, violet glow, 1:1",
          canvaBrief: "Dark gradient with code window showing 4 comprehension examples. Title above. Footer.",
        },
      },
      {
        id: "d4-p4", day: 4, postNumber: 4, slot: "evening", type: "tip", pillar: "python",
        title: "Three dict moves you probably don't know",
        copy: "Most Python developers learn dicts up to d[k] and d[k] = v and then stop. There are three more dict moves that, once internalised, will cut your data-wrangling code in half. I'm not exaggerating.\n\nFirst — dict.get(key, default). Returns d[key] if key exists, otherwise the default. No more KeyError, no more 'if key in d' checks. Use this any time you're reading from a dict and aren't 100% sure the key exists. Especially common when parsing API responses where some fields are optional.\n\nSecond — collections.defaultdict(list). Auto-creates an empty list (or anything else) the first time you access a missing key. Now d[key].append(x) just works. The classic group-by pattern that used to take five lines becomes two. defaultdict(int) gives you a counter — d[key] += 1 works on every key, even unseen ones. defaultdict(set) gives you unique-per-key. Nest them for matrices.\n\nThird — d1 | d2. The dict-merge operator from Python 3.9. Returns a new dict with both d1 and d2's keys (d2 wins on conflicts). The old way was {**d1, **d2}, which still works. The new way is more readable and slightly faster.\n\nBonus — dict(zip(keys, values)) builds a dict from two parallel lists. Useful when you have ['name', 'age', 'city'] and ['Saurav', 30, 'Bengaluru'] from a CSV.\n\nBonus 2 — d.items() lets you iterate keys and values together. for key, value in d.items(): ... Always cleaner than for key in d: value = d[key].\n\nDicts have more sharp tools than people use. Take an afternoon and explore the docs. The pyhon 'collections' module also has Counter, OrderedDict, ChainMap — useful when the situation calls for it.",
        hashtags: [...CORE, "#PythonDict", "#PythonTips"],
        image: {
          template: "tip",
          headline: "3 dict moves that replace 30 lines",
          bullets: [
            "dict.get(k, default)",
            "defaultdict(list)",
            "d1 | d2  (3.9+)",
            "dict(zip(keys, vals))",
          ],
          accent: "violet",
          aiPrompt: "Pro tip card with monospace examples, violet header, 1:1",
          canvaBrief: "Violet header gradient + PRO TIP pill. White card with 4 monospace lines. Footer.",
        },
      },
      {
        id: "d4-p5", day: 4, postNumber: 5, slot: "night", type: "recap", pillar: "python",
        title: "Day 4 — pick the right container, win the day",
        copy: "End of Day 4. Twenty posts in. We're 4.4% of the way through the sprint and Python is starting to feel native, not foreign. That's the goal.\n\nWhat we covered today.\n\nMorning, the foundation — list and dict. Dynamic array versus hash map. Two structures, two complexity profiles, 95% of the choices you'll ever make. Get this right and your code is fast by default; get it wrong and you'll find yourself optimising loops that shouldn't have been loops.\n\nMidday, slicing as a superpower. The lst[start:stop:step] syntax that most beginners never fully internalise. Reversal, every-other, drop-first, drop-last, in-place delete and replace — all one-liners. Every slice you write is a for-loop you didn't.\n\nAfternoon, comprehensions — the loops you don't write at all. List, dict, and set forms. Faster than for-loops in CPython because the bytecode is optimised. Cleaner than for-loops because the intent is in the expression. The shape becomes muscle memory after about 50 of them.\n\nEvening, three dict moves that compound across every project — .get(k, default), defaultdict, and the | merge operator. Plus dict(zip()) and .items(). Each one of these saves a few lines per use; across a year they save hundreds.\n\nReflection on pacing. We're four days in and you've already seen: project framing, environment setup, type system, control flow, comprehensions. By the end of week 1, you'll be able to write idiomatic Python from a blank file. By week 2 we go OOP and decorators.\n\nTomorrow, Day 5, we cover loops and control flow done right. Why range(len(lst)) is a code smell. The for/else clause Python actually has. The walrus operator's two real uses.\n\nSee you tomorrow.",
        hashtags: [...CORE, "#PythonProgress", "#DailyRecap"],
        image: {
          template: "quote",
          headline: "Pick the right container. Win the day.",
          subhead: "list and dict do 95% of the work.",
          accent: "violet",
          aiPrompt: "Soft violet quote card, premium minimal, 1:1",
          canvaBrief: "Pastel gradient. Big quote, italic subhead, accent bar, brand pill, footer.",
        },
      },
    ],
  },

  /* DAY 5 */
  {
    day: 5,
    theme: "Loops & control flow — the Python way",
    pillar: "python",
    posts: [
      {
        id: "d5-p1", day: 5, postNumber: 1, slot: "morning", type: "concept", pillar: "python",
        title: "Stop writing C-style loops in Python",
        copy: "I can spot a developer who came to Python from Java or C in two seconds, just by looking at their loops.\n\nfor i in range(len(lst)):\n    print(lst[i])\n\nThat's a C loop in Python clothing. It works, but it's writing C with extra steps. The Pythonic version is one line shorter and impossible to off-by-one:\n\nfor item in lst:\n    print(item)\n\nNeed the index too? Use enumerate. for i, item in enumerate(lst): gives you both. Don't reach for range(len()) — that's a habit from languages where you HAD to track indices. Python iterates over iterables natively.\n\nNeed two parallel lists? zip is the answer. for a, b in zip(xs, ys): gives you pairs. Python 3.10 added zip(xs, ys, strict=True), which raises if the two iterables have different lengths. Use it. Silent zip-truncation is a bug class.\n\nNeed to walk over chunks of a list? itertools.batched(lst, n) (Python 3.12+) yields tuples of n consecutive items. Before 3.12, you wrote a manual chunker. After, you don't.\n\nThe broader principle. Python's for-loop iterates over *values*, not over an integer index that you then use to retrieve values. Once you internalise this, your loops shrink, your bug surface shrinks, and your code reads like English.\n\nThe rare exception is when you genuinely need the index for arithmetic — e.g., comparing element i with element i+1. Even then, enumerate plus a sentinel is usually cleaner than range(len()).\n\nIt's a small habit. The amount of grief it saves a Python codebase, over years, is enormous. Break the C-style reflex.",
        hashtags: [...CORE, "#PythonStyle", "#PythonBasics"],
        image: {
          template: "compare",
          headline: "C-style vs Python-style loops",
          compare: {
            leftLabel: "C-style",
            leftItems: ["for i in range(len(lst))", "manual index management", "off-by-one bugs", "verbose"],
            rightLabel: "Pythonic",
            rightItems: ["for item in lst", "for i, x in enumerate(lst)", "for a, b in zip(x, y)", "concise"],
          },
          accent: "violet",
          aiPrompt: "Split compare poster, grey vs violet, code-style snippets, 1:1",
          canvaBrief: "Split 540/540. Left grey with old-style code. Right violet with pythonic. VS badge.",
        },
      },
      {
        id: "d5-p2", day: 5, postNumber: 2, slot: "midday", type: "deepdive", pillar: "python",
        title: "The loop-else clause — Python's best-kept secret",
        copy: "Python has a feature so obscure that some Python developers I've worked with for years didn't know it existed. It's called the loop-else clause, and once you start using it, you wonder how you ever wrote search loops without it.\n\nfor item in items:\n    if matches(item):\n        return item\nelse:\n    raise NotFound()\n\nThe else clause attached to a for-loop runs ONLY if the loop completed without hitting a break (or an early return, in this case). It's a clean way to say 'I searched the whole iterable and didn't find what I was looking for'.\n\nThe alternative — the dance most developers do — is a found = False flag. Set it inside the if, check it after the loop. Six lines, two state variables, three places to make a mistake. The for/else does the same thing in zero extra state.\n\nWorks the same on while-loops. while not done: ... else: <runs only if condition went False without a break>.\n\nThe naming is admittedly bad. 'else' here means 'else after the loop', not 'else if the loop didn't run'. Guido has publicly said he'd name it 'nobreak' if he could go back. The keyword is what we have, though, and it's standard Python.\n\nOne caveat — if you're new on a team, leave a one-line comment the first time you use it. Half your reviewers will ask 'wait, when does that else fire?' Better to head off the question than risk a 'is this a bug?' comment.\n\nOnce the team knows, they keep using it. Search loops, validation loops, retry loops — all cleaner with for/else. It's free in the language. Use it.",
        hashtags: [...CORE, "#PythonAdvanced", "#PythonHidden"],
        image: {
          template: "code",
          headline: "for/else — the loop clause nobody teaches",
          code: {
            language: "python",
            snippet: "for item in items:\n    if matches(item):\n        return item\nelse:\n    # runs only if the loop didn't break\n    raise NotFound()",
          },
          accent: "violet",
          aiPrompt: "Dark code card highlighting else clause, violet, 1:1",
          canvaBrief: "Dark gradient code window with for/else snippet, else line highlighted in cyan.",
        },
      },
      {
        id: "d5-p3", day: 5, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "match-case — better than a chain of ifs",
        copy: "Python 3.10 added structural pattern matching with match/case. Most articles online still describe it as 'switch with new syntax'. That undersells it badly. It's pattern matching, not switching — it can deconstruct dicts, lists, tuples, and even your own classes.\n\nLook at the snippet. Each case isn't checking equality — it's matching the *shape* of the value. The first case matches dicts that have a 'type' of 'click' and binds x and y from the dict's structure. The second matches scroll events with a 'dy'. The third matches anything with a string-typed 'type' and binds it. The wildcard _ catches everything else.\n\nThis kind of dispatching, before 3.10, was an isinstance ladder or a dict-of-functions. Pattern matching makes it readable as English. Each case is a spec, not a check.\n\nPattern matching also supports guards — case [first, *rest] if first.startswith('http'): runs only if the list-pattern AND the boolean condition both match. It supports class patterns — case Point(x=0, y=y): matches a Point with x=0, binding y. It supports literal-or — case 'GET' | 'HEAD':.\n\nWhen NOT to use it. If your branches are simple equality checks on a single variable, an if/elif chain is just as clear and avoids the new syntax. If your branches are heterogeneous in what they consume — some look at the type, some look at a field, some look at length — pattern matching shines.\n\nRule of thumb: if you find yourself writing isinstance() three or more times in a row, or destructuring a dict's fields by hand, switch to match/case.\n\nThe code reads like a specification. The interpreter does the heavy lifting.",
        hashtags: [...CORE, "#Python310", "#PythonAdvanced"],
        image: {
          template: "code",
          headline: "match-case beats if-elif chains",
          code: {
            language: "python",
            snippet: "def handle(event):\n    match event:\n        case {'type': 'click', 'x': x, 'y': y}:\n            return click(x, y)\n        case {'type': 'scroll', 'dy': dy}:\n            return scroll(dy)\n        case {'type': str(t)}:\n            log_unknown(t)\n        case _:\n            raise ValueError(event)",
          },
          accent: "violet",
          aiPrompt: "Dark IDE code card with pattern matching, premium violet accents, 1:1",
          canvaBrief: "Dark gradient code window with the match-case snippet. Headline above.",
        },
      },
      {
        id: "d5-p4", day: 5, postNumber: 4, slot: "evening", type: "tip", pillar: "python",
        title: "The walrus operator — when it earns its keep",
        copy: "Python 3.8 added the walrus operator, := (so named because the colon-equals looks like a walrus's eyes and tusks). It assigns and returns a value in a single expression.\n\nMost code shouldn't use it. Most uses I've seen on the internet are 'saving a line' in places where saving the line costs readability. The walrus is a power tool — useful, but easy to overdo.\n\nThere are two cases where it genuinely earns its place.\n\nCase one — avoiding recomputation in a comprehension. Suppose you have an expensive function expensive(x) and you want to keep only positives. Without walrus, you compute it twice or write a for-loop. With walrus, [y for x in data if (y := expensive(x)) > 0] computes once and filters in one pass.\n\nCase two — read-and-test in a while loop. Reading a stream in chunks until empty:\n\nwhile chunk := stream.read(4096):\n    process(chunk)\n\nThe assignment happens, the result is tested, the loop continues until read() returns falsy. Without walrus, you write a 'while True / read / break' dance. With walrus, the intent is in the loop header.\n\nThat's it. Two cases. If you're tempted to use walrus to 'save a line' anywhere else — in an if-else, in a regular assignment, in a function call — don't. The savings aren't worth the cognitive cost.\n\nA useful self-check. If a colleague asks 'why is this a walrus?' and your answer is 'to save a line', it shouldn't be a walrus. If your answer is 'to avoid double computation' or 'to read-and-test in a single expression', it's correct.\n\nPower tools. Sparingly.",
        hashtags: [...CORE, "#PythonTips", "#Python38"],
        image: {
          template: "tip",
          headline: "The walrus :=  — only two real uses",
          bullets: [
            "Avoid recomputing in a comprehension",
            "Read-and-test in a while loop",
            "Don't use it to 'save a line'",
          ],
          accent: "violet",
          aiPrompt: "Pro tip poster with walrus emoji-style decoration, premium, 1:1",
          canvaBrief: "Violet header with PRO TIP pill. White card with 3 items. Footer.",
        },
      },
      {
        id: "d5-p5", day: 5, postNumber: 5, slot: "night", type: "recap", pillar: "python",
        title: "Day 5 — loops you don't manage by hand",
        copy: "End of Day 5. Twenty-five posts shipped. The first week is more than half done.\n\nA recap and a confession. Today's theme was control flow done the Python way, and writing about it forced me to rethink some of my own habits. I went back through a couple of recent personal projects after writing the morning post and found two range(len()) loops I should have written as enumerate. They've been merged.\n\nWhat we covered.\n\nMorning, why C-style loops are a tell — and how to replace them with Python's iteration primitives. for x in lst, enumerate, zip(strict=True), itertools.batched. Each one a small win; together, idiomatic Python.\n\nMidday, the loop-else clause. Python's most underused feature. Eliminates the 'found = False' flag dance. Once you know it exists, you reach for it.\n\nAfternoon, match/case for clean dispatch. Not a switch statement — pattern matching. Use when you're checking shape (dict-with-fields, class-with-attributes, list-with-prefix), not just equality.\n\nEvening, the walrus operator's two real uses — recomputation in comprehensions, read-and-test in while loops. Two cases. Anywhere else, don't.\n\nA broader theme is showing up across this week — Python is small at its core, but rich at the edges. The basics (variables, lists, dicts) are six chapters in any textbook. The 'feature' set (comprehensions, walrus, match/case, for/else) is what separates someone who writes Python from someone who *thinks* in Python.\n\nTomorrow, Day 6, we wrap the basics with functions. Default args (without the trap from Day 3), keyword-only args, *args/**kwargs, lambdas. Functions in Python are first-class — meaning every framework you'll touch (Flask, FastAPI, PyTorch) treats them as values. Tomorrow we make peace with that.\n\nSee you in the morning.",
        hashtags: [...CORE, "#100DaysPython", "#DailyRecap"],
        image: {
          template: "quote",
          headline: "Loop the values. Not the indices.",
          subhead: "The Pythonic mindset, in one sentence.",
          accent: "violet",
          aiPrompt: "Pastel violet quote card, 1:1",
          canvaBrief: "Pastel gradient quote card with bold quote and italic subhead.",
        },
      },
    ],
  },

  /* DAY 6 */
  {
    day: 6,
    theme: "Functions — the building block you'll write a million times",
    pillar: "python",
    posts: [
      {
        id: "d6-p1", day: 6, postNumber: 1, slot: "morning", type: "concept", pillar: "python",
        title: "A function is a value in Python",
        copy: "Coming from Java or C++, the idea that 'a function is a value' takes some adjustment. In those languages, methods belong to classes, classes are first-class, methods aren't.\n\nIn Python, functions are first-class. That means a function — the def add(a, b): return a + b you wrote — is itself a value. It has a name, a type (function), and you can pass it around exactly like an int or a string.\n\nLet me show you. Define add, sub, mul. Now do this:\n\nops = [add, sub, mul]\nfor op in ops:\n    print(op(2, 3))\n\nYou just iterated over functions and called each one. The interpreter didn't blink, because to it, ops is just a list of three values that happen to be callable.\n\nThis is the foundational fact behind a stack of features that show up in every Python codebase you'll ever read.\n\nDecorators (Day 10) work because @my_decorator is shorthand for 'pass this function to my_decorator and replace it with the result'. That requires functions to be values.\n\nCallbacks work — the on_click handlers in your UI library, the key= argument in sorted(), the loss function you pass into PyTorch's training loop — all of them depend on this.\n\nHigher-order functions like map, filter, reduce work for the same reason.\n\nThis isn't a 'cool feature'. It's the bedrock for everything that makes modern Python ergonomic. Embrace it. Stop putting everything in classes (a Java reflex). Start writing small composable functions — they pass around freely, they test in isolation, they compose without ceremony.\n\nFunctions are first-class. Internalise it once and a lot of Python suddenly clicks.",
        hashtags: [...CORE, "#FunctionalProgramming", "#PythonOOP"],
        image: {
          template: "stat",
          headline: "Functions are first-class",
          subhead: "Pass them, store them, return them.",
          stat: { number: "1st", label: "class — like ints, strings, lists" },
          accent: "violet",
          aiPrompt: "Concept stat poster, deep purple background, 1st large, 1:1",
          canvaBrief: "Gradient deep violet. Big 1st centered, subhead, accent ring, brand pills, footer.",
        },
      },
      {
        id: "d6-p2", day: 6, postNumber: 2, slot: "midday", type: "deepdive", pillar: "python",
        title: "Args, kwargs, and the order that matters",
        copy: "Python's function signature has way more dials than people use, and learning them turns 'serviceable' functions into well-designed APIs.\n\nThe full shape, in one signature:\n\ndef f(a, b, /, c, d, *, e, f):\n    ...\n\nThe forward slash and asterisk are signature markers, not parameters. They divide the parameters into three zones.\n\nBefore the / are positional-only. Callers MUST pass them by position; they cannot pass them by keyword. Useful for the first one or two arguments where keyword names would be noise — open(path, mode), pow(base, exp).\n\nBetween / and * are flexible — callers may pass by position or by keyword. This is the default zone for most parameters.\n\nAfter the * are keyword-only. Callers MUST pass them by keyword. This is invaluable for booleans and 'optional' configuration.\n\nWhy lock down the call style?\n\nForce keyword-only for booleans. Compare f(True) to f(dry_run=True). The first reads like a code golf challenge; the second is self-documenting. Adding *, dry_run=False to your signature forces every caller to label what True or False means.\n\nForce positional-only for required arguments. open('/etc/hosts', 'r') reads naturally. open(path='/etc/hosts', mode='r') is verbose noise.\n\nThe modern Python idiom for any function with two or more booleans, or any flag with non-obvious meaning, is to put it after a *. Most stdlib functions do this. Most popular libraries do this. The result is calling code that reads as English.\n\nNext time you're designing a function, spend an extra 30 seconds on the signature. Decide which arguments must be positional, which must be keyword, which can be either. The function's lifetime users will thank you.",
        hashtags: [...CORE, "#PythonAdvanced", "#APIDesign"],
        image: {
          template: "list",
          headline: "Function signature — the order matters",
          bullets: [
            "Before / — positional only",
            "Between / and * — flexible",
            "After * — keyword only",
            "Use kwarg-only for booleans",
            "Use pos-only for required path/mode",
          ],
          accent: "violet",
          aiPrompt: "5-row infographic on white-violet, sig diagram, 1:1",
          canvaBrief: "White with violet grid. Title. 5 numbered rows. Bottom: small monospace example.",
        },
      },
      {
        id: "d6-p3", day: 6, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "*args, **kwargs — what they actually do",
        copy: "*args and **kwargs cause more confusion than any other Python feature, and the confusion is purely about syntax overlap. There are two different operations using the same symbols.\n\nIn a function definition, * and ** are *packing*. They collect leftover positional arguments into a tuple, and leftover keyword arguments into a dict.\n\ndef log(level, *messages, **fields):\n    print(level, messages, fields)\n\nNow log('INFO', 'saved', 'ok', user='sd', id=7) prints:\nINFO ('saved', 'ok') {'user': 'sd', 'id': 7}\n\nThe positional 'saved' and 'ok' got packed into messages. The keyword user= and id= got packed into fields. The required level got bound by position.\n\nIn a function call, * and ** are *unpacking*. They take a sequence or a dict and spread it into positional/keyword arguments.\n\nargs = ('INFO', 'saved')\nkwargs = {'user': 'sd'}\nlog(*args, **kwargs)\n\nThis is the same as log('INFO', 'saved', user='sd'). The tuple gets spread; the dict gets spread.\n\nYou'll see this pattern everywhere. Decorators use *args, **kwargs to forward arbitrary arguments to the wrapped function. Class hierarchies use **kwargs in __init__ to pass through to super(). Test fixtures spread parametrized arguments into test functions.\n\nDon't overuse them in your OWN code. Explicit named parameters are more readable, easier to type-check, easier to refactor. Save *args/**kwargs for the few specific situations where you genuinely need to accept anything — wrappers, forwarders, decorators.\n\nKnow them, recognise them, use them when justified, but default to explicit named parameters in the functions you write.",
        hashtags: [...CORE, "#PythonInternals", "#PythonAdvanced"],
        image: {
          template: "code",
          headline: "*args / **kwargs — packing & unpacking",
          code: {
            language: "python",
            snippet: "def log(level, *messages, **fields):\n    print(level, messages, fields)\n\nlog('INFO', 'saved', 'ok', user='sd', id=7)\n# INFO ('saved','ok') {'user':'sd','id':7}\n\n# unpacking\nargs = ('INFO', 'saved')\nkwargs = {'user': 'sd'}\nlog(*args, **kwargs)",
          },
          accent: "violet",
          aiPrompt: "Dark code card with star args/kwargs, violet, 1:1",
          canvaBrief: "Dark gradient code window. Headline. Footer.",
        },
      },
      {
        id: "d6-p4", day: 6, postNumber: 4, slot: "evening", type: "tip", pillar: "python",
        title: "Lambdas — short but rarely the right answer",
        copy: "Every Python tutorial introduces lambda eventually, and most beginners walk away thinking they should use it everywhere. They should not.\n\nA lambda is an anonymous one-line function. lambda x: x * x is shorthand for an unnamed function returning x squared. The whole expression IS the function — no name, no def statement, no return keyword.\n\nThere are exactly two situations where lambda is the right call.\n\nFirst, as a one-shot key argument to a built-in. sorted(people, key=lambda p: p.age) is clean. The function exists for one purpose, used once, and naming it square or get_age would be ceremony for no benefit. Same with filter(lambda x: x.ok, items), max(items, key=lambda i: i.score), and similar.\n\nSecond, in DSLs and frameworks that explicitly take callables. PyTorch's data transformations, pandas' .apply(), Django's URL configs sometimes. The framework expects a function; you supply one inline.\n\nWhere lambda is the WRONG call.\n\nIf you're saving the lambda to a name — square = lambda x: x * x — just write def square(x): return x * x. You get a proper function with a meaningful __name__ in stack traces, a docstring slot, and the ability to add type hints.\n\nIf the lambda is more than one line of logic — too late, it can't be. Multi-statement lambdas don't exist in Python by design. The moment your lambda needs an if-else (a ternary still works, but if you need branching), use def.\n\nIf the lambda is hard to read — Python's lambda has no extras. No statements, no annotations, no assignments. The constraint pushes you toward def for anything non-trivial.\n\nLambdas are tactical. Use sparingly, and only as one-shot keys.",
        hashtags: [...CORE, "#CleanCode", "#PythonStyle"],
        image: {
          template: "tip",
          headline: "Use lambdas only as one-shot keys",
          bullets: [
            "sorted(..., key=lambda x: x.age) ✓",
            "filter(..., lambda x: x.ok) ✓",
            "Saving as a name? Use def.",
            "Multi-line logic? Use def.",
          ],
          accent: "violet",
          aiPrompt: "Pro tip poster with lambda symbol motif, 1:1",
          canvaBrief: "Violet header with PRO TIP. White card with 4 items. Brand bar.",
        },
      },
      {
        id: "d6-p5", day: 6, postNumber: 5, slot: "night", type: "recap", pillar: "python",
        title: "Day 6 — functions are values",
        copy: "End of Day 6. Thirty posts in. Tomorrow we close out week 1.\n\nWhat we covered.\n\nMorning, the foundational shift — functions in Python are first-class values. You can store them in lists, pass them as arguments, return them from other functions. This single fact is the bedrock under decorators, callbacks, higher-order functions, and most of the framework code you'll ever read. If you came from Java or C++, this can take a week to actually feel natural. Worth the rewiring.\n\nMidday, function signatures with intent. The / and * markers split parameters into positional-only, flexible, and keyword-only zones. Use this to make booleans explicit (force keyword-only) and to keep required arguments terse (allow positional-only). It's a half-hour of API design that pays back across the function's lifetime.\n\nAfternoon, the *args/**kwargs split — packing in definitions, unpacking in calls. Same syntax, opposite operations. Recognise both, use them when forwarding, but default to explicit named parameters in your own code.\n\nEvening, lambda discipline. Two real uses (one-shot keys, framework callbacks), no other excuses. Anything else, write a def. Stack traces, debuggers, and your future-self all thank you.\n\nA week-one perspective check. We've covered: sprint setup, env tooling, types, control flow, comprehensions, functions. That's a solid Python core. By tomorrow we'll wrap with a recap and the reading list I'm using. By next Monday we're into OOP, decorators, generators — week 2 territory.\n\nIf you're following along with code, your Day 1-6 GitHub repo should have something running for at least four of the days by now. Don't worry about polish. Worry about 'does this run on my laptop'.\n\nTomorrow, Day 7 — week 1 wrap, the seven biggest lessons in seven posts, plus my exact reading list for the next 83 days.",
        hashtags: [...CORE, "#PythonFunctions", "#DailyRecap"],
        image: {
          template: "quote",
          headline: "Small functions. Composed. Named.",
          subhead: "How clean Python actually looks.",
          accent: "violet",
          aiPrompt: "Soft violet quote card, 1:1",
          canvaBrief: "Pastel violet quote card with accent bar.",
        },
      },
    ],
  },

  /* DAY 7 */
  {
    day: 7,
    theme: "Week 1 recap + the reading list I'm following",
    pillar: "career",
    posts: [
      {
        id: "d7-p1", day: 7, postNumber: 1, slot: "morning", type: "recap", pillar: "career",
        title: "Week 1 in 7 lessons",
        copy: "End of week one. 35 posts shipped. Time to step back and ask — what mattered, what surprised me, what I'd tell day-one-me if I could.\n\nSeven lessons, in the order they landed.\n\nOne. Make it public. Genuinely. Five posts a day forces you to compress what you learned into something a stranger can read. The compression is the learning. Private notebooks are kindling; public posts are fuel.\n\nTwo. AI ⊃ ML ⊃ DL is a sentence worth memorising. Three nested circles. Use the right word and the conversation gets clearer; use the wrong one and you sound like a marketing deck.\n\nThree. Tools first. uv + ruff + pyproject.toml. One afternoon of setup buys you the rest of your Python career without environment fights. The cost of not doing this is paid every morning until you do.\n\nFour. In Python, types belong to values, not labels. Variables are pointers; values have types. This single mental model resolves probably 80% of beginner confusion about the language.\n\nFive. List and dict do 95% of the work. Choose by complexity profile — array versus hash map. The remaining 5% (set, deque, heap, defaultdict) you reach for when the situation calls for it.\n\nSix. Loop the values, not the indices. enumerate, zip, comprehensions. range(len()) is a tell that you brought C habits to Python.\n\nSeven. Functions are first-class. They go in lists, get passed as args, get returned from other functions. Once this clicks, decorators and callbacks stop being magic.\n\nThe theme tying it all together — Python rewards explicitness. Be explicit about types, about call style, about which container you're using and why. The clearer your intent, the cleaner the code. Onward to week two.",
        hashtags: [...CORE, "#WeekRecap", "#90DaysOfAI"],
        image: {
          template: "list",
          headline: "Week 1 — 7 lessons",
          bullets: [
            "AI ⊃ ML ⊃ DL",
            "uv + ruff + pyproject",
            "Types belong to values",
            "list & dict ≈ 95%",
            "Loop values, not indices",
            "Functions are first-class",
            "Build tiny, ship public",
          ],
          accent: "violet",
          aiPrompt: "7-item recap infographic, white-violet, premium, 1:1",
          canvaBrief: "White grid background, 7 numbered rows alternating brandWhisper bands. Top headline.",
        },
      },
      {
        id: "d7-p2", day: 7, postNumber: 2, slot: "midday", type: "deepdive", pillar: "career",
        title: "The exact AI/ML reading list I'm following",
        copy: "People keep asking what I'm reading. Here's the actual list — books, courses, channels — that survived my filter for this 90-day sprint. I've cut the ones that overlap or that I'd recommend mainly out of nostalgia.\n\nFluent Python by Luciano Ramalho. The single best Python book if you want to go from 'writes Python' to 'thinks in Python'. Long, dense, worth every page. Reread chapters as you encounter the topics in your day job.\n\nHands-On Machine Learning by Aurélien Géron (3rd edition, the 2022 one). Best practical intro to classical ML. Code-first, math-as-needed, scikit-learn and Keras both covered. Read chapters 1-9 for ML, 10-15 for the DL section.\n\nDive into Deep Learning (d2l.ai). Free, online, code-first deep learning textbook. PyTorch, JAX, and TensorFlow versions. Notebooks for every chapter. The right resource if you want depth without paying for a course.\n\nfast.ai courses. Top-down, practical, opinionated. Jeremy Howard's teaching style is unusual — show the result first, explain the theory after. It works for some learners and not for others. Try one lesson; you'll know.\n\nKarpathy's 'Neural Networks: Zero to Hero' on YouTube. Andrej Karpathy explains backprop, transformers, and tokenisers from first principles, building each from scratch in a notebook. Free. Probably the best deep-learning teaching material on the internet right now.\n\n3Blue1Brown's deep learning playlist. Visual intuition for the math. Pair with anything technical and the math suddenly makes sense.\n\nLilian Weng's blog (lilianweng.github.io). Survey-grade summaries of agent design, prompt engineering, RL fundamentals. Reference material — bookmark, don't read in one sitting.\n\nFree beats paid. Practice beats reading. Bookmark this; I'll cite it across the next 83 days.",
        hashtags: [...CORE, "#AILearning", "#ReadingList"],
        image: {
          template: "list",
          headline: "AI/ML reading list — 7 sources I trust",
          bullets: [
            "Fluent Python — Ramalho",
            "Hands-On ML — Géron",
            "d2l.ai — free DL book",
            "fast.ai — practical courses",
            "Karpathy: Zero to Hero",
            "3Blue1Brown DL series",
            "Lilian Weng's blog",
          ],
          accent: "violet",
          aiPrompt: "Premium reading-list infographic, book-spine icons, white-violet, 1:1",
          canvaBrief: "White with violet dotted grid. Headline top. 7 rows with violet number badges + book titles. Stylised book-spine glyph corner.",
        },
      },
      {
        id: "d7-p3", day: 7, postNumber: 3, slot: "afternoon", type: "code", pillar: "python",
        title: "A 12-line pyproject.toml for any AI/ML project",
        copy: "Before the week ends, here's the exact pyproject.toml I drop into every new AI/ML repo. Copy it, rename the project, swap dependencies for your stack, you're done.\n\nThe [project] section declares the basics — name, version, Python version requirement, and the dependencies that uv will install when you run uv sync. The version specifier 'requires-python = >=3.11' is intentional. As of 2026, 3.11 is the minimum I'd target — you get exception groups, decent typing, and good error messages.\n\nDependencies stay flat in this section. Just package names. Specific version pins live in the auto-generated uv.lock file, which you commit. The two together give you reproducibility without locking your pyproject.toml to specific versions.\n\nThe [tool.ruff] section sets line-length to 100 (the modern default; 88 is too narrow on wide screens, 120 is too generous for diff-friendliness) and enables a tight set of rule families: E (pycodestyle errors), F (pyflakes — undefined names, unused imports), I (isort — import ordering), UP (pyupgrade — modernise old syntax), B (bugbear — common bug patterns). These five letters catch most of the issues I'd otherwise hit in code review.\n\nThe [tool.pytest.ini_options] section sets pytest's default flags. addopts = '-q' makes pytest output less noisy. You'll add more options as your test suite grows.\n\nThis is the floor. Add type-checker config under [tool.mypy] when you want it. Add hatch or build-system entries when you publish to PyPI. For 90% of personal AI/ML projects, this 12-line file is the entire setup.",
        hashtags: [...CORE, "#PythonSetup", "#uv"],
        image: {
          template: "code",
          headline: "Drop-in pyproject.toml",
          code: {
            language: "toml",
            snippet: "[project]\nname = \"my-ai-project\"\nversion = \"0.1.0\"\nrequires-python = \">=3.11\"\ndependencies = [\n  \"numpy\",\n  \"pandas\",\n  \"scikit-learn\",\n]\n\n[tool.ruff]\nline-length = 100\nselect = [\"E\",\"F\",\"I\",\"UP\",\"B\"]\n\n[tool.pytest.ini_options]\naddopts = \"-q\"",
          },
          accent: "violet",
          aiPrompt: "Dark TOML config card, violet glow, 1:1",
          canvaBrief: "Dark gradient code window with TOML snippet. Headline. Footer.",
        },
      },
      {
        id: "d7-p4", day: 7, postNumber: 4, slot: "evening", type: "tip", pillar: "career",
        title: "How I avoid the 'tutorial trap'",
        copy: "There's a failure mode in self-taught learning so universal that it has earned a name — the tutorial trap. It works like this:\n\nWatch a course. Take notes. Feel productive. Don't write any code. Forget most of it within a week. Buy the next course. Watch. Take notes. Repeat.\n\nIf this sounds familiar, you're not alone. I lived in the tutorial trap for two years before I figured out the way out. The way out is uncomfortable but simple.\n\nMy rule, kept religiously now: every concept I read about, I build a 30-line repo about, by end of day.\n\nNot a polished project. Not a finished tutorial. A 30-line script in a public GitHub repo that demonstrates the concept, runs on my laptop, and proves to me that I understood it.\n\nLearned about embeddings? cosine_similarity_demo.py. Learned about decorators? timing_decorator.py. Learned about dataclasses? frozen_dataclass_demo.py. Each one ugly. Each one runs.\n\nThe point isn't the project quality. The point is the friction of moving from 'I read about this' to 'I implemented this'. The friction is the learning. You can't fake your way through a 30-line script the way you can fake your way through reading.\n\nAt the end of 90 days, I'll have 90+ tiny repos. Each takes 30-60 minutes to write. Most are scrappy. All run.\n\nTwo years from now, when I need to remember how decorators work, I'll grep my repos before I google. Reading my own past code is a compounding asset. Reading other people's tutorials isn't.\n\nFor every hour of theory, spend an hour shipping.",
        hashtags: [...CORE, "#LearningInPublic", "#GitHub"],
        image: {
          template: "tip",
          headline: "Tutorial → tiny repo → ship",
          subhead: "1 concept = 1 repo. Same day.",
          bullets: [
            "Read for 1 hour",
            "Code for 1 hour",
            "Push to GitHub",
            "Tweet/post the link",
          ],
          accent: "violet",
          aiPrompt: "Pro tip poster, GitHub-icon motif, violet header, 1:1",
          canvaBrief: "Violet gradient header with PRO TIP. White card with 4 steps. Footer.",
        },
      },
      {
        id: "d7-p5", day: 7, postNumber: 5, slot: "night", type: "recap", pillar: "career",
        title: "Week 1 done. 12 weeks to go.",
        copy: "End of week one. 35 posts. 7 days. Zero misses.\n\nThank you. Genuinely. To everyone who reposted, commented, or just hit save without saying anything — showing up for someone else's learning journey on the internet is one of the most generous, low-recognition things you can do, and it's why this format works at all.\n\nA few things I've noticed in the first week.\n\nThe pace is doable but tight. Five posts a day, written in advance the night before, takes about 90 minutes. The actual writing time isn't the constraint — the thinking-clearly-enough-to-write is. If a topic isn't clear in my head, the post takes three times longer.\n\nThe public commitment is doing what I hoped. There have been at least two days this week where, alone, I would have skimmed a topic. Knowing five posts had to ship made me actually understand. That's the whole game.\n\nThe response has been more generous than I expected. DMs from people starting their own sprints, comments correcting me where I was wrong (and right to do so), and quiet reposts that reach corners of the network I'd never reach myself. Keep it coming.\n\nWhat's next.\n\nWeek 2 starts tomorrow with Python OOP. By the end of week 2, you'll be able to read any open-source AI/ML codebase without flinching. Decorators, generators, context managers, type hints, dataclasses — the parts that show up in every framework and confuse most beginners.\n\nAfter week 2 we go DSA for two weeks (the foundation that ML interviews and elegant code share), then NumPy, Pandas, classical ML, deep learning, transformers, RAG, agents, automation, and a career-focused wrap.\n\nIf you're catching up, the full plan lives on my GitHub. Pinned, indexed, and updating daily.\n\nSee you tomorrow.",
        hashtags: [...CORE, "#90DaysOfAI", "#WeekRecap"],
        image: {
          template: "quote",
          headline: "1 week down. 12 to go.",
          subhead: "Week 2: OOP, decorators, generators, dataclasses.",
          accent: "violet",
          aiPrompt: "Pastel violet quote card with subtle progress bar 7/90, 1:1",
          canvaBrief: "Pastel gradient. Big quote. Italic subhead. Tiny progress bar 7/90 violet bar at bottom. Brand pill, footer.",
        },
      },
    ],
  },
];
