import type { DayPlan } from "../types";

const CORE = ["#NLP", "#Transformers", "#LLM", "#AI", "#100DaysOfCode"];

export const week08: DayPlan[] = [
  /* DAY 50 */
  {
    day: 50, theme: "Tokenisation — the unsung hero of NLP", pillar: "ai-ml",
    posts: [
      { id: "d50-p1", day: 50, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Tokens are not words",
        copy: "📅 Day 50. Halfway through the sprint. Welcome to NLP and transformers week.\n\n📝 Let's start with the layer no one talks about but everyone uses — tokenisation.\n\nA tokenizer turns text into a list of integer IDs that the model can process. Modern tokenizers (BPE, WordPiece, SentencePiece) split text into subword units, NOT whole words.\n\n🔤 Examples:\n→ 'tokenization' might be ['token', 'ization'] — two tokens.\n→ 'unbelievable' might be ['un', 'bel', 'ievable'] — three tokens.\n→ 'hello world' is usually ['hello', ' world'] (the leading space is part of the token).\n→ Numbers and punctuation each become tokens.\n→ Emojis often become 2-4 tokens because they're encoded in multi-byte Unicode.\n\n💰 Why this matters in practice — APIs charge by token, not by word.\n\nA 1000-word English blog post is roughly 1300 tokens. A 1000-character code snippet is roughly 250-400 tokens (code is denser). A page of dense math symbols is hundreds of tokens for a few lines.\n\nGPT-4-class models cost a few dollars per million tokens. For high-volume apps, token efficiency matters.\n\n🌐 Tokenization is also language-dependent. English averages ~1.3 tokens per word. Chinese, Japanese, Korean often hit 1-2 tokens per character (much higher per equivalent meaning). Multi-lingual apps need to budget for this.\n\n🎯 The takeaway:\n→ Tokens ≠ words. The mental model 'each word is one token' is wrong.\n→ Token counts are language-specific and content-specific.\n→ Always count tokens before sending to APIs to estimate cost and check context limits.\n\n💡 We'll write code to count tokens later in the day. For now — internalise that 'token' is the model's unit, not the human's.",
        hashtags: [...CORE, "#Tokenization"],
        image: { template: "stat", headline: "1 word ≈ 1.3 tokens", subhead: "BPE / WordPiece subword tokens", stat: { number: "1.3x", label: "tokens per English word, on average" }, accent: "violet", aiPrompt: "Stat poster with split-word glyph, 1:1", canvaBrief: "Violet gradient. Big 1.3x." }
      },
      { id: "d50-p2", day: 50, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "BPE in 4 sentences",
        copy: "🧮 Byte-Pair Encoding (BPE) is the most common subword tokenisation algorithm in 2026. The whole idea fits in four sentences.\n\n1️⃣ Start with the corpus split into characters. Each character is a token.\n\n2️⃣ Find the most-frequent adjacent pair of tokens. Merge them into a new combined token.\n\n3️⃣ Repeat the merge step until the vocabulary reaches the desired size (typically 32k-100k tokens for modern LLMs).\n\n4️⃣ The result — a vocabulary that covers common words as single tokens and rare words as combinations of subwords.\n\n🎯 Why BPE wins:\n\n→ No 'unknown word' problem. Any string is decomposable, even names you've never seen, even random gibberish, even other languages. The worst case is per-character tokenisation; never an outright failure.\n\n→ Frequent words stay efficient. 'the', 'and', 'is' are single tokens. Common bigrams like 'New York' might also be a single token if frequent enough in training.\n\n→ Rare words decompose meaningfully. 'unhappiness' might split as ['un', 'happiness'], retaining morphological information.\n\n→ Cross-language. A multilingual BPE trained on many languages handles all of them. The model implicitly learns shared subwords (Latin alphabet shows up in many languages).\n\n📦 Variants:\n→ WordPiece (BERT) — similar to BPE, slightly different merge criterion (likelihood-based, not frequency-based).\n→ SentencePiece (Llama, T5) — operates on raw bytes/Unicode, no whitespace pre-tokenisation. More language-agnostic.\n→ Byte-level BPE (GPT-2 onwards) — tokens are byte sequences. Handles any string at byte level. The standard in modern LLMs.\n\n🏆 GPT, Llama, Claude — all variants of BPE.\n\n💡 You don't usually train your own tokenizer. You use the pretrained one that came with your model. But understanding BPE makes you a better LLM user.",
        hashtags: [...CORE, "#BPE"],
        image: { template: "list", headline: "BPE — 4 facts",
          bullets: ["Start from characters", "Merge most-frequent pair", "Repeat until vocab full", "No unknown words ever"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d50-p3", day: 50, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Use a tokenizer in 3 lines (HuggingFace)",
        copy: "💻 transformers ships with the tokenizer for every modern LLM. Three lines from import to encoded text.\n\nLook at the snippet.\n\n📦 Line 1 — import AutoTokenizer.\n\n🔧 Line 2 — load by model name. AutoTokenizer.from_pretrained('gpt2'). Downloads the tokenizer (small, fast). Same API for every model — gpt2, llama-3, mistral, claude (via Anthropic SDK), gemini (via Google SDK).\n\n🔢 Line 3 — encode text into integer IDs. tok.encode('Saurav Danej · 90 days of AI/ML in public.') returns a list like [27817, 526, 65, ...].\n\n📝 Line 4 — decode IDs back to text. tok.decode(ids) returns the original string.\n\nFor production use, the typical call is:\n\nresult = tok(text, padding=True, truncation=True, return_tensors='pt')\n\nThis returns a dict with input_ids (the integer IDs), attention_mask (1 for real tokens, 0 for padding), and possibly token_type_ids for some models. Pad and truncate to a fixed length; convert to PyTorch tensors. Ready to feed into the model.\n\n🛠 Common kwargs:\n→ max_length=512 — truncate to this many tokens.\n→ padding='max_length' — pad to max_length.\n→ truncation=True — truncate longer inputs.\n→ return_tensors='pt' for PyTorch, 'tf' for TensorFlow.\n\n⚠️ Important — when fine-tuning a model, always save the tokenizer alongside it. The tokenizer must match the model exactly. Different tokenizers produce different IDs for the same text; the model only understands its own.\n\n💾 Save with tok.save_pretrained('my-model/'). Load alongside the model.\n\n💡 The HuggingFace tokenizer API is one of the cleanest in NLP. Three lines to encode anything. Use it.",
        hashtags: [...CORE, "#HuggingFace"],
        image: { template: "code", headline: "Tokenizer — 3 lines",
          code: { language: "python", snippet: "from transformers import AutoTokenizer\n\ntok = AutoTokenizer.from_pretrained('gpt2')\nids = tok.encode('Saurav Danej · 90 days of AI/ML in public.')\nprint(ids)\nprint(tok.decode(ids))\n\n# also: tok(text, padding=True, truncation=True, return_tensors='pt')" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d50-p4", day: 50, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Always check token counts before sending an API call",
        copy: "💡 Pro tip — count your tokens BEFORE sending to an LLM API. Two reasons: cost and context limits.\n\n💰 Cost. Major LLM APIs charge per token. GPT-4 class models are roughly $5-15 per million input tokens. For high-volume applications, token estimation is the difference between $50/month and $5000/month in production.\n\n🚧 Context limits. Every model has a maximum context (input + output) it can handle. GPT-4o is 128k tokens. Claude 3.5 Sonnet is 200k. Gemini Pro 2 is up to 2M. If you exceed the limit, the API returns an error — you won't get a partial response, you'll get rejected.\n\nAccidentally sending a 200k-token document to a 128k-token-limit model fails immediately. You discover this in production at 2am.\n\n🛠 The tools:\n\n→ tiktoken (OpenAI). pip install tiktoken. Then tokenizer = tiktoken.encoding_for_model('gpt-4o') and len(tokenizer.encode(text)) gives you the count. Fast — pure Rust under the hood.\n\n→ AutoTokenizer (HuggingFace). For open models. len(tok.encode(text)).\n\n→ anthropic.beta.messages.count_tokens — Anthropic's official token counter for Claude.\n\n→ Google's count_tokens method on the GenerativeModel object for Gemini.\n\n📋 Pre-flight check pattern:\n\ntoken_count = count_tokens(prompt)\nif token_count > MAX_TOKENS - response_buffer:\n    truncate_or_chunk(prompt)\nelse:\n    send_to_api(prompt)\n\n🎯 For RAG specifically — pre-flight checks save you from the 'I retrieved 20 chunks and the prompt is too big' bug. Truncate to the most-relevant N chunks before sending.\n\n💡 Tokens > characters > words for sizing prompts. Get the unit right. Estimate before you spend.",
        hashtags: [...CORE, "#LLM"],
        image: { template: "tip", headline: "Count tokens before you send",
          bullets: ["tiktoken (OpenAI)", "AutoTokenizer (HF)", "client.count_tokens (Anthropic)", "Budget by token, not char"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d50-p5", day: 50, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 50 — tokens decoded",
        copy: "📅 End of Day 50.\n\n✅ Recap:\n\n📝 Tokens are not words. BPE/WordPiece subword tokenisation gives ~1.3 tokens per English word. Languages and content type vary.\n\n🧮 BPE in 4 sentences. Start from characters; merge frequent pairs; repeat. Vocabulary size around 32k-100k for modern LLMs. No unknown words.\n\n💻 HuggingFace AutoTokenizer in 3 lines. Same API across all transformer models. Save the tokenizer alongside the model when fine-tuning.\n\n💰 Always count tokens before API calls. tiktoken for OpenAI, AutoTokenizer for open models, official counters for Anthropic and Google. Budget by token, not by character or word.\n\n🧠 Reflection — tokenisation is the most under-discussed part of LLM engineering. Token efficiency directly affects cost and latency. Understanding the model's actual unit (token, not word) makes everything downstream — context limits, API pricing, prompt design — clearer.\n\n🚀 Tomorrow, Day 51 — embeddings. Coordinates of meaning. The bridge from token IDs to dense vectors that capture semantic similarity. The MTEB leaderboard and how to pick an embedding model.\n\n💼 Halfway through the sprint. The next four weeks are the modern AI stack — NLP, transformers, RAG, agents.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Tokenization"],
        image: { template: "quote", headline: "Tokens are the unit. Not words.", subhead: "Budget. Truncate. Ship.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 51 */
  {
    day: 51, theme: "Word embeddings — meaning as a vector", pillar: "ai-ml",
    posts: [
      { id: "d51-p1", day: 51, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Embeddings are learned coordinates of meaning",
        copy: "📅 Day 51. Embeddings might be the most important concept in modern NLP. They turn discrete things (words, sentences, images, even users) into dense vectors where similar things have nearby vectors.\n\n🧭 An embedding is a function — input X (text, image, anything) → vector in some d-dimensional space. The function is learned from data. The space is shaped so that semantically similar inputs end up close together.\n\n🎯 Word2Vec (2013) famously demonstrated this with vector arithmetic:\n\nvector('king') - vector('man') + vector('woman') ≈ vector('queen')\n\nThe vector difference between 'king' and 'man' captures the concept of 'royalty without gender'. Add it to 'woman' → you get 'queen'. The embedding space encodes meaning structurally.\n\n🌍 Modern embeddings (OpenAI text-embedding-3, BAAI/bge, jina-embeddings, voyage-3) are trained on web-scale text with contrastive learning. They don't just map words; they map sentences, paragraphs, documents — entire chunks of meaning into single vectors.\n\n💡 Where embeddings power 2026 AI:\n\n→ Semantic search. Embed query and documents; return the most similar by cosine. Better than keyword search for natural-language queries.\n\n→ RAG retrieval. The R in RAG. Find relevant chunks for a question by embedding both and matching.\n\n→ Clustering and topic modelling. Embed documents; cluster the vectors; each cluster is a topic.\n\n→ Recommendation systems. Embed users and items; recommend items with vectors close to the user's.\n\n→ Anomaly detection. Embed events; outliers in embedding space are anomalies.\n\n📊 Cross-modal embeddings. CLIP embeds both images and text into the same space. Search for images using text queries. The bridge between modalities.\n\n🧠 If you understand embeddings, you understand half of LLM applications. Tomorrow we go into how to pick a model. Wednesday we put it into a RAG system.",
        hashtags: [...CORE, "#Embeddings"],
        image: { template: "stat", headline: "vec(king) - vec(man) + vec(woman) ≈ vec(queen)", subhead: "Meaning is a coordinate.", stat: { number: "≈", label: "the analogy that introduced the world to embeddings" }, accent: "cyan", aiPrompt: "Stat poster with vector-space glyph, cyan accent, 1:1", canvaBrief: "Cyan-violet gradient. Big ≈ symbol."
        }
      },
      { id: "d51-p2", day: 51, postNumber: 2, slot: "midday", type: "deepdive", pillar: "rag",
        title: "Pick an embedding model — 3 questions",
        copy: "🤔 Choosing the right embedding model matters more than people realise. The same downstream RAG/search system can have wildly different quality depending on the embedding model. Three questions guide the choice.\n\n💰 Question 1 — Cost vs control.\n\n→ API embeddings (OpenAI text-embedding-3-small, Voyage AI, Cohere). Pay per token. Fast. No infrastructure. Quality is consistently strong. Best for prototyping and low-volume production.\n\n→ Self-hosted embeddings (BAAI/bge, sentence-transformers). Free per inference (after compute cost). Requires GPU/CPU resources. Quality competitive with APIs for top models. Best for high-volume production or privacy-sensitive data.\n\nMy default — start with OpenAI text-embedding-3-small ($0.02/M tokens) for prototyping. Switch to bge-small or bge-m3 self-hosted when scale or privacy demands.\n\n📐 Question 2 — Dimension.\n\n→ 384 dim — bge-small. Fast retrieval, lower memory.\n→ 768 dim — bge-base, sentence-transformers. Good balance.\n→ 1024 dim — bge-large, voyage-3.\n→ 1536 dim — OpenAI text-embedding-3-small (default).\n→ 3072 dim — OpenAI text-embedding-3-large, optional dimensions.\n\nHigher dim = more nuance + more memory + slower retrieval. For most retrieval tasks, 768-1024 is the sweet spot. Higher only helps when the data is genuinely complex.\n\nNote: text-embedding-3 supports 'matryoshka' embeddings — train at high dim, truncate to lower dim at inference. Best of both worlds.\n\n🎯 Question 3 — Domain.\n\n→ General-purpose models for most cases.\n→ Code-specific models (voyage-code-3) for codebases.\n→ Multilingual models (bge-m3, jina-embeddings-v3) for non-English data.\n→ Domain-specific (biomedical, legal) for niche content.\n\n📋 The rule — always evaluate on YOUR data, not benchmark scores. A 'top MTEB' model might lose to a smaller model on your specific corpus. Build a 30-pair eval set; test 3 candidates; pick the winner.",
        hashtags: [...CORE, "#Embeddings"],
        image: { template: "list", headline: "Pick an embedding model — 3 questions",
          bullets: ["Cost — local vs API", "Dim — 768 to 1536 typical", "Domain — general or specific", "Test on your data"],
          accent: "cyan", aiPrompt: "List card, cyan, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d51-p3", day: 51, postNumber: 3, slot: "afternoon", type: "code", pillar: "rag",
        title: "Local embeddings with sentence-transformers",
        copy: "💻 Free, runs on CPU or GPU, 5 lines from import to embedding. The fastest path to a working embedding setup for prototyping or self-hosted production.\n\nLook at the snippet.\n\n📦 Import sentence_transformers. The library is the easiest way to use BAAI/bge, sentence-transformers' own models, mxbai, and many others through a single API.\n\n🔧 Load model. SentenceTransformer('BAAI/bge-small-en-v1.5'). Downloads from HuggingFace on first use. Subsequently cached locally.\n\nThe 'small' in the name means 384 dim. The 'large' variants (bge-large-en-v1.5) are 1024 dim. The trade-off is quality vs speed/memory.\n\n📝 Define documents. A list of strings.\n\n🔢 Encode. model.encode(docs, normalize_embeddings=True) returns a NumPy array of shape (n, dim). normalize_embeddings=True scales each vector to unit length, which makes cosine similarity equivalent to dot product downstream — saves a normalisation step at retrieval time.\n\n📊 print(vecs.shape) confirms the result. (2, 384) means 2 documents, 384-dimensional each.\n\n🚀 Now you can:\n→ Compute similarity — np.dot(vec_a, vec_b) gives cosine similarity (because vectors are normalised).\n→ Find nearest — sort by similarity, pick top-k.\n→ Cluster — pass vectors to KMeans.\n→ Persist — save to a vector database like Qdrant.\n\n📋 For batch processing — pass a list of strings. The library batches internally for GPU efficiency. For 100k documents, this typically takes 30-60 seconds on a modest GPU.\n\n💡 Performance tips:\n→ Use a GPU if available. CPU is fine for prototyping (a few documents per second); GPU is needed for production scale.\n→ Set show_progress_bar=False to suppress the progress bar in scripts.\n→ For very long documents, the model truncates at its max sequence length (typically 512 tokens). Chunk before embedding for long docs.",
        hashtags: [...CORE, "#sentencetransformers"],
        image: { template: "code", headline: "Embed any text in 5 lines",
          code: { language: "python", snippet: "from sentence_transformers import SentenceTransformer\n\nmodel = SentenceTransformer('BAAI/bge-small-en-v1.5')\ndocs = [\n    'Embeddings are coordinates of meaning.',\n    'A vector database stores these coordinates.',\n]\nvecs = model.encode(docs, normalize_embeddings=True)\nprint(vecs.shape)   # (2, 384)" },
          accent: "cyan", aiPrompt: "Dark code card, cyan, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d51-p4", day: 51, postNumber: 4, slot: "evening", type: "tip", pillar: "rag",
        title: "Always normalise embeddings before cosine similarity",
        copy: "💡 Pro tip — embeddings should be unit-normalised before you do cosine similarity or store in a vector DB. Otherwise you have subtle bugs.\n\n🧮 The math. Cosine similarity between vectors a and b is (a · b) / (||a|| * ||b||). The dot product divided by the product of magnitudes.\n\nIf both vectors are unit-normalised (||a|| = ||b|| = 1), the formula simplifies to just (a · b). Cosine = dot product. Saves a normalisation step at every comparison.\n\n📊 If they're NOT normalised:\n→ The cosine formula computes the right answer, but slowly (every comparison divides by the product of norms).\n→ ANN libraries (Faiss, ScaNN) often assume unit norms. Without normalisation, they return the wrong neighbours.\n→ Some vector DBs (Qdrant with COSINE distance) handle non-normalised inputs correctly. Others assume normalisation. Read your DB's docs.\n→ Comparing similarity scores across different documents is harder when norms vary.\n\n✅ The fix — normalise once, at encode time, before storage:\n\nv = v / np.linalg.norm(v, axis=-1, keepdims=True)\n\nNumPy does this in one line. After this, every comparison is just dot product (or matrix multiplication for batches), which is much faster.\n\n📦 Most modern embedding APIs return normalised vectors by default — OpenAI text-embedding-3, voyage, jina. Some don't (some sentence-transformers models). Always check.\n\nFor sentence-transformers — pass normalize_embeddings=True to model.encode(). The flag is right there in the API.\n\nFor custom models — add the normalisation as a post-processing step in your encoding pipeline.\n\n🎯 The cost — one line of code per encode call. The savings — correct retrieval, faster comparisons, compatible with all vector DBs.\n\n💡 Always normalise. The bug from skipping is silent and ranking-distorting.",
        hashtags: [...CORE, "#Embeddings"],
        image: { template: "tip", headline: "Normalise before cosine",
          bullets: ["v / |v|", "Cosine == dot when normalised", "Most ANN indices assume it", "Subtle bugs without it"],
          accent: "cyan", aiPrompt: "Pro tip card, cyan, 1:1", canvaBrief: "Cyan header. PRO TIP."
        }
      },
      { id: "d51-p5", day: 51, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 51 — meaning as coordinates",
        copy: "📅 End of Day 51.\n\n✅ Recap:\n\n🧭 Embeddings = learned coordinates of meaning. Vector arithmetic captures relationships. Modern embeddings power semantic search, RAG, recommendation, anomaly detection.\n\n🤔 Pick by 3 questions — cost (API vs self-hosted), dim (768-1024 sweet spot), domain (general vs specific). Always evaluate on YOUR data.\n\n💻 5-line local embedding with sentence-transformers + bge-small. Free, runs on CPU/GPU.\n\n📐 Always normalise before cosine. Saves a step at every comparison; required by most ANN libraries; eliminates a class of subtle ranking bugs.\n\n🧠 Reflection — embeddings are the underrated workhorse of modern AI. Every search bar that 'just understands what you meant' is using embeddings. Every recommendation system that 'gets your taste' is using embeddings. The technique itself is decades old (latent semantic analysis from the 90s); the modern realisation (contrastive learning + transformers) is what made them dominant.\n\n🚀 Tomorrow, Day 52 — attention. Q, K, V — the three letters behind every transformer. The mechanism that ate ML.\n\n💼 We're building toward transformers (Day 53), then BERT/GPT (54-55), then RAG (week 9). Each day builds on the last; you'll see the pattern.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Embeddings"],
        image: { template: "quote", headline: "Meaning is a coordinate.", subhead: "Embeddings made it computable.", accent: "cyan", aiPrompt: "Pastel cyan quote, 1:1", canvaBrief: "Pastel cyan quote card." }
      },
    ]
  },
  /* DAY 52 */
  {
    day: 52, theme: "Attention — the mechanism that ate ML", pillar: "ai-ml",
    posts: [
      { id: "d52-p1", day: 52, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Attention in three letters: Q, K, V",
        copy: "📅 Day 52. Attention is the most important architectural innovation in deep learning since the convolution. Once you grok Q, K, V, every transformer becomes readable.\n\n🎯 The intuition. For each token in a sequence, attention asks — 'which other tokens should I pay attention to, and how much?'\n\nIt has three vectors per token, each derived from the input via a linear projection:\n\n→ Q (query) — what am I looking for? \n\n→ K (key) — what do I offer?\n\n→ V (value) — what information do I carry?\n\n🧮 The mechanics — for each query, dot it with every key. The result is a similarity score — how much should this token attend to that token? Apply softmax to turn scores into weights (sum to 1). Take a weighted sum of all the value vectors using these weights.\n\nFormula — Attention(Q, K, V) = softmax(QKᵀ / √d) · V. The √d in the denominator scales the dot products to prevent the softmax from saturating.\n\n📊 Result — each token gets a context-aware representation that mixes information from all relevant tokens. The representation depends on what's around the token. The same word in different contexts gets different representations. This is the secret behind transformers' contextual understanding.\n\n⚡ The 'in parallel' part is what made transformers replace RNNs. RNNs process tokens one at a time. Attention processes ALL token pairs at once, in a single matrix multiplication. GPU-friendly; massively parallelisable.\n\n🌐 Same operation in vision (Vision Transformers split images into patches; each patch is a 'token'), audio (Whisper), code (Codex), proteins (AlphaFold). The Q-K-V mechanism is universal.\n\n💡 Three letters. The foundation of everything. Internalise once.",
        hashtags: [...CORE, "#Attention"],
        image: { template: "stat", headline: "softmax(QKᵀ/√d) · V", subhead: "Attention in one formula", stat: { number: "QKV", label: "three vectors per token, mix to produce context" }, accent: "violet", aiPrompt: "Stat poster with attention diagram, 1:1", canvaBrief: "Violet gradient. Big QKV."
        }
      },
      { id: "d52-p2", day: 52, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Multi-head attention — parallel perspectives",
        copy: "🧠 One attention head can only learn one type of pattern. Multi-head attention runs multiple attention computations in parallel, each free to specialise.\n\n📊 The mechanics — split Q, K, V into h chunks (h = number of heads, typically 8-96). Compute attention independently in each chunk. Concatenate the outputs and project back to the original dimension.\n\nIf the model dim is 768 and you have 12 heads, each head operates on 64-dim Q, K, V. Lower dim per head; more heads in parallel.\n\n🎯 Why this works:\n\n→ Each head learns a different relationship pattern. Some heads focus on syntactic relationships (subject-verb agreement). Others on semantic similarity. Others on long-range dependencies (matching opening and closing parens). The diversity emerges from training; you don't program it.\n\n→ More expressive than a single head with the same parameter count. The split-then-concatenate structure adds capacity.\n\n→ Stays parallelisable. Each head is independent; computed in parallel.\n\n📈 Modern model head counts:\n→ BERT-base: 12 heads.\n→ GPT-3 175B: 96 heads.\n→ LLama-3-70B: 64 heads.\n→ Most small models: 8-16 heads.\n\nMore heads doesn't always mean more performance. Past a point (typically 64), additional heads add parameters without improving quality. Training on more data is usually a better investment.\n\n🛠 In PyTorch — nn.MultiheadAttention(embed_dim=768, num_heads=12). One line. Handles the split, attention computation, concatenation, and output projection.\n\n💡 You almost never set num_heads by hand for new architectures. Use the defaults from a published architecture. The 'right' number was found empirically and tweaking rarely improves things.",
        hashtags: [...CORE, "#MultiHeadAttention"],
        image: { template: "list", headline: "Why multi-head attention works",
          bullets: ["Each head learns a different pattern", "Parallel — same compute, more capacity", "8-96 heads typical", "Defaults are usually right"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d52-p3", day: 52, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Self-attention in 14 lines",
        copy: "💻 Strip away every transformer paper. Self-attention is matmul + softmax + matmul. The hardest part is keeping shapes straight.\n\nLook at the snippet. We implement single-head self-attention from scratch. No multi-head, no masks, no projections — just the bare math to make the operation transparent.\n\n📐 Inputs and shapes:\n→ X is the input. Shape (B, T, D) — batch size, sequence length, hidden dim.\n→ Wq, Wk, Wv are weight matrices, each (D, D). They project X into Q, K, V.\n\n🧮 Compute Q, K, V:\n→ Q = X @ Wq. Shape (B, T, D).\n→ K = X @ Wk. Shape (B, T, D).\n→ V = X @ Wv. Shape (B, T, D).\n\n🎯 Compute attention scores:\n→ Q @ K.transpose(-2, -1). Shape (B, T, T). For each query position, gives a row of similarity scores against every key position.\n→ Divide by sqrt(d). Scaling factor that keeps softmax inputs in a reasonable range. Without it, large d would saturate the softmax.\n\n📊 Softmax:\n→ F.softmax(scores, dim=-1). Each row of scores becomes a probability distribution that sums to 1. These are the attention weights.\n\n🔄 Aggregate:\n→ weights @ V. For each query position, take a weighted sum of all value vectors. Shape (B, T, D).\n\nThe output is the same shape as the input — (B, T, D). Each position is a context-aware representation.\n\n💡 Read this 14-line implementation once. The wrapped versions in PyTorch (nn.MultiheadAttention) and HuggingFace (transformers' attention layers) all do this exact computation, plus multi-head and masking. The core math is what's here.\n\n🚀 You've now seen attention from first principles.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Self-attention — bare math",
          code: { language: "python", snippet: "import torch\nimport torch.nn.functional as F\n\ndef self_attention(X, Wq, Wk, Wv):\n    # X: (B, T, D)\n    Q = X @ Wq    # (B, T, D)\n    K = X @ Wk\n    V = X @ Wv\n    d = Q.size(-1)\n    scores = Q @ K.transpose(-2, -1) / d ** 0.5   # (B, T, T)\n    weights = F.softmax(scores, dim=-1)\n    return weights @ V                              # (B, T, D)" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d52-p4", day: 52, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Use F.scaled_dot_product_attention",
        copy: "💡 Pro tip for PyTorch 2.0+ — use F.scaled_dot_product_attention. It dispatches to FlashAttention on supported GPUs. Faster, less memory, exact same math.\n\n⚡ FlashAttention. A 2022 algorithm that computes attention in a memory-efficient way. Doesn't materialise the full attention matrix (which is O(T²) memory for sequence length T). Instead, it computes attention in tiles, using the GPU's fast on-chip SRAM.\n\nReal numbers — for sequence length 4096:\n→ Naive attention — minutes per training step. Often runs out of memory.\n→ FlashAttention — seconds per step. Memory bounded by sequence length, not its square.\n\nThis isn't a quality difference; it's an efficiency difference. The output is mathematically identical.\n\n🛠 The simplest way to get it — use PyTorch's built-in.\n\nimport torch.nn.functional as F\n\nout = F.scaled_dot_product_attention(\n    Q, K, V,\n    attn_mask=mask,\n    is_causal=True,  # for decoder-only models\n)\n\nThe function checks the GPU and dispatches to FlashAttention if supported (Ampere or newer). Falls back to standard attention otherwise.\n\nis_causal=True applies the causal mask automatically — each position can only attend to itself and earlier positions. Used in decoder LLMs (GPT-style).\n\n📊 Speedup vs naive attention on long sequences (T=4096+):\n→ 2-4x faster.\n→ Memory drops from O(T²) to O(T).\n→ Enables training on longer contexts than otherwise possible.\n\n🚨 Common mistake. People still write the manual self_attention from yesterday's snippet in production code in 2026. That code is fine for understanding; not for production. Use the built-in.\n\n💡 Don't roll your own attention math. Use F.scaled_dot_product_attention. Half a billion lines of tutorials are doing it the slow way.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "tip", headline: "Use scaled_dot_product_attention",
          bullets: ["PyTorch 2.0+", "Dispatches to FlashAttention", "is_causal=True for decoders", "2-4x faster, no math errors"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d52-p5", day: 52, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 52 — attention, framed cleanly",
        copy: "📅 End of Day 52.\n\n✅ Recap:\n\n🎯 QKV in 3 letters. Query asks; Key answers; Value carries the info. softmax(QKᵀ/√d) · V is the formula.\n\n🧠 Multi-head attention — parallel perspectives. h heads, each on D/h dim, concatenated. Each head learns different patterns. 8-96 heads typical.\n\n💻 14-line self-attention from scratch. The clearest way to understand the math. Production code uses framework versions.\n\n⚡ F.scaled_dot_product_attention. PyTorch's built-in dispatches to FlashAttention. 2-4x faster, exact same math. Use it.\n\n🧠 Reflection — attention is the mechanism that scaled. Convolutions worked great for vision but had limited reach. Attention works for sequences of any length, in any modality. The 2017 'Attention Is All You Need' paper started a chain reaction that produced GPT, BERT, Claude, every modern AI system. Worth understanding deeply.\n\n🚀 Tomorrow, Day 53 — the full transformer block. Attention + MLP + LayerNorm + residual. The Lego brick that stacks to billions of parameters. The encoder vs decoder distinction. The 'don't write your own transformer' wisdom.\n\n💼 Week 8 is past halfway. Then RAG (week 9-10) builds on top of all this.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Attention"],
        image: { template: "quote", headline: "Attention is QKV.", subhead: "Everything else is plumbing.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel violet quote card." }
      },
    ]
  },
  /* DAY 53 */
  {
    day: 53, theme: "Transformer block — the architectural Lego", pillar: "ai-ml",
    posts: [
      { id: "d53-p1", day: 53, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "A transformer block is two sublayers",
        copy: "📅 Day 53. The transformer block — the Lego brick that stacks to build every modern LLM.\n\n🏗 The block has two sublayers. Each sublayer is wrapped in a 'pre-norm + residual' pattern.\n\n📐 Sublayer 1 — Multi-head attention.\n→ LayerNorm the input.\n→ Multi-head attention on the normalised input.\n→ Add the result back to the original input (residual connection).\n\n📐 Sublayer 2 — MLP (feed-forward).\n→ LayerNorm the result of sublayer 1.\n→ Two linear layers with GELU in between (typically inner dim is 4x outer dim).\n→ Add the result back (residual connection).\n\nThat's it. One block has these two sublayers. Stack 12, 24, 48, 96 of them, add an embedding layer at the bottom and an output head at the top, and you have GPT, Llama, BERT, Claude.\n\n🌐 Same skeleton; different scales:\n→ BERT-base — 12 blocks, hidden dim 768. ~110M parameters.\n→ GPT-3 — 96 blocks, hidden dim 12288. 175B parameters.\n→ Llama-3-8B — 32 blocks, hidden dim 4096. 8B parameters.\n→ Llama-3-405B — 126 blocks, hidden dim 16384. 405B parameters.\n\n🧠 The two simple sublayers, plus residual connections and layer normalisation, are what make 100B-parameter models trainable. Residuals carry gradient through deep stacks; LayerNorm keeps activation magnitudes stable.\n\n🔧 Modern variations (post-2020):\n→ RMSNorm replaces LayerNorm. Simpler, slightly faster, same effect.\n→ SwiGLU replaces standard MLP. Slightly more parameters, better performance.\n→ Rotary positional encodings (RoPE) replace absolute position embeddings. Better extrapolation to longer sequences.\n→ Grouped-query attention (GQA) reduces inference memory. Used in Llama-2/3.\n\nAll these are optimisations on the same core block. The 2017 design holds.\n\n💡 Master the block. Stack to taste.",
        hashtags: [...CORE, "#Transformers"],
        image: { template: "stat", headline: "1 block = attention + MLP", subhead: "Stack to depth. Add data.", stat: { number: "2", label: "sublayers per transformer block" }, accent: "violet", aiPrompt: "Stat poster with stacked-block glyph, 1:1", canvaBrief: "Violet gradient. Big 2."
        }
      },
      { id: "d53-p2", day: 53, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Encoder vs decoder — same block, different mask",
        copy: "🤔 Same transformer block. Different attention mask. Different model.\n\n👁 Encoder (BERT, RoBERTa, DistilBERT) — bidirectional attention. Each token can attend to ALL positions, including future ones. Good for understanding tasks where the whole input is available — classification, NER, embedding.\n\n🎯 Decoder (GPT, Llama, Claude) — causal (autoregressive) attention. Each token can attend ONLY to itself and earlier positions. Good for generation — predict the next token given everything so far.\n\nThe attention mask is what enforces this. In decoder, mask out the upper triangle of the attention matrix (so position i can't see position j > i).\n\n🔄 Encoder-decoder (T5, BART, the original 'Attention Is All You Need' transformer) — encoder reads input; decoder generates output, cross-attending to the encoder's output. Used for sequence-to-sequence tasks like translation and summarisation.\n\n📊 Where each shines:\n\n👁 Encoder for:\n→ Embeddings (sentence-transformers, BAAI/bge use encoder-only).\n→ Classification (BERT for sentiment, intent, topic).\n→ NER, QA, similarity.\n\n🎯 Decoder for:\n→ Text generation (chat, completion, code).\n→ Question answering with reasoning.\n→ All major LLMs in 2026 are decoder-only.\n\n🔄 Encoder-decoder for:\n→ Translation (T5, mBART).\n→ Summarisation (BART, T5).\n→ Some niche seq2seq tasks.\n\n💡 In 2026, the trend is decoder-only for almost everything generative. ChatGPT, Claude, Llama, Gemini — all decoder-only. The encoder-decoder distinction matters less than it used to; you can do almost any task with a decoder by clever prompting.\n\n🎯 But for embeddings and dense retrieval, encoder models still dominate. BAAI/bge, sentence-transformers, Jina embeddings — all encoder-only. They're better suited for the bidirectional understanding that retrieval needs.",
        hashtags: [...CORE, "#Transformers"],
        image: { template: "compare", headline: "Encoder vs Decoder",
          compare: { leftLabel: "Encoder (BERT)", leftItems: ["Bidirectional attn", "Understanding", "Embeddings", "Classification"], rightLabel: "Decoder (GPT)", rightItems: ["Causal attn", "Generation", "Chat / completion", "All major LLMs"] },
          accent: "violet", aiPrompt: "Compare poster, 1:1", canvaBrief: "Split. Grey vs violet."
        }
      },
      { id: "d53-p3", day: 53, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "A transformer block in PyTorch (compact)",
        copy: "💻 The transformer block in PyTorch. Pre-LN style (norm before each sublayer) — the modern default.\n\nLook at the snippet.\n\n🏗 Block class:\n→ self.ln1 = nn.LayerNorm(d) — first LayerNorm.\n→ self.attn = nn.MultiheadAttention(d, h, batch_first=True) — multi-head attention.\n→ self.ln2 = nn.LayerNorm(d) — second LayerNorm.\n→ self.mlp = nn.Sequential(nn.Linear(d, 4*d), nn.GELU(), nn.Linear(4*d, d)) — feedforward MLP.\n\n🔄 forward(x, mask=None):\n→ a, _ = self.attn(self.ln1(x), self.ln1(x), self.ln1(x), attn_mask=mask). Apply LayerNorm, then attention. We pass the same input as Q, K, V (this is self-attention).\n→ x = x + a. Add the attention output to the original input (residual connection).\n→ x = x + self.mlp(self.ln2(x)). Apply LayerNorm, MLP, residual.\n→ Return x.\n\n📊 The shape stays (B, T, D) throughout. No dimension changes inside a block.\n\n💡 Pre-LN vs post-LN. The original Transformer (2017) used post-LN — applied LayerNorm AFTER the sublayer + residual. Pre-LN (LayerNorm BEFORE the sublayer) was found to train more stably with deeper models. All modern transformers use pre-LN.\n\n🧠 The MLP details:\n→ Inner dimension 4x outer (d → 4d → d). Standard since the original paper.\n→ GELU activation. ReLU also works; GELU is smoother and slightly better.\n→ Some modern models use SwiGLU instead of GELU (Llama, Mistral). Slightly more compute, slightly better quality.\n\n🚀 This is the core block. Stack N of them. Add an embedding layer below. Add a language modeling head above. You have a transformer.\n\n💡 You'll never write this from scratch in production. But understanding the structure makes every transformer paper readable.",
        hashtags: [...CORE, "#PyTorch"],
        image: { template: "code", headline: "Transformer block — pre-LN",
          code: { language: "python", snippet: "import torch.nn as nn\n\nclass Block(nn.Module):\n    def __init__(self, d, h):\n        super().__init__()\n        self.ln1 = nn.LayerNorm(d)\n        self.attn = nn.MultiheadAttention(d, h, batch_first=True)\n        self.ln2 = nn.LayerNorm(d)\n        self.mlp = nn.Sequential(\n            nn.Linear(d, 4*d), nn.GELU(), nn.Linear(4*d, d)\n        )\n    def forward(self, x, mask=None):\n        a, _ = self.attn(self.ln1(x), self.ln1(x), self.ln1(x), attn_mask=mask)\n        x = x + a\n        x = x + self.mlp(self.ln2(x))\n        return x" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d53-p4", day: 53, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Don't write your own transformer in 2026",
        copy: "💡 Pro tip — writing your own transformer is a great learning exercise. It's a terrible production choice.\n\n🚨 Why? Because the production transformer ecosystem in 2026 is mature, optimised, and battle-tested. Hand-rolling means you reinvent — usually with bugs and worse performance.\n\n📦 Use these instead:\n\n🤗 HuggingFace transformers. The de facto standard for transformer fine-tuning, inference, and most training. Supports thousands of pretrained models, all major architectures, multiple training paradigms (causal LM, masked LM, sequence classification).\n\n⚡ vLLM. Best in class for inference serving. Paged attention, continuous batching, OpenAI-compatible API. 10-30x throughput vs naive .generate(). Used in production at many AI companies.\n\n💨 TGI (Text Generation Inference). HuggingFace's inference server. Similar performance to vLLM with deeper HF integration.\n\n💻 llama.cpp. C++ implementation for local inference. GGUF quantised models run on CPU and consumer GPUs. Best for laptops, edge devices, and resource-constrained environments.\n\n🛠 TRL / Axolotl / unsloth. For fine-tuning. SFT, DPO, RLHF — all the modern training paradigms. Configure with YAML; train with one command.\n\n📚 PEFT (parameter-efficient fine-tuning). LoRA, QLoRA, prefix tuning. Fine-tune big models on consumer GPUs.\n\n🎯 What you save by using these:\n\n→ Hardened bugs. Years of issue reports have been fixed in the public libraries.\n→ Performance. FlashAttention, kernel fusions, quantisation — all integrated.\n→ Compatibility. Read any HuggingFace model; share your fine-tuned model on the hub.\n→ Speed of iteration. Hours, not weeks.\n\n💡 Learn the architecture. Use the libraries. Save your time for the parts that matter — data, evaluation, prompts, your specific application logic.\n\n🚀 Don't reinvent. Compose.",
        hashtags: [...CORE, "#MLEngineering"],
        image: { template: "tip", headline: "Don't roll your own transformer",
          bullets: ["HF transformers — training", "vLLM / TGI — inference", "Axolotl — fine-tune", "Llama.cpp — local"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d53-p5", day: 53, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 53 — the block that ate ML",
        copy: "📅 End of Day 53.\n\n✅ Recap:\n\n🏗 Transformer block = LayerNorm + Attention + Residual + LayerNorm + MLP + Residual. Two sublayers per block. Stack to depth.\n\n👁🎯 Encoder vs decoder = mask choice. Encoder is bidirectional (BERT). Decoder is causal (GPT). Encoder-decoder for seq2seq (T5).\n\n💻 Pre-LN block in PyTorch. Compact implementation. Modern default.\n\n📦 Don't write your own transformer in 2026. Use HF transformers for training, vLLM for inference, llama.cpp for local. The ecosystem is mature.\n\n🧠 Reflection — the transformer block is one of the most consequential designs in computing history. It powers GPT-4, Claude, Llama, Gemini, every AI assistant you've used. The architecture has barely changed since 2017; what changed is scale (more parameters, more data, more training compute) and engineering (FlashAttention, mixed precision, distributed training). The lesson — small architectural ideas with massive impact when scaled.\n\n🚀 Tomorrow, Day 54 — BERT and the encoder family. Why they still matter for embeddings and small-data classification. The DistilBERT trick for production. Then Friday: GPT-style decoders. Saturday: fine-tune vs prompt vs RAG.\n\n💼 Three days left in week 8. Then RAG, agents, automation, career. The home stretch is more about applications than fundamentals.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#Transformers"],
        image: { template: "quote", headline: "One block. Stacked deep. Run on data.", subhead: "All of modern AI.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel violet quote card." }
      },
    ]
  },
  /* DAY 54 */
  {
    day: 54, theme: "BERT — encoders that still matter", pillar: "ai-ml",
    posts: [
      { id: "d54-p1", day: 54, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "BERT — bidirectional, pre-trained, fine-tuned",
        copy: "📅 Day 54. BERT was the first transformer to dominate NLP benchmarks. Released in 2018; still in active production use seven years later.\n\n🎯 Two ideas made BERT work:\n\n1️⃣ Bidirectional attention. Unlike GPT (which only sees past tokens), BERT sees the entire input both ways. Each token's representation is informed by tokens before AND after it. Useful for understanding tasks where the whole context is available.\n\n2️⃣ Masked language modeling (MLM) pretraining. Take a sentence, randomly mask 15% of tokens, train the model to predict the masked tokens. The model learns rich contextual representations from massive unlabeled text.\n\n📚 BERT was pretrained on Wikipedia + BooksCorpus (~16GB of text). After pretraining, fine-tune for any downstream task — classification, NER, QA, similarity.\n\nFine-tuning costs are low — a few hours on a single GPU for most tasks. The 'transfer learning' from pretraining provides 90% of the value; fine-tuning specialises the last 10%.\n\n🌐 In 2026, BERT-class models dominate:\n\n→ Sentence embeddings. sentence-transformers, BAAI/bge, Jina embeddings — all BERT-family architectures.\n\n→ Retrieval for RAG. The 'R' in RAG uses encoder embeddings. BERT and descendants.\n\n→ Small-data classification. Fine-tune BERT on 1000 labeled examples; often beats a hand-crafted feature pipeline.\n\n→ Named entity recognition (NER), token classification, sentence-pair tasks.\n\n💡 GPT-style models excel at generation; BERT-style at understanding. Both are transformers; the architectural difference is the attention mask. The right choice depends on whether you're producing text or understanding it.\n\n🚀 BERT's descendants — RoBERTa (better training), DistilBERT (smaller, faster), DeBERTa (improved attention), MPNet — push the original further. All share the bidirectional encoder design.",
        hashtags: [...CORE, "#BERT"],
        image: { template: "stat", headline: "MLM + NSP", subhead: "BERT's pretraining recipe", stat: { number: "15%", label: "of tokens masked during BERT pretraining" }, accent: "violet", aiPrompt: "Stat poster, 1:1", canvaBrief: "Violet gradient. Big 15%."
        }
      },
      { id: "d54-p2", day: 54, postNumber: 2, slot: "midday", type: "deepdive", pillar: "rag",
        title: "When to use BERT (or its descendants) in 2026",
        copy: "🤔 LLMs (GPT, Claude, Llama) can do most NLP tasks now. So when is BERT-family still the right choice in 2026?\n\n✅ Use encoder models when you need:\n\n📐 Sentence/document embeddings. For semantic search, RAG, similarity computations. Sentence-transformers and BAAI/bge are BERT-family. Faster, smaller, more cost-effective than running a large LLM for each embedding.\n\n📊 Small-data classification. If you have 1000 labeled examples for a classification task, fine-tuning BERT typically beats few-shot prompting an LLM. The fine-tuned BERT is also faster at inference and easier to deploy.\n\n🏷 NER and information extraction. Token-level tasks like 'find all person names' or 'extract dates'. Encoder models with token classification heads are the standard.\n\n🔍 Retrieval inside RAG. Both as embedders (encode docs into vectors) and as cross-encoder rerankers (score query-doc pairs).\n\n❌ DON'T use encoders when you need:\n\n📝 Open-ended generation. BERT can't generate text. Use a decoder LLM.\n\n💬 Multi-turn chat. Encoders aren't designed for stateful conversation.\n\n🧠 Long-form reasoning, math, code. Decoders win at multi-step reasoning.\n\n🎯 Few-shot or zero-shot tasks where you can't fine-tune.\n\n💰 Cost comparison:\n\n→ Embedding 1M docs with BAAI/bge-small (encoder) — minutes on a GPU, free.\n\n→ Embedding 1M docs with OpenAI text-embedding-3-small (encoder via API) — $20.\n\n→ Generating answers for 1M queries with a fine-tuned BERT classifier — minutes, runs anywhere.\n\n→ Generating answers for 1M queries with GPT-4 — $1000s, slower, requires API.\n\nFor classification + retrieval, encoder + classical model is dramatically cheaper and faster. Use the right tool.\n\n💡 Encoders are not legacy. They're the right choice for retrieval and small-data classification.",
        hashtags: [...CORE, "#NLP"],
        image: { template: "list", headline: "BERT — when to reach for it",
          bullets: ["Embeddings", "Small-data classification", "NER / extraction", "Retrieval / RAG ranking"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d54-p3", day: 54, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Fine-tune BERT for classification in 20 lines",
        copy: "💻 HuggingFace Trainer makes BERT fine-tuning trivial. Twenty lines from import to trained model.\n\nLook at the snippet.\n\n📦 Imports — AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments. The 'Auto' classes pick the right architecture based on the model name.\n\n🔧 Load:\n→ tok = AutoTokenizer.from_pretrained('bert-base-uncased'). Standard BERT tokenizer.\n→ model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2). Loads BERT with a fresh classification head (2 output classes for binary classification).\n\n🔄 Tokenize:\n→ Define a tokenize function that takes a batch and returns token IDs.\n→ ds = ds.map(tokenize, batched=True). Apply to the dataset (assumed to be a HuggingFace Datasets object).\n\n⚙️ Training arguments:\n→ output_dir='out' — where to save checkpoints.\n→ per_device_train_batch_size=16 — fits on most GPUs for BERT-base.\n→ num_train_epochs=2 — usually enough for BERT fine-tuning.\n\n🚀 Train:\n→ Trainer(model=model, args=args, train_dataset=ds['train'], eval_dataset=ds['val']).train().\n\nOne line of training. Trainer handles AMP, gradient accumulation, evaluation, checkpointing, logging — all by default.\n\n📊 Inference after training:\n→ outputs = model(**tok('your text', return_tensors='pt'))\n→ predictions = outputs.logits.argmax(dim=-1)\n\nOr use the pipeline API for simpler inference:\n→ from transformers import pipeline\n→ classifier = pipeline('text-classification', model='./out')\n→ classifier('your text')\n\n💡 Twenty lines covers the entire fine-tuning workflow for binary classification. For multi-class, change num_labels. For multi-label, use AutoModelForSequenceClassification with problem_type='multi_label_classification'. For NER, use AutoModelForTokenClassification.\n\n🚀 Trainer is the modern standard for most fine-tuning. Learn it once; use it forever.",
        hashtags: [...CORE, "#HuggingFace"],
        image: { template: "code", headline: "Fine-tune BERT — minimum viable",
          code: { language: "python", snippet: "from transformers import (\n    AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments\n)\n\ntok = AutoTokenizer.from_pretrained('bert-base-uncased')\nmodel = AutoModelForSequenceClassification.from_pretrained(\n    'bert-base-uncased', num_labels=2\n)\n\ndef tokenize(b): return tok(b['text'], truncation=True, padding='max_length', max_length=128)\nds = ds.map(tokenize, batched=True)\n\nargs = TrainingArguments(output_dir='out', per_device_train_batch_size=16, num_train_epochs=2)\nTrainer(model=model, args=args, train_dataset=ds['train'], eval_dataset=ds['val']).train()" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d54-p4", day: 54, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Use distilled / small variants for production",
        copy: "💡 Pro tip — full BERT-large is overkill for most production tasks. Use distilled or small variants.\n\n📦 The ecosystem of small encoder models in 2026:\n\n🔹 DistilBERT (66M params). 40% smaller than BERT-base, 60% faster, retains 97% of accuracy. Ideal for production where latency matters.\n\n🔹 MiniLM / all-MiniLM-L6-v2 (22M params). Tiny but excellent for sentence embeddings. Industry standard for free, self-hosted embeddings. Runs on CPU at decent speed.\n\n🔹 BAAI/bge-small (33M params, 384 dim). Modern lightweight embedding model. Strong on MTEB. Fast.\n\n🔹 BAAI/bge-base (110M, 768 dim). Mid-size. Best balance for most retrieval.\n\n🔹 BAAI/bge-large (335M, 1024 dim). Highest quality from this family. Slower; use when quality is critical.\n\n🔹 RoBERTa-distill, MobileBERT, ALBERT — other distillation lineages.\n\n📊 Why this matters in production:\n\n→ Latency. Smaller models = faster inference. For real-time applications (search, chatbots), the 2-3x speedup of distilled models is huge.\n\n→ Cost. Smaller models fit on CPUs. No GPU needed. CPU instances are 5-10x cheaper than GPU instances.\n\n→ Memory. Distilled models can fit in browser-side WebAssembly. Edge inference becomes possible.\n\n→ Throughput. Same hardware can serve more requests with smaller models. Better cost-per-prediction.\n\n🎯 The trade-off — typically 1-3% accuracy drop. For most production tasks, that's a fine trade for the speed and cost benefits.\n\n💡 The rule — start with the smallest model that meets your accuracy requirements. Don't default to the largest. The marginal accuracy gain rarely justifies the cost overhead.\n\n🚀 For embeddings specifically — bge-small is hard to beat for the cost. Try it first.",
        hashtags: [...CORE, "#MLEngineering"],
        image: { template: "tip", headline: "Distilled / small for production",
          bullets: ["DistilBERT — 40% smaller", "MiniLM-L6 — tiny embedder", "bge-small — modern small", "CPU-friendly = cheap"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d54-p5", day: 54, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 54 — encoders still matter",
        copy: "📅 End of Day 54.\n\n✅ Recap:\n\n👁 BERT = bidirectional encoder + masked language modeling pretraining. 2018 release; still in production use in 2026.\n\n🎯 Use encoders for embeddings, small-data classification, NER, RAG retrieval. Use decoders for generation.\n\n💻 20-line fine-tune with HuggingFace Trainer. Tokenize, set arguments, train. Done.\n\n📦 For production, use distilled / small variants — DistilBERT, MiniLM, bge-small. 1-3% accuracy drop for 2-3x speedup and CPU deployability.\n\n🧠 Reflection — encoders are the unsung workhorse of modern NLP. Every search bar with semantic understanding, every recommendation system, every retrieval-augmented chat — they're all running encoder models in the background. GPT and Claude get the press; BERT family does the heavy lifting.\n\n🚀 Tomorrow, Day 55 — GPT-style decoders. Autoregressive generation. Sampling strategies (greedy, top-k, top-p, temperature). Local LLM with vLLM. Then Day 56: fine-tune vs prompt vs RAG. Then we close week 8.\n\n💼 Three days left in week 8.\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#BERT"],
        image: { template: "quote", headline: "Encoders for understanding.", subhead: "Decoders for generation.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel violet quote card." }
      },
    ]
  },
  /* DAY 55 */
  {
    day: 55, theme: "GPT-style decoders — autoregressive generation", pillar: "ai-ml",
    posts: [
      { id: "d55-p1", day: 55, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Decoder LLMs predict the next token, repeatedly",
        copy: "📅 Day 55. GPT-style models — the architecture behind every modern LLM you've used.\n\n🎯 The objective is shockingly simple — given tokens t_1, t_2, ..., t_n, predict t_{n+1}. Take the predicted token, append it, predict t_{n+2}. Repeat until you have enough output or hit a stop token.\n\nThis is autoregressive generation. The model generates one token at a time, each one informed by everything before it.\n\n📚 Training. Cross-entropy loss on the next token across a huge corpus (trillions of tokens for modern LLMs). The model learns to model P(token | context). Train for months on thousands of GPUs; you have a base LLM.\n\n💬 Then comes instruction tuning. Take the base LLM and fine-tune on (instruction, response) pairs. The model learns to follow instructions. This is the difference between GPT-3 (good at completing text) and ChatGPT (good at answering questions).\n\n📈 Then RLHF (Reinforcement Learning from Human Feedback). Humans rank model outputs; the model learns to produce outputs humans prefer. This is what makes Claude, ChatGPT, Llama-Instruct so useful.\n\n🌐 Inference. Most modern chat is — start with a system prompt + user message; predict the next token; append; repeat until end-of-turn token or max length. The 'thinking' you see is just one token at a time, sampled from a distribution.\n\n🚀 The simplicity is striking. ONE training objective (predict next token), scaled massively (trillions of tokens, hundreds of billions of parameters), gives you GPT-4, Claude 3.5, Llama-3-405B. The intelligence emerges from scale plus good training data.\n\n💡 Understand this loop and modern AI is no longer mysterious. It's a transformer predicting tokens, one at a time, very fast.",
        hashtags: [...CORE, "#GPT"],
        image: { template: "stat", headline: "predict next token", subhead: "The whole training objective.", stat: { number: "1", label: "objective: next-token prediction" }, accent: "violet", aiPrompt: "Stat poster with sequence-arrow glyph, 1:1", canvaBrief: "Violet gradient. Big 1."
        }
      },
      { id: "d55-p2", day: 55, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "Sampling — how the model picks the next token",
        copy: "🎲 The model outputs a probability distribution over the entire vocabulary at each step. The sampling strategy decides which token to pick.\n\n🎯 Four common strategies:\n\n📐 Greedy. argmax of the distribution. Always pick the most-likely token. Deterministic; given the same input, you get the same output. Often produces repetitive, robotic-sounding text. Use for tasks where determinism matters (factual QA, code generation).\n\n🌡 Temperature. Divide logits by T before softmax. T < 1 makes the distribution sharper (more confident, closer to greedy). T > 1 makes it flatter (more random). T = 0 is greedy. T = 1 is the model's natural distribution. For creative writing, T = 0.7-1.0. For factual QA, T = 0 or 0.1.\n\n🔢 Top-k. Keep only the top k tokens by probability; renormalise; sample from those. Limits the candidate set. k = 50 is common. Less likely to pick weird low-probability tokens.\n\n📊 Top-p (nucleus). Keep the smallest set of tokens whose cumulative probability >= p; renormalise; sample from those. Adaptive — sometimes 5 tokens, sometimes 50, depending on how peaked the distribution is. p = 0.9-0.95 is the modern default.\n\n🎯 Combinations:\n\n→ For factual answers — T = 0 or T = 0.1. Greedy or near-greedy.\n\n→ For creative writing — T = 0.7-1.0 with top_p = 0.95. Diverse but not random.\n\n→ For code generation — T = 0 to 0.2. Want correct, not creative.\n\n→ For RAG/Q&A from docs — T = 0. You want the model to ground in the docs, not invent.\n\n→ For brainstorming / idea generation — T = 0.9-1.2 with top_p = 0.95. More diversity.\n\n💡 The 'temperature' parameter people see in OpenAI's playground is exactly this T. Drop it for grounded tasks. Raise it for creative ones.",
        hashtags: [...CORE, "#LLM"],
        image: { template: "list", headline: "Sampling — 4 dials",
          bullets: ["Greedy — deterministic", "Temperature — sharpness", "Top-k — limit options", "Top-p — adaptive (default)"],
          accent: "violet", aiPrompt: "List card, 1:1", canvaBrief: "White grid, 4 rows."
        }
      },
      { id: "d55-p3", day: 55, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "Generate text with a small open LLM",
        copy: "💻 Twenty lines to load a small open LLM and generate text locally. transformers + a 1B-3B parameter model is the perfect size for laptops with 16GB RAM.\n\nLook at the snippet.\n\n📦 Imports — AutoTokenizer, AutoModelForCausalLM, torch.\n\n🔧 Load model:\n→ name = 'meta-llama/Llama-3.2-1B-Instruct'. The Instruct variant is fine-tuned for chat. The 1B size runs on a laptop.\n→ tok = AutoTokenizer.from_pretrained(name).\n→ model = AutoModelForCausalLM.from_pretrained(name, torch_dtype='auto'). torch_dtype='auto' picks the best precision (bf16 on supported hardware, fp32 fallback).\n\n📝 Prompt — 'Explain RAG in two sentences.'.\n\n🔢 Encode — tok(prompt, return_tensors='pt').input_ids.\n\n🎯 Generate:\n→ model.generate(ids, max_new_tokens=80, temperature=0.7, top_p=0.95).\n→ max_new_tokens=80 limits the output length.\n→ temperature=0.7 + top_p=0.95 — moderate creativity.\n\n📝 Decode — tok.decode(out[0], skip_special_tokens=True). Get back text. The model's response will be appended to your prompt; you typically slice off the input portion.\n\n🚀 The whole loop runs in seconds for 80 tokens on a modern laptop. Great for prototyping, evaluation harnesses, and learning.\n\n📊 Model size guide for laptops:\n→ 1B params — fits in ~4GB memory. Runs comfortably on most laptops. Quality good for simple tasks.\n→ 3B params — ~6GB memory. Better quality. Borderline on 8GB laptops.\n→ 7-8B params — ~16GB. Needs a decent GPU or 32GB+ system RAM. Quality competitive with hosted models for many tasks.\n→ 70B+ — needs server-class hardware. Use cloud or APIs.\n\n💡 For local production deployment (more than just generating one prompt at a time), use vLLM (next post). The naive .generate() loop is fine for tutorials, awful for serving.",
        hashtags: [...CORE, "#HuggingFace"],
        image: { template: "code", headline: "Local LLM generation",
          code: { language: "python", snippet: "from transformers import AutoTokenizer, AutoModelForCausalLM\nimport torch\n\nname = 'meta-llama/Llama-3.2-1B-Instruct'\ntok = AutoTokenizer.from_pretrained(name)\nmodel = AutoModelForCausalLM.from_pretrained(name, torch_dtype='auto')\n\nprompt = 'Explain RAG in two sentences.'\nids = tok(prompt, return_tensors='pt').input_ids\nout = model.generate(ids, max_new_tokens=80, temperature=0.7, top_p=0.95)\nprint(tok.decode(out[0], skip_special_tokens=True))" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d55-p4", day: 55, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Use vLLM for any serious local inference",
        copy: "💡 Pro tip — for serious local LLM inference, use vLLM (or llama.cpp). transformers' .generate() is fine for tutorials but terrible for production.\n\n⚡ vLLM. State-of-the-art LLM inference engine. Open source, pip install vllm. Serves models with an OpenAI-compatible API.\n\n📊 What it does:\n\n→ Paged attention. Memory-efficient KV cache that allows much higher batch sizes. The KV cache is divided into pages and managed like virtual memory; less wasted memory.\n\n→ Continuous batching. Doesn't wait for a fixed batch to fill before processing. New requests join the batch in flight. Throughput stays high regardless of request timing.\n\n→ FlashAttention integration. Fastest attention implementations.\n\n→ Quantisation support — INT8, INT4, AWQ, GPTQ. Run larger models with less memory.\n\nReal numbers — for Llama-3-8B on an A100 GPU:\n→ Naive .generate() — ~50 tokens/sec, single request only.\n→ vLLM — ~1500 tokens/sec across 32 concurrent requests. 30x throughput.\n\n🛠 Quick setup:\n\nfrom vllm import LLM\n\nllm = LLM(model='meta-llama/Llama-3.2-3B-Instruct')\noutputs = llm.generate('Explain RAG in two sentences.')\nprint(outputs[0].outputs[0].text)\n\nOr serve as an OpenAI-compatible API:\nvllm serve meta-llama/Llama-3.2-3B-Instruct\n\nThen point your OpenAI client at http://localhost:8000.\n\n🦀 llama.cpp. Alternative for CPU and consumer GPUs. C++ implementation; supports GGUF quantised models. Best for laptops, edge devices, no-GPU setups.\n\n💻 Use llama.cpp on a MacBook M-series, Windows laptop without a discrete GPU, or anywhere you need to run LLMs without cloud infrastructure. Surprisingly fast on Apple Silicon thanks to unified memory.\n\n📋 The decision tree:\n→ Have a NVIDIA GPU, want max throughput → vLLM.\n→ Want CPU/laptop inference → llama.cpp.\n→ Just prototyping → transformers .generate().\n\n💡 Don't ship .generate() to production. The paths above are easier and orders of magnitude faster.",
        hashtags: [...CORE, "#vLLM"],
        image: { template: "tip", headline: "Use vLLM in production",
          bullets: ["10-30x throughput", "OpenAI-compatible API", "PagedAttention memory", "Or llama.cpp for CPU"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d55-p5", day: 55, postNumber: 5, slot: "night", type: "recap", pillar: "ai-ml",
        title: "Day 55 — generation, framed",
        copy: "📅 End of Day 55.\n\n✅ Recap:\n\n🎯 Decoder LLMs predict the next token autoregressively. Train on trillions of tokens. Add instruction tuning + RLHF. You have ChatGPT/Claude.\n\n🎲 Four sampling dials — greedy, temperature, top-k, top-p. T=0 for factual; T=0.7 + top_p=0.95 for creative.\n\n💻 20-line local LLM with transformers + Llama-3.2-1B-Instruct. Runs on a laptop.\n\n⚡ Use vLLM for serious local inference. 10-30x throughput vs naive .generate(). OpenAI-compatible API for easy integration.\n\n🧠 Reflection — the gap between 'how it works' and 'how to use it well' is huge for LLMs. The architecture is simple. The engineering of training and serving is enormous. Most ML engineers spend their time on the engineering side; the architecture is library code.\n\n🚀 Tomorrow, Day 56 — fine-tune vs prompt vs RAG. The decision tree for adapting LLMs to your problem. LoRA and QLoRA for cheap fine-tuning. Always-evaluate-fine-tunes-vs-base. Then we close week 8.\n\n💼 One more day in week 8. Then RAG (week 9-10).\n\n👋 See you in the morning.",
        hashtags: [...CORE, "#GPT"],
        image: { template: "quote", headline: "Predict next token. Append. Repeat.", subhead: "Modern chat in three steps.", accent: "violet", aiPrompt: "Pastel violet quote, 1:1", canvaBrief: "Pastel quote card." }
      },
    ]
  },
  /* DAY 56 */
  {
    day: 56, theme: "Fine-tune or prompt? + week 8 wrap", pillar: "ai-ml",
    posts: [
      { id: "d56-p1", day: 56, postNumber: 1, slot: "morning", type: "concept", pillar: "ai-ml",
        title: "Prompt > RAG > Fine-tune (in that order)",
        copy: "📅 Day 56. Last day of week 8. Before we go into RAG next week, let's frame when to use what.\n\n🎯 When you want an LLM to do something new, try in this order:\n\n1️⃣ Better prompting. A clearer system prompt + few-shot examples solves 60% of cases. Cheap (no compute), fast (immediate iteration), reversible (just edit text). The first thing to try.\n\n2️⃣ RAG (Retrieval-Augmented Generation). If it's a knowledge problem — the model lacks information about your domain or recent events — retrieve relevant docs and stuff them into the prompt. Doesn't change the model; provides it with knowledge.\n\n3️⃣ Fine-tuning. If you need a different style, format, or specialised behaviour at scale — and prompting alone can't get you there — fine-tune. Modifies the model's weights to bake in patterns you want.\n\n📋 Why this order:\n\n→ Prompting is free. Zero training cost. Zero infrastructure cost. Just tokens.\n\n→ RAG is moderate. You pay for embeddings + a vector DB + a few extra tokens per request. Knowledge updates instantly when you re-index docs.\n\n→ Fine-tuning is expensive. GPU compute for training. New model artifact to maintain. Requires re-fine-tuning when the base model updates. Brittle — small data shifts can require retraining.\n\n💸 Most teams jump to fine-tune too early. They have a problem prompting could solve in an afternoon; they spend two weeks fine-tuning. The result is no better, more expensive to maintain, and locked to a specific model version.\n\n🎯 The disciplined approach — try cheap things first. Move down the cost curve only when needed.\n\n💡 Most production LLM apps in 2026 use prompting + RAG. Fine-tuning is reserved for specific cases — distilling a large model into a small one, or training a model on private data that can't be retrieved at inference.\n\n🚀 Start cheap. Stop early.",
        hashtags: [...CORE, "#LLM"],
        image: { template: "list", headline: "Order of operations",
          bullets: ["1. Better prompt", "2. RAG (knowledge)", "3. Fine-tune (style/format/scale)", "Stop early if it works"],
          accent: "violet", aiPrompt: "Three-tier infographic, 1:1", canvaBrief: "White grid. 3 numbered tiers."
        }
      },
      { id: "d56-p2", day: 56, postNumber: 2, slot: "midday", type: "deepdive", pillar: "ai-ml",
        title: "LoRA — fine-tune big models with small budgets",
        copy: "💰 Full fine-tuning of a 7B model needs roughly 80GB+ of GPU memory (for the weights, gradients, optimiser states, and activations). Most people don't have an A100 or H100 sitting around.\n\n🎯 LoRA (Low-Rank Adaptation) solves this. Released in 2021; standard practice by 2023.\n\n🧮 The idea — instead of updating all the model's weights, freeze them. Add small trainable matrices ('LoRA adapters') alongside each layer. The forward pass becomes — original_weight @ x + lora_a @ lora_b @ x. lora_a and lora_b are tiny (typically rank 8-64), much smaller than the full weight.\n\n📊 Numbers — for Llama-3-8B:\n→ Full fine-tune trains 8B parameters. ~80GB GPU.\n→ LoRA fine-tune trains ~10M parameters (0.1% of the original). ~24GB GPU.\n\nQuality is usually within 1-2% of full fine-tuning, often equivalent on most tasks.\n\n🔧 QLoRA combines LoRA with 4-bit quantisation of the base model. The base model is loaded in 4-bit (saving 4x memory) and the LoRA adapters are trained in fp16. Now you can fine-tune Llama-3-8B on a single 16GB GPU.\n\n📦 Libraries:\n→ peft — HuggingFace's parameter-efficient fine-tuning library. Implements LoRA, prefix-tuning, IA3, and more.\n→ trl — for SFT (supervised fine-tuning), DPO (direct preference optimisation), and GRPO. Uses peft underneath.\n→ Axolotl — declarative YAML config for fine-tuning. Pick model, dataset, method; one command runs it.\n→ unsloth — optimised LoRA training. 2x faster than standard implementations.\n\n💼 The democratisation of fine-tuning. In 2023, fine-tuning a 7B model required cloud GPUs. By 2026, you can do it on a consumer M-series MacBook (slowly) or a single 16GB consumer GPU (fast).\n\n💡 LoRA changed who can fine-tune. Now anyone with a modest GPU can adapt large models to specific tasks.",
        hashtags: [...CORE, "#LoRA"],
        image: { template: "stat", headline: "0.1% of params", subhead: "LoRA fine-tunes the rest", stat: { number: "0.1%", label: "of params updated by LoRA" }, accent: "violet", aiPrompt: "Stat poster, 1:1", canvaBrief: "Violet gradient. Big 0.1%."
        }
      },
      { id: "d56-p3", day: 56, postNumber: 3, slot: "afternoon", type: "code", pillar: "ai-ml",
        title: "QLoRA fine-tune in 20 lines",
        copy: "💻 QLoRA fine-tune of a 1B model. Twenty lines. Fits in a 16GB consumer GPU; on a Mac with unified memory, even less.\n\nLook at the snippet.\n\n📦 Imports — peft for LoRA, transformers for model loading, BitsAndBytesConfig for quantisation.\n\n🔧 Quantisation config:\n→ load_in_4bit=True. Load the base model in 4-bit precision.\n→ bnb_4bit_compute_dtype=torch.bfloat16. Use bf16 for forward/backward computation (more numerically stable than fp16).\n\n📦 Load base model:\n→ AutoModelForCausalLM.from_pretrained(name, quantization_config=bnb).\n→ The base loads in 4-bit. ~1GB memory for a 1B model (vs 4GB in fp32).\n\n🎯 LoRA config:\n→ r=16. The rank of the LoRA matrices. Higher = more parameters, more capacity, more overfitting risk. 8-32 is the typical range.\n→ lora_alpha=32. Scaling factor. Common choice — alpha = 2 * r.\n→ target_modules=['q_proj','v_proj']. Apply LoRA to the attention's Q and V projections. Typical for Llama-family. Some setups also add 'k_proj', 'o_proj', or all linear layers.\n→ task_type='CAUSAL_LM'. We're fine-tuning for causal language modeling.\n\n🚀 Wrap base model:\n→ model = get_peft_model(base, cfg). Returns a model with LoRA adapters added. The base weights are frozen; only the LoRA adapters are trainable.\n\n📊 model.print_trainable_parameters() — typically reports 'trainable: ~0.1% of total'. Huge savings.\n\n💼 What's next (not in the snippet):\n→ Prepare a dataset of (prompt, response) pairs.\n→ Tokenise with the model's tokenizer.\n→ Use trl's SFTTrainer (or HuggingFace Trainer with DataCollatorForLanguageModeling) to train.\n→ At the end, save the LoRA adapter (a few MB). Load alongside the base for inference.\n\n💡 The full training pipeline is ~50 lines with TRL. Axolotl reduces it to a YAML config + one command.\n\n🚀 Production fine-tuning is now within reach for anyone with a $500 GPU.",
        hashtags: [...CORE, "#PEFT"],
        image: { template: "code", headline: "QLoRA — minimum viable",
          code: { language: "python", snippet: "from peft import LoraConfig, get_peft_model\nfrom transformers import (\n    AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig\n)\nimport torch\n\nbnb = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.bfloat16)\nbase = AutoModelForCausalLM.from_pretrained(\n    'meta-llama/Llama-3.2-1B-Instruct', quantization_config=bnb\n)\ncfg = LoraConfig(r=16, lora_alpha=32, target_modules=['q_proj','v_proj'], task_type='CAUSAL_LM')\nmodel = get_peft_model(base, cfg)\nmodel.print_trainable_parameters()  # ~0.1% of base" },
          accent: "violet", aiPrompt: "Dark code card, 1:1", canvaBrief: "Dark gradient code window."
        }
      },
      { id: "d56-p4", day: 56, postNumber: 4, slot: "evening", type: "tip", pillar: "ai-ml",
        title: "Evaluate fine-tunes against the base, not against your hopes",
        copy: "💡 Pro tip — after fine-tuning, every output looks great. That's confirmation bias. ALWAYS evaluate the fine-tuned model against the base model on the same held-out test set.\n\n🚨 The trap. You spent two weeks fine-tuning. You see the model outputs and feel pride. You ship it. Three weeks later, someone asks 'is this actually better than the base model?' You don't know.\n\n📊 The discipline:\n\n1️⃣ Hold out a test set BEFORE fine-tuning. 100-500 examples that the model never sees during training. Cover the use cases you care about — easy ones, hard ones, edge cases.\n\n2️⃣ Evaluate the BASE model on the test set. Get its score. This is your floor. Document it.\n\n3️⃣ Fine-tune.\n\n4️⃣ Evaluate the FINE-TUNED model on the SAME test set. Get its score.\n\n5️⃣ Compare. The fine-tune should beat the base by a meaningful margin (e.g., 5+ points on accuracy, or substantially better on qualitative review).\n\n🎯 If it doesn't, the fine-tune isn't worth the cost. Roll it back. Use the base model. Save the maintenance burden.\n\n📋 How to evaluate qualitative outputs (e.g., generated text quality):\n\n→ Use a stronger LLM as judge. GPT-4o or Claude 3.5 Sonnet rates outputs on a 1-5 scale or compares pairs. Cheap, fast, reproducible.\n\n→ Use a panel of human evaluators on a sample. Slower, more accurate, captures things LLMs miss.\n\n→ Use task-specific metrics where they apply (BLEU for translation, accuracy for classification).\n\n💡 The key principle — the comparison must be apples-to-apples. Same test set. Same scoring method. Different models.\n\n🚨 Common mistake — only looking at fine-tune outputs, never comparing. Always go back to the base. It might already be good enough; you'd save weeks of effort.\n\n🚀 Fine-tunes that don't beat baseline are technical debt. Don't ship them.",
        hashtags: [...CORE, "#Evaluation"],
        image: { template: "tip", headline: "Always compare fine-tune vs base",
          bullets: ["Same held-out set", "Use a stronger LLM as judge", "Quantify the lift", "Roll back if marginal"],
          accent: "violet", aiPrompt: "Pro tip card, 1:1", canvaBrief: "Violet header. PRO TIP."
        }
      },
      { id: "d56-p5", day: 56, postNumber: 5, slot: "night", type: "recap", pillar: "career",
        title: "Week 8 done — NLP and transformers",
        copy: "📅 End of Day 56. End of week 8. We're 62% through the sprint.\n\n✅ Week 8 in seven topics:\n\n📝 Tokenisation. BPE/subword units. Tokens ≠ words. Always count before API calls.\n\n🧭 Embeddings. Coordinates of meaning. Pick by cost/dim/domain. Always normalise.\n\n🎯 Attention. Q, K, V, softmax(QKᵀ/√d) · V. Multi-head for parallel perspectives. F.scaled_dot_product_attention for production.\n\n🏗 Transformer block. LayerNorm + Attention + Residual + LayerNorm + MLP + Residual. Stack to depth. Don't write your own; use HF transformers.\n\n👁 BERT and encoders. Bidirectional + MLM pretraining. Use for embeddings, small-data classification, NER. Distilled variants for production.\n\n🎯 GPT and decoders. Autoregressive next-token prediction. Sampling dials (T, top-k, top-p). vLLM for production inference.\n\n🛠 Fine-tune vs prompt vs RAG. Try cheap first. LoRA/QLoRA make fine-tuning accessible. Always compare fine-tune to base.\n\n🧠 Big takeaway from week 8 — modern AI rests on the transformer architecture. Same building block (attention + MLP), different masks (encoder vs decoder), different scales (millions to trillions of parameters). Understanding the block makes every paper and every framework readable.\n\n🚀 Next week — RAG. The architecture that powers most LLM apps you'll build in 2026. We've covered all the components — embeddings, encoders, decoders, sampling. Now we put them together.\n\n💼 We're 62% through. Five weeks to go. RAG (week 9-10), agents (11), automation (12), career (13).\n\n👋 See you in week 9.",
        hashtags: [...CORE, "#90DaysOfAI"],
        image: { template: "quote", headline: "8 weeks down. 5 to go.", subhead: "Next week: RAG fundamentals.", accent: "violet", aiPrompt: "Pastel violet quote with 56/90 progress, 1:1", canvaBrief: "Pastel violet quote with 56/90 violet bar." }
      },
    ]
  },
];
